;;; org-workflow-planning-test.el -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-agenda)
(require 'org-workflow-planning)
(unless (fboundp 'org-workflow-store-test)
  (load (expand-file-name "org-workflow-store-test.el" (file-name-directory load-file-name)) nil t))
(ert-deftest workflow-planning-readonly-includes-next-stage ()
  (org-workflow-store-test
   (goto-char (point-max)) (insert "* Next\n** TODO Second\n* Later\n** TODO Excluded\n")
   (let* ((before (buffer-string)) (modified (buffer-modified-p))
          (context (org-workflow-planning-context file 26))
          (titles (mapcar (lambda (row) (plist-get row :title)) (plist-get context :tasks))))
     (should (member "Second" titles)) (should-not (member "Excluded" titles))
     (should (equal before (buffer-string))) (should (eq modified (buffer-modified-p))))))
(ert-deftest workflow-planning-rejects-stale-and-rolls-back ()
  (org-workflow-store-test
   (let* ((pos (point))
          (proposal (list :version 1 :file file :hash (org-workflow-planning--hash)
                          :suggestions (list (list :position pos :title "Task" :tag "@deep" :effort "1:00")))))
     (org-workflow-planning--validate proposal)
     (let ((org-workflow-planning--proposal proposal)
           (org-workflow-planning--selected (list pos))
           (before (buffer-string)))
       (cl-letf (((symbol-function 'org-entry-put) (lambda (&rest _) (error "injected"))))
         (should-error (org-workflow-planning-accept)))
       (should (equal before (buffer-string))))
     (goto-char (point-max)) (insert "changed")
     (should-error (org-workflow-planning--validate proposal) :type 'user-error))))
(ert-deftest workflow-planning-preserves-manual-values ()
  (org-workflow-store-test
   (org-set-tags '("@tiny")) (org-entry-put nil "EFFORT" "0:15")
   (let* ((pos (point))
          (org-workflow-planning--proposal
           (list :version 1 :file file :hash (org-workflow-planning--hash)
                 :suggestions (list (list :position pos :title "Task" :tag "@deep" :effort "1:00" :boundary "Explain it"))))
          (org-workflow-planning--selected (list pos)))
     (cl-letf (((symbol-function 'quit-window) #'ignore)) (org-workflow-planning-accept))
     (goto-char pos)
     (should (member "@tiny" (org-get-tags))) (should-not (member "@deep" (org-get-tags)))
     (should (equal "0:15" (org-entry-get nil "EFFORT")))
     (should (equal "Explain it" (org-entry-get nil "WORKFLOW_BOUNDARY"))))))
(ert-deftest workflow-planning-last-sibling-stays-in-subtree ()
  (org-workflow-store-test
   (let* ((context (org-workflow-planning-context file (point)))
          (titles (mapcar (lambda (row) (plist-get row :title)) (plist-get context :tasks))))
     (should (equal titles '("Task"))))))
(ert-deftest workflow-planning-batch-error-restores-all-rows ()
  (org-workflow-store-test
   (goto-char (point-max)) (insert "** TODO Second\n")
   (let* ((second (line-beginning-position 0))
          (first (save-excursion (goto-char (point-min)) (search-forward "** TODO Task") (line-beginning-position)))
          (before (buffer-string))
          (org-workflow-planning--proposal
           (list :version 1 :file file :hash (org-workflow-planning--hash)
                 :suggestions (list (list :position first :title "Task" :tag "@deep" :effort "1:00")
                                    (list :position second :title "Second" :tag "@tiny" :effort "0:10"))))
          (org-workflow-planning--selected (list first second))
          (put (symbol-function 'org-entry-put)) (calls 0))
     (cl-letf (((symbol-function 'org-entry-put)
                (lambda (&rest args)
                  (cl-incf calls)
                  (if (= calls 2) (error "second row fails") (apply put args)))))
       (should-error (org-workflow-planning-accept)))
     (should (= calls 2))
     (should (equal before (buffer-string))))))
