;;; org-workflow-guidance-test.el -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-agenda)
(unless (fboundp 'org-workflow-store-test)
  (load (expand-file-name "org-workflow-store-test.el" (file-name-directory load-file-name)) nil t))
(ert-deftest workflow-panel-focus-start-is-idempotent-and-query-is-not-start ()
  (org-workflow-store-test
   (should-not (org-workflow-store-meta "started:2026-09-16"))
   (org-workflow-panel--focus-started 'short-break)
   (should-not (org-workflow-store-meta "started:2026-09-16"))
   (org-workflow-panel--focus-started 'focus)
   (let ((first (org-workflow-store-meta "started:2026-09-16")))
     (org-workflow-panel--focus-started 'focus)
     (org-workflow-panel-invalidate)
     (should (equal first (org-workflow-store-meta "started:2026-09-16"))))))
(ert-deftest workflow-panel-week-uses-sealed-achievement-not-current-sources ()
  (let ((org-workflow-store-enabled t))
    (cl-letf (((symbol-function 'org-workflow-store-day)
               (lambda (date)
                 (cond ((equal date "2026-09-21") '(:commitment "met" :minimumTasks []))
                       ((equal date "2026-09-22") '(:commitment "unmet" :minimumTasks [(:focusMinutes 25)])))))
              ((symbol-function 'org-workflow-store-leaves) (lambda (_) nil))
              ((symbol-function 'org-agenda-files) (lambda (&rest _) '("/missing/source.org")))
              ((symbol-function 'org-workflow-history--tasks) (lambda (_) (error "must not read source"))))
      (let ((week (org-workflow-panel--week "2026-09-24")))
        (should (equal (mapcar (lambda (day) (plist-get day :state)) week)
                       '("complete" "incomplete" "unknown" "unknown" "future" "future" "future")))
        (should (equal "commitment" (plist-get (aref week 0) :basis)))
        (should-not (plist-get (aref week 2) :basis))))))
(ert-deftest workflow-panel-no-commitment-investment-includes-habits-and-done ()
  (cl-letf (((symbol-function 'org-agenda-files) (lambda (&rest _) nil))
            ((symbol-function 'org-workflow-history-progress) (lambda (_) '(:minimumTotal 0)))
            ((symbol-function 'org-workflow-history--habit-records) (lambda (_) nil)))
    (dolist (rows '(nil ((:focusMinutes 0 :outcome "pending"))
                    ((:focusMinutes 5 :outcome "focused"))
                    ((:focusMinutes 0 :outcome "done"))))
      (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) rows)))
        (let ((day (org-workflow-panel--day-achievement "2026-09-16" "2026-09-16")))
          (should (equal "investment" (plist-get day :basis)))
          (should (equal (if (org-workflow-panel--invested-p rows) "complete" "incomplete")
                         (plist-get day :state))))))
    (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) nil)))
      (dolist (row '((:focusMinutes 10 :outcome "focused") (:focusMinutes 0 :outcome "done")))
        (cl-letf (((symbol-function 'org-workflow-history--habit-records) (lambda (_) (list row))))
          (should (equal "complete" (plist-get (org-workflow-panel--day-achievement
                                               "2026-09-16" "2026-09-16") :state))))))))
(ert-deftest workflow-panel-commitments-require-every-dated-commitment ()
  (org-workflow-store-test
   (org-workflow-store-set-meta "attempt-progress-since" "2026-09-16")
   (let ((db (org-workflow-store--db)))
     (sqlite-execute db "INSERT INTO commitments VALUES('one','one-task','2026-09-16T09:00:00+08:00','2026-09-16','One','One','pending',0)")
     (sqlite-execute db "INSERT INTO commitments VALUES('two','two-task','2026-09-16T09:00:00+08:00','2026-09-16','Two','Two','pending',0)")
     (cl-letf (((symbol-function 'org-workflow-history--habit-records)
                (lambda (_) '((:focusMinutes 25 :outcome "done")))))
       (dolist (tasks '(((:id "one-task" :focusMinutes 25 :outcome "focused"))
                        ((:id "one-task" :focusMinutes 25 :outcome "focused")
                         (:id "two-task" :focusMinutes 1 :outcome "focused"))))
         (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) tasks)))
           (let ((day (org-workflow-panel--day-achievement "2026-09-16" "2026-09-16")))
             (should (equal "commitment" (plist-get day :basis)))
             (should (equal (if (= 2 (length tasks)) "complete" "incomplete")
                            (plist-get day :state))))))))))
(ert-deftest workflow-panel-historical-no-commitment-uses-sealed-investment ()
  (let ((org-workflow-store-enabled t))
    (dolist (rows '(nil [(:focusMinutes 0 :outcome "done")] [(:focusMinutes 4 :outcome "focused")]))
      (cl-letf (((symbol-function 'org-workflow-store-day)
                 (lambda (_) (list :commitment "untouch" :habitTasks rows)))
                ((symbol-function 'org-agenda-files) (lambda (&rest _) (error "must not read sources"))))
        (let ((day (org-workflow-panel--day-achievement "2026-09-15" "2026-09-16")))
          (should (equal "investment" (plist-get day :basis)))
          (should (equal (if rows "complete" "incomplete") (plist-get day :state))))))))

(ert-deftest workflow-panel-time-sums-task-and-habit-records-without-changing-achievement ()
  (cl-letf (((symbol-function 'org-agenda-files) (lambda (&rest _) nil))
            ((symbol-function 'org-workflow-history-progress)
             (lambda (_) '(:minimumTotal 2 :commitmentComplete :false)))
            ((symbol-function 'org-workflow-history--tasks)
             (lambda (_) '((:focusMinutes 100) (:focusMinutes 200))))
            ((symbol-function 'org-workflow-history--habit-records)
             (lambda (_) (should-not org-clock-report-include-clocking-task)
               '((:focusMinutes 5)))))
    (let ((day (org-workflow-panel--day-achievement "2026-09-16" "2026-09-16")))
      (should (= 305 (plist-get day :focusMinutes)))
      (should (equal "incomplete" (plist-get day :state))))))

(ert-deftest workflow-panel-time-reads-sealed-total-without-recalculation ()
  (let ((org-workflow-store-enabled t)
        (record '(:commitment "met" :focusTotalMinutes 605)))
    (cl-letf (((symbol-function 'org-workflow-store-day) (lambda (_) record))
              ((symbol-function 'org-workflow-history--tasks) (lambda (_) (error "must not recompute"))))
      (let ((day (org-workflow-panel--day-achievement "2026-09-15" "2026-09-16")))
        (should (= 605 (plist-get day :focusMinutes)))
        (should (equal "complete" (plist-get day :state)))
        (should (equal record '(:commitment "met" :focusTotalMinutes 605)))))))
(ert-deftest workflow-panel-commitment-leave-does-not-replace-success-or-unknown ()
  (let ((org-workflow-store-enabled t))
    (cl-letf (((symbol-function 'org-workflow-store-leaves)
               (lambda (_) [(:reason "social" :slots ["evening"])])))
      (dolist (commitment '("met" "unmet" nil))
        (cl-letf (((symbol-function 'org-workflow-store-day)
                   (lambda (_) (when commitment (list :commitment commitment)))))
          (let ((day (aref (org-workflow-panel--week "2026-09-16") 1)))
            (should (equal (pcase commitment ("met" "complete") ("unmet" "leave") (_ "unknown"))
                           (plist-get day :state)))
            (should (= 1 (length (plist-get day :leaveRecords))))))))))
(ert-deftest workflow-panel-day-boundary-replaces-live-result-with-sealed-result ()
  (let ((org-workflow-store-enabled t))
    (cl-letf (((symbol-function 'org-workflow-store-leaves) (lambda (_) nil))
              ((symbol-function 'org-workflow-store-day) (lambda (_) '(:commitment "met")))
              ((symbol-function 'org-agenda-files) (lambda (&rest _) nil))
              ((symbol-function 'org-workflow-history-progress)
               (lambda (_) '(:minimumTotal 1 :commitmentComplete :false)))
              ((symbol-function 'org-workflow-history--habit-records) (lambda (_) nil)))
      (should (equal "incomplete" (plist-get (aref (org-workflow-panel--week "2026-09-16") 2) :state)))
      (should (equal "complete" (plist-get (aref (org-workflow-panel--week "2026-09-17") 2) :state))))))
(ert-deftest workflow-panel-first-focus-survives-reopen-and-day-boundary ()
  (org-workflow-store-test
   (cl-letf (((symbol-function 'org-workflow-panel--week) (lambda (_) []))
             ((symbol-function 'org-workflow-panel--habits) (lambda (_) []))
             ((symbol-function 'org-workflow-guidance-opening) (lambda (_) nil))
             ((symbol-function 'org-workflow-guidance-current) (lambda () nil)))
     (org-workflow-panel-invalidate)
     (should (eq :false (plist-get (org-workflow-panel-status) :started)))
     (should-not (org-workflow-store-meta "started:2026-09-16"))
     (org-workflow-panel--focus-started 'focus)
     (sqlite-close org-workflow-store--connection)
     (setq org-workflow-store--connection nil)
     (org-workflow-panel-invalidate)
     (should (eq t (plist-get (org-workflow-panel-status) :started)))
     (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-17")))
       (should (eq :false (plist-get (org-workflow-panel-status) :started)))))))
