;;; org-workflow-history-panel-test.el --- Read-only panel contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-history)
(require 'org-workflow-history-panel nil t)
(unless (featurep 'org-workflow-history-view-test)
  (load (expand-file-name "org-workflow-history-view-test.el"
                          (file-name-directory (or load-file-name buffer-file-name))) nil t))
(unless (featurep 'org-workflow-web-export-test)
  (load (expand-file-name "org-workflow-web-export-test.el"
                          (file-name-directory (or load-file-name buffer-file-name))) nil t))

(defconst workflow-history-test--advice
  '((org-workflow-web-export--candidate-records . org-workflow-history--export-candidates)
    (org-workflow-web-export--finalized-day . org-workflow-history--export-day)
    (org-workflow-web-export--tracking-started . org-workflow-history--export-anchor)
    (org-workflow-web-export--eligible-through . org-workflow-history--export-cutoff)
    (org-workflow-web-export--days . org-workflow-history--export-leaves)
    (org-workflow-journal-finalized-record . org-workflow-history--record)))
(defconst workflow-history-test--now (encode-time 0 0 12 17 9 2026))
(defconst workflow-history-test--day
  '(:date "2026-09-15" :recordState "finalized" :commitment "met"
    :finalizedAt "2026-09-16T00:00:00+08:00" :commitmentFocusMinutes 25
    :optionalFocusMinutes 5 :focusTotalMinutes 30 :optionalCompleted 0 :minimumTasks [] :optionalTasks []))

(defmacro workflow-history-test--store (&rest body)
  (declare (indent 0) (debug t))
  `(let* ((directory (make-temp-file "history-panel-" t))
          (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
          (org-workflow-store-enabled t)
          (org-workflow-store--connection nil) (org-workflow-store--path nil)
          (added nil))
     (unwind-protect
         (progn
           (dolist (pair workflow-history-test--advice)
             (unless (advice-member-p (cdr pair) (car pair))
               (advice-add (car pair) :around (cdr pair)) (push pair added)))
           ,@body)
       (dolist (pair added) (advice-remove (car pair) (cdr pair)))
       (when (org-workflow-store--live-p org-workflow-store--connection)
         (sqlite-close org-workflow-store--connection))
       (when (get-buffer "*Workflow History*") (kill-buffer "*Workflow History*"))
       (delete-directory directory t))))

(ert-deftest workflow-history-tracer-read-render ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
    (should (fboundp 'org-workflow-history-panel))
    (let ((window (selected-window)) (displayed nil))
      (cl-letf (((symbol-function 'sqlite-execute)
                 (lambda (&rest _) (ert-fail "Read path attempted SQLite write")))
                ((symbol-function 'display-buffer)
                 (lambda (buffer &rest _)
                   (should (eq window (selected-window)))
                   (setq displayed buffer))))
        (let ((buffer (org-workflow-history-panel workflow-history-test--now)))
          (should (eq buffer displayed))
          (with-current-buffer buffer
            (should vui--root-instance)
            (should (equal "2026-09-16" (plist-get org-workflow-history-panel--model :selected-date)))
            (should (string-match-p "Workflow 历史" (buffer-string)))
            (should (string-match-p "2026-09-15.*2026-09-16" (buffer-string)))))))))

(ert-deftest workflow-history-tracer-backend-not-ready ()
  (workflow-history-test--store
    (setq org-workflow-store-file (expand-file-name "absent/facts.sqlite" directory))
    (should (fboundp 'org-workflow-history-panel))
    (cl-letf (((symbol-function 'display-buffer) #'ignore))
      (with-current-buffer (org-workflow-history-panel workflow-history-test--now)
        (should (string-match-p "无法读取历史" (buffer-string)))))
    (should-not (file-exists-p (file-name-directory org-workflow-store-file)))))

(ert-deftest workflow-history-panel-select-cutoff-missing-bounds-cancel ()
  (let ((payload (workflow-history-view-test--payload
                  (workflow-history-view-test--day "2026-09-15" "missing")
                  (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (should (equal "2026-09-16" (plist-get org-workflow-history-panel--model :selected-date)))
      (org-workflow-history-panel-select-date "2026-09-15")
      (let ((before org-workflow-history-panel--model))
        (org-workflow-history-panel-select-date "2025-01-01")
        (should (eq before org-workflow-history-panel--model))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil))))
          (org-workflow-history-panel-select-date))
        (should (eq before org-workflow-history-panel--model))))))
(ert-deftest workflow-history-panel-select-refresh-preserve-fallback-clear ()
  (let ((payload (workflow-history-view-test--payload
                  (workflow-history-view-test--day "2026-09-15" "missing")
                  (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (org-workflow-history-panel-select-date "2026-09-15")
      (org-workflow-history-panel-refresh)
      (should (equal "2026-09-15" (plist-get org-workflow-history-panel--model :selected-date)))
      (setq payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16")))
      (org-workflow-history-panel-refresh)
      (should (equal "2026-09-16" (plist-get org-workflow-history-panel--model :selected-date)))
      (should (string-match-p "原选中日期已不在历史范围内，已选择 2026-09-16。" (buffer-string)))
      (setq payload (workflow-history-view-test--payload))
      (org-workflow-history-panel-refresh)
      (should-not (plist-get org-workflow-history-panel--model :selected-date))
      (should (string-match-p "当前历史范围为空，已清除日期选择。" (buffer-string)))
      (should-not (string-match-p "查看日期：" (buffer-string))))))
(ert-deftest workflow-history-panel-refresh-first-error-empty-retry ()
  (let ((payload (workflow-history-view-test--payload)))
    (workflow-history-view-test--panel payload
      (should (eq 'empty (plist-get org-workflow-history-panel--model :state)))
      (should (string-match-p "暂无历史数据" (buffer-string)))
      (should-not (string-match-p "查看日期：" (buffer-string)))))
  (unwind-protect
      (cl-letf (((symbol-function 'display-buffer) #'ignore)
                ((symbol-function 'org-workflow-history-read) (lambda (&rest _) (error "读取出错"))))
        (with-current-buffer (org-workflow-history-panel)
          (should (eq 'error (plist-get org-workflow-history-panel--model :state)))
          (should (string-match-p "无法读取历史：读取出错。使用“刷新历史”重试。" (buffer-string)))
          (should (string-match-p "刷新历史" (buffer-string)))
          (should (string-match-p "关闭面板" (buffer-string)))
          (should-not (string-match-p "暂无历史数据\|历史摘要\|查看日期：" (buffer-string)))
          (cl-letf (((symbol-function 'org-workflow-history-read) (lambda (&rest _) (workflow-history-view-test--payload))))
            (org-workflow-history-panel-refresh))
          (should (eq 'empty (plist-get org-workflow-history-panel--model :state)))
          (should-not (plist-get org-workflow-history-panel--model :error))))
    (when (get-buffer "*Workflow History*") (kill-buffer "*Workflow History*"))))
(ert-deftest workflow-history-panel-refresh-stale-retains-loading-one-read-recovery ()
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (let ((before org-workflow-history-panel--model) (reads 0))
        (cl-letf (((symbol-function 'org-workflow-history-read)
                   (lambda (&rest _)
                     (cl-incf reads)
                     (should (eq 'loading (plist-get org-workflow-history-panel--model :state)))
                     (should (eq (plist-get before :payload) (plist-get org-workflow-history-panel--model :payload)))
                     (should (string-match-p "正在刷新历史…" (buffer-string)))
                     (org-workflow-history-panel-refresh)
                     (error "出错"))))
          (org-workflow-history-panel-refresh))
        (should (= 1 reads))
        (should (eq 'stale (plist-get org-workflow-history-panel--model :state)))
        (dolist (key '(:payload :summary :detail :selected-date :last-success))
          (should (eq (plist-get before key) (plist-get org-workflow-history-panel--model key))))
        (should (string-match-p "未更新：本次读取失败，保留上次成功读取的历史" (buffer-string)))
        (org-workflow-history-panel-refresh)
        (should (eq 'ready (plist-get org-workflow-history-panel--model :state)))
        (should-not (plist-get org-workflow-history-panel--model :error))
        (should-not (string-match-p "未更新：" (buffer-string)))))))
(ert-deftest workflow-history-panel-refresh-quit-restores-complete-model ()
  (dolist (state '(ready stale empty error))
    (let ((payload (if (memq state '(empty error)) (workflow-history-view-test--payload)
                     (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16")))))
      (cl-letf (((symbol-function 'org-workflow-history-panel--wide-p) (lambda () nil)))
        (workflow-history-view-test--panel payload
        (when (memq state '(stale error))
          (cl-letf (((symbol-function 'org-workflow-history-read)
                     (lambda (&rest _) (error "旧读取错误"))))
            (when (eq state 'error) (setq org-workflow-history-panel--model nil))
            (org-workflow-history-panel-refresh)))
        (should (eq state (plist-get org-workflow-history-panel--model :state)))
        (let ((before org-workflow-history-panel--model)
              (text (buffer-substring-no-properties (point-min) (point-max)))
              (reads 0) (caught nil))
          (workflow-history-test--no-writes
            (cl-letf (((symbol-function 'org-workflow-history-read)
                       (lambda (&rest _)
                         (cl-incf reads)
                         (should org-workflow-history-panel--reading)
                         (should (eq 'loading (plist-get org-workflow-history-panel--model :state)))
                         (org-workflow-history-panel-refresh)
                         (signal 'quit nil))))
              (condition-case nil (org-workflow-history-panel-refresh) (quit (setq caught t)))))
          (should caught)
          (should (= reads 1))
          (should-not org-workflow-history-panel--reading)
          (should (eq before org-workflow-history-panel--model))
          (should (equal text (buffer-substring-no-properties (point-min) (point-max))))
          (dolist (text '("正在刷新历史" "正在读取历史"))
            (should-not (string-match-p text (buffer-string))))))))))

(ert-deftest workflow-history-panel-refresh-quit-initial-retry ()
  (let ((reads 0) (caught nil))
    (unwind-protect
        (progn
          (workflow-history-test--no-writes
            (cl-letf (((symbol-function 'display-buffer) #'ignore)
                      ((symbol-function 'org-workflow-history-read)
                       (lambda (&rest _)
                         (cl-incf reads)
                         (should org-workflow-history-panel--reading)
                         (signal 'quit nil))))
              (condition-case nil (org-workflow-history-panel) (quit (setq caught t)))))
          (should caught)
          (should (= reads 1))
          (with-current-buffer "*Workflow History*"
            (should-not org-workflow-history-panel--reading)
            (should (eq 'error (plist-get org-workflow-history-panel--model :state)))
            (should (string-match-p "读取已取消" (buffer-string)))
            (should (string-match-p "刷新历史" (buffer-string)))
            (should-not (string-match-p "正在读取历史" (buffer-string)))
            (should-not (string-match-p "历史摘要" (buffer-string)))
            (workflow-history-test--no-writes
              (cl-letf (((symbol-function 'org-workflow-history-read)
                         (lambda (&rest _) (cl-incf reads) (workflow-history-view-test--payload))))
                (org-workflow-history-panel-refresh)))
            (should (= reads 2))
            (should (eq 'empty (plist-get org-workflow-history-panel--model :state)))
            (should-not (plist-get org-workflow-history-panel--model :error))))
      (when (get-buffer "*Workflow History*") (kill-buffer "*Workflow History*")))))

(ert-deftest workflow-history-panel-refresh-bounded-field-path ()
  (let* ((day (workflow-history-view-test--day "2026-09-16"))
         (payload (workflow-history-view-test--payload day)))
    (setf (plist-get (aref (plist-get day :minimumTasks) 0) :task) "秘密标题"
          (plist-get day :habitCompleted) "invalid")
    (workflow-history-view-test--panel payload
      (should (eq 'error (plist-get org-workflow-history-panel--model :state)))
      (should (string-match-p (regexp-quote "历史数据不合法：days[0].habitCompleted") (buffer-string)))
      (should-not (string-match-p "秘密标题" (buffer-string))))))
(ert-deftest workflow-history-panel-refresh-reopen-one-read-and-external-update ()
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (let ((reads 0) (updates nil) (original (symbol-function 'vui-update)))
        (cl-letf (((symbol-function 'org-workflow-history-read) (lambda (&rest _) (cl-incf reads) payload))
                  ((symbol-function 'vui-update)
                   (lambda (instance props)
                     (should (eq instance vui--root-instance))
                     (should (equal '(:model) (cl-loop for (k _v) on props by #'cddr collect k)))
                     (push (plist-get props :model) updates)
                     (funcall original instance props))))
          (org-workflow-history-panel)
          (should (= 1 reads))
          (should (= 1 (cl-count 'ready updates :key (lambda (m) (plist-get m :state)))))
          (setq reads 0 updates nil)
          (org-workflow-history-panel-refresh)
          (should (= 1 reads))
          (should (= 1 (cl-count 'ready updates :key (lambda (m) (plist-get m :state))))))))))

(ert-deftest workflow-history-panel-refresh-initial-loading-and-invalid-stale ()
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (unwind-protect
        (cl-letf (((symbol-function 'display-buffer) #'ignore)
                  ((symbol-function 'org-workflow-history-read)
                   (lambda (&rest _)
                     (should (eq 'loading (plist-get org-workflow-history-panel--model :state)))
                     (should (string-match-p "正在读取历史…" (buffer-string)))
                     (should-not (string-match-p "历史摘要\|日详情" (buffer-string))) payload)))
          (with-current-buffer (org-workflow-history-panel)
            (let ((before org-workflow-history-panel--model))
              (cl-letf (((symbol-function 'org-workflow-history-read) (lambda (&rest _) '(:schema "bad"))))
                (org-workflow-history-panel-refresh))
              (should (eq 'stale (plist-get org-workflow-history-panel--model :state)))
              (dolist (key '(:payload :summary :detail :selected-date :last-success))
                (should (eq (plist-get before key) (plist-get org-workflow-history-panel--model key))))
              (should (string-match-p "未更新：" (buffer-string)))
              (should (string-match-p "历史数据不合法：" (buffer-string))))))
      (when (get-buffer "*Workflow History*") (kill-buffer "*Workflow History*")))))
(ert-deftest workflow-history-panel-refresh-width-layout-and-error-privacy ()
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (cl-letf (((symbol-function 'get-buffer-window)
                 (lambda (buffer &rest _) (should (eq buffer (current-buffer))) (selected-window)))
                ((symbol-function 'window-body-width) (lambda (&rest _) 60)))
        (org-workflow-history-panel--publish org-workflow-history-panel--model))
      (should-not (string-match-p "\\[刷新历史\\].*\\[关闭面板\\]" (buffer-string)))
      (cl-letf (((symbol-function 'get-buffer-window)
                 (lambda (buffer &rest _) (should (eq buffer (current-buffer))) (selected-window)))
                ((symbol-function 'window-body-width) (lambda (&rest _) 90)))
        (org-workflow-history-panel--publish org-workflow-history-panel--model))
      (should (string-match-p "\\[刷新历史\\].*\\[关闭面板\\]" (buffer-string)))
      (let ((text (org-workflow-history-panel--error-text (list 'error (concat "line1\n" (make-string 500 ?长))))))
        (should (equal (concat "line1\n" (make-string 500 ?长)) text))))))

(ert-deftest workflow-history-panel-ui-long-error-complete-multiline ()
  (let* ((plain (concat "首行 " (make-string 240 ?长) "\n第二行：完整安全原因 VISIBLE-END"))
         (reason (workflow-history-test--active-text plain))
         (payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (should (equal-including-properties plain (org-workflow-history-panel--error-text (list 'error reason))))
    (dolist (prior '(nil t))
      (workflow-history-view-test--panel payload
        (unless prior (setq org-workflow-history-panel--model nil))
        (cl-letf (((symbol-function 'org-workflow-history-read)
                   (lambda (&rest _) (signal 'error (list reason)))))
          (workflow-history-test--no-writes (org-workflow-history-panel-refresh)))
        (should (eq (if prior 'stale 'error) (plist-get org-workflow-history-panel--model :state)))
        (should (equal-including-properties plain (plist-get org-workflow-history-panel--model :error)))
        (should (string-search plain (buffer-substring-no-properties (point-min) (point-max))))
        (workflow-history-test--inert-buffer-text "VISIBLE-END")))))

(ert-deftest workflow-history-panel-ui-close-body-face ()
  (workflow-history-view-test--panel
      (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))
    (dolist (control '(("[关闭面板]" . default) ("[刷新历史]" . org-workflow-history-panel-action)
                       ("[2026-09-16 · 已达标]" . link)))
      (goto-char (point-min))
      (search-forward (car control))
      (let ((button (button-at (match-beginning 0))))
        (should button)
        (should (eq (cdr control) (button-get button 'face)))
        (should (button-get button 'action))
        (should (eq 'highlight (button-get button 'mouse-face)))))))

(ert-deftest workflow-history-panel-ui-status-normal-weight ()
  (dolist (spec '((org-workflow-history-panel-warning warning stale)
                  (org-workflow-history-panel-error error error)))
    (pcase-let ((`(,face ,inherit ,state) spec))
      (should (facep face))
      (should (eq inherit (face-attribute face :inherit nil)))
      (should (eq 'normal (face-attribute face :weight nil t)))
      (should (= 1.0 (face-attribute face :height nil)))
      (workflow-history-view-test--panel
          (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))
        (when (eq state 'error) (setq org-workflow-history-panel--model nil))
        (cl-letf (((symbol-function 'org-workflow-history-read) (lambda (&rest _) (error "状态样式验证"))))
          (workflow-history-test--no-writes (org-workflow-history-panel-refresh)))
        (goto-char (point-min))
        (search-forward "状态样式验证")
        (should (eq face (get-text-property (match-beginning 0) 'face)))))))

(ert-deftest workflow-history-panel-ui-list-continuation-prefix-owned ()
  (let* ((day (workflow-history-view-test--day "2026-09-16"))
         (leave (aref (workflow-history-view-test--leave "2026-09-16") 0))
         (texts (mapcar (lambda (label)
                          (propertize (concat label (make-string 80 ?长) "末尾完整")
                                      'wrap-prefix "UNTRUSTED PREFIX"
                                      'help-echo #'workflow-history-test--data-callback
                                      'keymap '(keymap (120 . workflow-history-test--data-callback))
                                      'display "HIDDEN DATA"))
                        '("承诺长标题" "可选长标题" "习惯长标题" "请假长理由" "关联长标题"))))
    (setf (plist-get (aref (plist-get day :minimumTasks) 0) :task) (nth 0 texts)
          (plist-get (aref (plist-get day :optionalTasks) 0) :task) (nth 1 texts)
          (plist-get day :habitTasks) (vector (list :task (nth 2 texts) :outcome "done" :focusMinutes 0))
          (plist-get leave :reason) (nth 3 texts)
          (plist-get (aref (plist-get leave :tasks) 0) :task) (nth 4 texts)
          (plist-get day :leaveRecords) (vector leave))
    (workflow-history-view-test--panel (workflow-history-view-test--payload day)
      (dolist (text texts)
        (workflow-history-test--inert-buffer-text text)
        (let ((from (- (point) (length text))))
          (should (equal (substring-no-properties text) (buffer-substring-no-properties from (point))))
          (cl-loop for pos from from below (point) do
                   (should (equal "  " (get-text-property pos 'wrap-prefix)))
                   (should (= 2 (string-width (get-text-property pos 'wrap-prefix))))
                   (should-not (get-text-property pos :wrap-prefix)))))
      (dolist (label '("任务状态：" "承诺履行：" "请假 · "))
        (goto-char (point-min))
        (search-forward label)
        (should (equal "  " (get-text-property (match-beginning 0) 'wrap-prefix)))))))

(defun workflow-history-test--bytes (file)
  (with-temp-buffer
    (set-buffer-multibyte nil) (insert-file-contents-literally file) (buffer-string)))

(defun workflow-history-test--buffer-facts (buffer)
  (with-current-buffer buffer
    (list (save-restriction (widen) (buffer-substring-no-properties (point-min) (point-max)))
          (buffer-modified-p) (point) (point-min) (point-max))))

(defun workflow-history-test--runtime-facts ()
  (mapcar (lambda (symbol) (cons symbol (and (boundp symbol) (copy-tree (symbol-value symbol)))))
          '(org-clock-marker org-clock-hd-marker org-clock-start-time org-clock-current-task
            org-workflow-history-timer org-workflow-history--refresh-timer
            org-workflow-journal-seal-timer org-workflow-web-export--timer
            timer-list timer-idle-list org-clock-out-hook org-clock-in-hook
            org-workflow-journal-finalized-hook org-workflow-habits-saved-hook
            after-save-hook clone-indirect-buffer-hook org-workflow-store-enabled org-workflow-store--path
            org-workflow-store--connection)))

(defun workflow-history-test--presentation-hook-p (hook function)
  "Only the two lifecycle-managed chart observers are permitted globally."
  (and (memq hook '(enable-theme-functions disable-theme-functions))
       (eq function #'org-workflow-history-panel--theme-changed)))
(defmacro workflow-history-test--no-writes (&rest body)
  (declare (indent 0) (debug t))
  `(let ((native-comp-enable-subr-trampolines nil))
     (let ((original-add-hook (symbol-function 'add-hook))
           (original-remove-hook (symbol-function 'remove-hook)))
     (cl-letf (((symbol-function 'add-hook)
                (lambda (hook function &optional depth local)
                  (let ((before (and (boundp hook) (copy-tree (default-value hook)))))
                    (unless (or local (member function before) (workflow-history-test--presentation-hook-p hook function))
                      (ert-fail (format "Forbidden global hook addition: %S" hook)))
                    (prog1 (funcall original-add-hook hook function depth local)
                      (unless (or local (workflow-history-test--presentation-hook-p hook function))
                        (should (equal before (default-value hook))))))))
              ((symbol-function 'remove-hook)
                (lambda (hook function &optional local)
                  (unless (or local (workflow-history-test--presentation-hook-p hook function))
                    (ert-fail "Forbidden global hook removal"))
                  (funcall original-remove-hook hook function local)))
              ,@(mapcar
              (lambda (symbol)
                `((symbol-function ',symbol)
                  (lambda (&rest _) (ert-fail ,(format "Forbidden read-side call: %s" symbol)))))
              '(sqlite-execute sqlite-open sqlite-close make-directory
                org-workflow-history-setup org-workflow-store-recover
                org-workflow-migrate org-workflow-migrate-setup
                org-workflow-history-catch-up org-workflow-history-finalize
                org-workflow-history-recompute org-workflow-history--compute
                org-workflow-history-progress org-workflow-history-streak
                org-workflow-store--sources org-workflow-history--habit-records
                org-workflow-history--tasks org-workflow-history--responsibilities
                org-workflow-journal-direct-clock-minutes org-workflow--direct-clock-records
                org-workflow-web-export-history org-workflow-web-export--write-atomically
                org-entry-put org-entry-delete org-todo org-schedule org-deadline
                org-clock-in org-clock-out org-clock-cancel save-buffer basic-save-buffer
                write-region run-at-time run-with-idle-timer cancel-timer)))
       ,@body))))

(defvar workflow-history-test--data-callback-count 0)
(defun workflow-history-test--data-callback (&rest _)
  (interactive)
  (cl-incf workflow-history-test--data-callback-count))
(defun workflow-history-test--active-text (text)
  "Make serializable data properties, including an unfamiliar property."
  (propertize text 'keymap '(keymap (120 . workflow-history-test--data-callback))
              'help-echo #'workflow-history-test--data-callback
              'display "HIDDEN DATA" 'face 'error 'invisible t
              'workflow-history-data-property 'must-not-render))
(defun workflow-history-test--inert-buffer-text (text)
  "Assert ordinary TEXT is visible and no data properties reached its range."
  (goto-char (point-min))
  (search-forward (substring-no-properties text))
  (cl-loop for pos from (- (point) (length text)) below (point) do
           (dolist (property '(help-echo display invisible workflow-history-data-property))
             (should-not (get-text-property pos property)))
           (should-not (eq #'workflow-history-test--data-callback
                           (key-binding (kbd "x") nil nil pos)))
           (should-not (eq 'error (get-text-property pos 'face)))))

(ert-deftest workflow-history-panel-persisted-text-properties-inert ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (let* ((day (workflow-history-view-test--day "2026-09-15"))
           (leave (aref (workflow-history-view-test--leave "2026-09-15") 0))
           (title (workflow-history-test--active-text "数据库标题 DATA CALLBACK"))
           (reason (workflow-history-test--active-text "数据库请假理由"))
           (linked (workflow-history-test--active-text "数据库关联任务"))
           (workflow-history-test--data-callback-count 0))
      (setf (plist-get (aref (plist-get day :minimumTasks) 0) :task) title
            (plist-get (aref (plist-get day :optionalTasks) 0) :task)
            (workflow-history-test--active-text "数据库可选任务")
            (plist-get day :habitTasks)
            (vector (list :task (workflow-history-test--active-text "数据库习惯任务")
                          :outcome "done" :focusMinutes 0))
            (plist-get day :finalizedAt) (workflow-history-test--active-text (plist-get day :finalizedAt))
            (plist-get day :commitment) (workflow-history-test--active-text "met")
            (plist-get day :date) (workflow-history-test--active-text "2026-09-15")
            (plist-get leave :reason) reason
            (plist-get (aref (plist-get leave :tasks) 0) :task) linked)
      (org-workflow-store-put-day "2026-09-15" day)
      (org-workflow-store-put-leave leave)
      (let ((changes (sqlite-select org-workflow-store--connection "SELECT total_changes()")))
        (workflow-history-test--no-writes
          (cl-letf (((symbol-function 'display-buffer) #'ignore))
            (with-current-buffer (org-workflow-history-panel workflow-history-test--now)
              (org-workflow-history-panel-select-date "2026-09-15")
              (let* ((payload (plist-get org-workflow-history-panel--model :payload))
                     (decoded (aref (plist-get payload :days) 0))
                     (decoded-title (plist-get (aref (plist-get decoded :minimumTasks) 0) :task)))
                (should (eq payload (org-workflow-history-view-validate payload)))
                (should (eq decoded (plist-get org-workflow-history-panel--model :detail)))
                (should (equal-including-properties title decoded-title))
                (dolist (text (list title reason linked "数据库可选任务" "数据库习惯任务"
                                    (plist-get day :finalizedAt) "met"))
                  (workflow-history-test--inert-buffer-text text))
                (dolist (option (org-workflow-history-view-date-options payload))
                  (should (equal-including-properties (car option) (substring-no-properties (car option))))
                  (should (equal-including-properties (cdr option) (substring-no-properties (cdr option)))))
                (cl-letf (((symbol-function 'completing-read)
                           (lambda (_prompt candidates &rest _)
                             (dolist (candidate candidates)
                               (should (equal-including-properties candidate (substring-no-properties candidate))))
                             (car candidates))))
                  (org-workflow-history-panel-select-date))
                (should (= 0 workflow-history-test--data-callback-count))))))
        (should (equal changes (sqlite-select org-workflow-store--connection "SELECT total_changes()")))))))

(ert-deftest workflow-history-panel-metadata-and-error-properties-inert ()
  (let* ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16")))
         (workflow-history-test--data-callback-count 0))
    (dolist (field '(:timezone :generatedAt))
      (setf (plist-get payload field) (workflow-history-test--active-text (plist-get payload field))))
    (dolist (field '(:trackingStarted :eligibleThrough))
      (setf (plist-get (plist-get payload :coverage) field)
            (workflow-history-test--active-text (plist-get (plist-get payload :coverage) field))))
    (workflow-history-view-test--panel payload
      (dolist (text (list "2026-09-16"))
        (workflow-history-test--inert-buffer-text text))
      (cl-letf (((symbol-function 'org-workflow-history-read)
                 (lambda (&rest _) (signal 'error (list (workflow-history-test--active-text "带属性的读取错误"))))))
        (workflow-history-test--no-writes (org-workflow-history-panel-refresh)))
      (should (equal-including-properties
               (plist-get org-workflow-history-panel--model :error)
               (substring-no-properties (plist-get org-workflow-history-panel--model :error))))
      (workflow-history-test--inert-buffer-text "带属性的读取错误")
      (should (= 0 workflow-history-test--data-callback-count)))))

(defun workflow-history-test--bad-day-records ()
  "Persisted root and identity failures that synthesized missing must not hide."
  (list nil :false :null "PRIVATE BAD ROOT" ["PRIVATE BAD ROOT"]
        '((:date . "2026-09-15")) '(:date "2026-09-15" :private)
        '(:date "2026-09-15" :date "2026-09-15" :recordState "finalized")
        '(:date "2026-09-15" :recordState "missing")
        (plist-put (copy-tree workflow-history-test--day t) :date "2026-09-16")))

(ert-deftest workflow-history-panel-persisted-bad-row-first-error ()
  (dolist (bad (workflow-history-test--bad-day-records))
    (workflow-history-test--store
      (org-workflow-store--db)
      (org-workflow-store-set-meta "anchor" "2026-09-15")
      (org-workflow-store-put-day "2026-09-15" bad)
      (let ((rows (sqlite-select org-workflow-store--connection "SELECT * FROM days"))
            (bytes (workflow-history-test--bytes org-workflow-store-file))
            (changes (sqlite-select org-workflow-store--connection "SELECT total_changes()")))
        (workflow-history-test--no-writes
          (cl-letf (((symbol-function 'display-buffer) #'ignore))
            (with-current-buffer (org-workflow-history-panel workflow-history-test--now)
              (should (eq 'error (plist-get org-workflow-history-panel--model :state)))
              (should-not (plist-get org-workflow-history-panel--model :payload))
              (should (string-match-p (regexp-quote "days[2026-09-15]") (buffer-string)))
              (should-not (string-match-p "PRIVATE\|暂无历史数据\|历史摘要" (buffer-string))))))
        (should (equal rows (sqlite-select org-workflow-store--connection "SELECT * FROM days")))
        (should (equal bytes (workflow-history-test--bytes org-workflow-store-file)))
        (should (equal changes (sqlite-select org-workflow-store--connection "SELECT total_changes()")))))))

(ert-deftest workflow-history-panel-persisted-bad-row-stale ()
  (dolist (bad (workflow-history-test--bad-day-records))
    (workflow-history-test--store
      (org-workflow-store--db)
      (org-workflow-store-set-meta "anchor" "2026-09-15")
      (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
      (cl-letf (((symbol-function 'display-buffer) #'ignore))
        (with-current-buffer (org-workflow-history-panel workflow-history-test--now)
          (org-workflow-history-panel-select-date "2026-09-15")
          (let ((before org-workflow-history-panel--model))
            (org-workflow-store-put-day "2026-09-15" bad)
            (let ((rows (sqlite-select org-workflow-store--connection "SELECT * FROM days"))
                  (bytes (workflow-history-test--bytes org-workflow-store-file))
                  (changes (sqlite-select org-workflow-store--connection "SELECT total_changes()")))
              (workflow-history-test--no-writes (org-workflow-history-panel-refresh workflow-history-test--now))
              (should (eq 'stale (plist-get org-workflow-history-panel--model :state)))
              (dolist (field '(:payload :summary :detail :selected-date :last-success))
                (should (eq (plist-get before field) (plist-get org-workflow-history-panel--model field))))
              (should (string-match-p (regexp-quote "days[2026-09-15]") (buffer-string)))
              (should-not (string-match-p "PRIVATE" (buffer-string)))
              (should (equal rows (sqlite-select org-workflow-store--connection "SELECT * FROM days")))
              (should (equal bytes (workflow-history-test--bytes org-workflow-store-file)))
              (should (equal changes (sqlite-select org-workflow-store--connection "SELECT total_changes()"))))))))))

(ert-deftest workflow-history-read-stored-decode-error-private ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (sqlite-execute org-workflow-store--connection "INSERT INTO days VALUES(?,?)"
                    '("2026-09-15" "(PRIVATE DECODE TEXT . #)"))
    (workflow-history-test--no-writes
      (let ((err (should-error (org-workflow-history-read workflow-history-test--now))))
        (should (string-match-p (regexp-quote "days[2026-09-15].payload") (error-message-string err)))
        (should-not (string-match-p "PRIVATE" (error-message-string err)))))))

(ert-deftest workflow-history-read-current-parity ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
    (org-workflow-store-put-leave '(:id "leave" :date "2026-09-16" :reason "休息"))
    (let* ((expected (org-workflow-web-export--payload workflow-history-test--now))
           (db org-workflow-store--connection)
           (source (expand-file-name "source.org" directory)))
      (with-temp-file source (insert "* TODO Source\n:LOGBOOK:\nCLOCK: [2026-09-15 Tue 10:00]--[2026-09-15 Tue 10:25] => 0:25\n:END:\n"))
      (let ((source-buffer (find-file-noselect source)))
        (unwind-protect
            (with-current-buffer source-buffer
              (goto-char 3) (narrow-to-region 2 (1- (point-max)))
              (let ((facts (workflow-history-test--buffer-facts source-buffer))
                    (bytes (workflow-history-test--bytes source))
                    (db-bytes (workflow-history-test--bytes org-workflow-store-file))
                    (runtime (workflow-history-test--runtime-facts))
                    (tables (mapcar (lambda (table) (sqlite-select db (concat "SELECT * FROM " table)))
                                    '("meta" "days" "leave_records" "habit_days" "commitments" "events" "operations")))
                    (version (sqlite-select db "PRAGMA user_version"))
                    (changes (sqlite-select db "SELECT total_changes()"))
                    (decoded nil) (original-decode (symbol-function 'org-workflow-store--decode)))
                (workflow-history-test--no-writes
                  (cl-letf (((symbol-function 'org-workflow-store--decode)
                             (lambda (&rest args)
                               (setq decoded t)
                               (apply original-decode args))))
                    (let ((actual (org-workflow-history-read workflow-history-test--now)))
                      (should (equal expected actual))
                      (should (equal "missing" (plist-get (aref (plist-get actual :days) 1) :recordState)))
                      (should (equal "休息" (plist-get (aref (plist-get (aref (plist-get actual :days) 1) :leaveRecords) 0) :reason)))))
                  (should decoded)
                  (should-error (org-workflow-store--decode "#.(error \"executed\")")
                                :type 'invalid-read-syntax)
                  (should (equal runtime (workflow-history-test--runtime-facts)))
                  (should (equal version (sqlite-select db "PRAGMA user_version")))
                  (should (equal changes (sqlite-select db "SELECT total_changes()")))
                  (should (equal tables (mapcar (lambda (table) (sqlite-select db (concat "SELECT * FROM " table)))
                                               '("meta" "days" "leave_records" "habit_days" "commitments" "events" "operations"))))
                  (should (equal facts (workflow-history-test--buffer-facts source-buffer)))
                  (should (equal bytes (workflow-history-test--bytes source)))
                  (should (equal db-bytes (workflow-history-test--bytes org-workflow-store-file))))))
          (with-current-buffer source-buffer (set-buffer-modified-p nil))
          (kill-buffer source-buffer))))))

(ert-deftest workflow-history-read-legacy-parity ()
  (let ((org-workflow-store-enabled nil) (org-element-use-cache nil))
    (org-workflow-web-export-test-with-journal org-workflow-web-export-test--valid-journal
      (with-current-buffer buffer
        (goto-char 5) (narrow-to-region 2 (1- (point-max)))
        (let ((expected (org-workflow-web-export--payload workflow-history-test--now))
              (facts (workflow-history-test--buffer-facts buffer))
              (bytes (workflow-history-test--bytes journal-file))
              (runtime (workflow-history-test--runtime-facts)))
          (workflow-history-test--no-writes
            (should (equal expected (org-workflow-history-read workflow-history-test--now)))
            (should (equal facts (workflow-history-test--buffer-facts buffer)))
            (should (equal bytes (workflow-history-test--bytes journal-file)))
            (should (equal runtime (workflow-history-test--runtime-facts)))))))))

(ert-deftest workflow-history-read-only-missing-anchor ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
    (workflow-history-test--no-writes
      (should-error (org-workflow-history-read workflow-history-test--now) :type 'error :exclude-subtypes t))))

(ert-deftest workflow-history-read-only-initialized-empty ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (workflow-history-test--no-writes
      (let ((payload (org-workflow-history-read workflow-history-test--now)))
        (should (eq :null (plist-get payload :coverage)))
        (should (equal [] (plist-get payload :days)))))))

(ert-deftest workflow-history-read-only-missing-table ()
  (workflow-history-test--store
    (sqlite-execute (org-workflow-store--db) "DROP TABLE leave_records")
    (workflow-history-test--no-writes
      (should-error (org-workflow-history-read workflow-history-test--now) :type 'sqlite-error))))

(ert-deftest workflow-history-read-only-missing-leave-anchor ()
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-put-leave '(:id "leave" :date "2026-09-16" :reason "休息"))
    (workflow-history-test--no-writes
      (should-error (org-workflow-history-read workflow-history-test--now) :type 'error :exclude-subtypes t))))

(ert-deftest workflow-history-read-only-connection-states ()
  (dolist (state '(absent closed mismatch))
    (workflow-history-test--store
      (unless (eq state 'absent) (org-workflow-store--db))
      (when (eq state 'closed) (sqlite-close org-workflow-store--connection))
      (setq org-workflow-store-file (expand-file-name "new/facts.sqlite" directory))
      (when (eq state 'closed) (setq org-workflow-store--path org-workflow-store-file))
      (workflow-history-test--no-writes
        (should-error (org-workflow-history-read workflow-history-test--now) :type 'error :exclude-subtypes t)
        (should-not (file-exists-p (file-name-directory org-workflow-store-file)))))))

(ert-deftest workflow-history-read-only-advice-states ()
  (dolist (pair workflow-history-test--advice)
    (workflow-history-test--store
      (org-workflow-store--db)
      (advice-remove (car pair) (cdr pair))
      (unwind-protect
          (workflow-history-test--no-writes
            (should-error (org-workflow-history-read workflow-history-test--now) :type 'error :exclude-subtypes t))
        (advice-add (car pair) :around (cdr pair))))))


(ert-deftest workflow-history-command-tracer ()
  "Configured commands retain one buffer and never steal the caller window."
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
    (let ((reader (symbol-function 'org-workflow-history-read))
          (reads 0) (displayed nil) (caller (selected-window))
          (display-policy (copy-tree display-buffer-alist))
          (shared-map (copy-keymap vui-mode-map))
          (widget-map (copy-keymap widget-keymap))
          (global-map (copy-keymap (current-global-map))))
      (save-window-excursion
        (workflow-history-test--no-writes
          (cl-letf (((symbol-function 'org-workflow-history-read)
                     (lambda (&rest args) (cl-incf reads) (apply reader args)))
                    ((symbol-function 'display-buffer)
                     (lambda (buffer &rest _)
                       (should (eq caller (selected-window)))
                       (should (buffer-local-value 'vui--root-instance buffer))
                       (setq displayed buffer))))
            (let ((buffer (org-workflow-history-panel workflow-history-test--now)))
              (should (eq buffer displayed))
              (should (= 1 reads))
              (should (eq caller (selected-window)))
              (with-current-buffer buffer
                (dolist (command '(org-workflow-history-panel org-workflow-history-panel-refresh
                                   org-workflow-history-panel-select-date org-workflow-history-panel-close))
                  (should (commandp command)))
                (should (eq #'org-workflow-history-panel-refresh (lookup-key (current-local-map) (kbd "g"))))
                (should (eq #'org-workflow-history-panel-close (lookup-key (current-local-map) (kbd "q"))))
                (dolist (binding '(("TAB" . vui-forward) ("<backtab>" . vui-backward)
                                   ("RET" . vui-activate)))
                  (should (eq (cdr binding)
                              (lookup-key (current-local-map) (kbd (car binding))))))
                (goto-char (point-min))
                (should-error (insert "edit"))
                (should-not buffer-read-only)
                (org-workflow-history-panel-select-date "2026-09-16")
                (should (= 1 reads))
                (should (equal "missing" (plist-get (plist-get org-workflow-history-panel--model :detail) :recordState)))
                (org-workflow-history-panel--publish org-workflow-history-panel--model)
                (should (= 1 reads))
                (let ((instance vui--root-instance))
                  (org-workflow-history-panel-refresh workflow-history-test--now)
                  (should (eq instance vui--root-instance)))
                (should (= 2 reads))
                (set-window-buffer caller buffer)
                (call-interactively (lookup-key (current-local-map) (kbd "q"))))
              (should (= 2 reads))
              (should (buffer-live-p buffer))
              (should-not (buffer-local-value 'vui--root-instance buffer))
              (should (eq buffer (org-workflow-history-panel workflow-history-test--now)))
              (should (= 3 reads))
              (should (buffer-local-value 'vui--root-instance buffer)))))
        (should (equal display-policy display-buffer-alist))
        (should (equal shared-map vui-mode-map))
        (should (equal widget-map widget-keymap))
        (should (equal global-map (current-global-map)))))))

(ert-deftest workflow-history-command-evil-controls ()
  "The actual configured normal-state keys match the panel's visible hints."
  (require 'evil)
  (let ((normal-map (copy-keymap evil-normal-state-map))
        (vui-map (copy-keymap vui-mode-map)))
    (with-temp-buffer
      (let ((vui-mode-map (copy-keymap vui-mode-map)))
        (org-workflow-history-panel-mode))
      (evil-local-mode 1)
      (evil-normal-state)
      (dolist (binding '(("TAB" . vui-forward) ("<backtab>" . vui-backward)
                         ("RET" . vui-activate)
                         ("g" . org-workflow-history-panel-refresh)
                         ("q" . org-workflow-history-panel-close)))
        (should (eq (cdr binding) (key-binding (kbd (car binding)))))))
    (should (equal normal-map evil-normal-state-map))
    (should (equal vui-map vui-mode-map))))

(defun workflow-history-test--action-facts (db source buffer absent)
  "Exact business and global facts, excluding panel presentation."
  (list
   (mapcar (lambda (file) (list file (file-exists-p file)
                                (and (file-exists-p file) (workflow-history-test--bytes file))))
           (list org-workflow-store-file source absent
                 (concat org-workflow-store-file "-wal")
                 (concat org-workflow-store-file "-shm")))
   (sqlite-select db "PRAGMA user_version")
   (sqlite-select db "SELECT total_changes()")
   (mapcar (lambda (table) (sqlite-select db (concat "SELECT * FROM " table " ORDER BY rowid")))
           '("meta" "days" "leave_records" "habit_days" "commitments" "events" "operations"))
   (workflow-history-test--buffer-facts buffer)
   (workflow-history-test--runtime-facts)
   (selected-window) (copy-tree display-buffer-alist)
   (copy-keymap vui-mode-map) (copy-keymap widget-keymap)
   (copy-keymap (current-global-map))))

(ert-deftest workflow-history-read-only-panel-action-matrix ()
  "Each action retains real SELECT/decode and its own exact before/after snapshot."
  (workflow-history-test--store
    (org-workflow-store--db)
    (org-workflow-store-set-meta "anchor" "2026-09-15")
    (org-workflow-store-put-day "2026-09-15" workflow-history-test--day)
    (let* ((db org-workflow-store--connection)
           (source (expand-file-name "source.org" directory))
           (absent (expand-file-name "absent.org" directory))
           (reader (symbol-function 'org-workflow-history-read))
           (reads 0) (fail nil) (panel nil))
      (with-temp-file source (insert "* TODO Chinese source 中文\n:LOGBOOK:\nCLOCK: [2026-09-15 Tue 10:00]--[2026-09-15 Tue 10:25] => 0:25\n:END:\n"))
      (let ((source-buffer (find-file-noselect source)))
        (unwind-protect
            (progn
              (with-current-buffer source-buffer
                (goto-char 6) (narrow-to-region 2 (1- (point-max)))
                (set-buffer-modified-p t))
              (save-window-excursion
                (workflow-history-test--no-writes
                  (cl-letf (((symbol-function 'org-workflow-history-read)
                             (lambda (&rest _) (cl-incf reads)
                               (if fail (error "Synthetic read failure")
                                 (funcall reader workflow-history-test--now)))))
                    (cl-labels ((action (label count function)
                                  (ert-info ((format "Action: %s" label))
                                    (let ((before (workflow-history-test--action-facts db source source-buffer absent))
                                          (read-before reads))
                                      (funcall function)
                                      (should (= count (- reads read-before)))
                                      (should (equal before (workflow-history-test--action-facts db source source-buffer absent)))))))
                      (setq fail t)
                      (action 'first-error 1 (lambda () (setq panel (org-workflow-history-panel))))
                      (with-current-buffer panel
                        (should (eq 'error (plist-get org-workflow-history-panel--model :state))))
                      (setq fail nil)
                      (action 'first-recovery 1 (lambda () (with-current-buffer panel (org-workflow-history-panel-refresh))))
                      (action 'select-finalized 0 (lambda () (with-current-buffer panel (org-workflow-history-panel-select-date "2026-09-15"))))
                      (action 'select-missing 0 (lambda () (with-current-buffer panel (org-workflow-history-panel-select-date "2026-09-16"))))
                      (action 'cancel 0 (lambda () (with-current-buffer panel
                                                   (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil))))
                                                     (call-interactively #'org-workflow-history-panel-select-date)))))
                      (action 'render 0 (lambda () (with-current-buffer panel (org-workflow-history-panel--publish org-workflow-history-panel--model))))
                      (action 'refresh 1 (lambda () (with-current-buffer panel (org-workflow-history-panel-refresh))))
                      (setq fail t)
                      (action 'stale-failure 1 (lambda () (with-current-buffer panel (org-workflow-history-panel-refresh))))
                      (with-current-buffer panel (should (eq 'stale (plist-get org-workflow-history-panel--model :state))))
                      (setq fail nil)
                      (action 'g-recovery 1 (lambda () (with-current-buffer panel (call-interactively (lookup-key (current-local-map) (kbd "g"))))))
                      (set-window-buffer (selected-window) panel)
                      (action 'q-close 0 (lambda () (with-current-buffer panel (call-interactively (lookup-key (current-local-map) (kbd "q"))))))
                      (should-not (buffer-local-value 'vui--root-instance panel))
                      (action 'reopen 1 (lambda () (should (eq panel (org-workflow-history-panel)))))
                      (action 'kill 0 (lambda () (kill-buffer panel)))
                      (should-not (buffer-live-p panel))
                      (action 'open-after-kill 1 (lambda () (setq panel (org-workflow-history-panel)))))))))
          (with-current-buffer source-buffer (set-buffer-modified-p nil))
          (kill-buffer source-buffer))))))

(ert-deftest workflow-history-command-package-registration ()
  "History entry points are available without a personal init file."
  (should (featurep 'org-workflow))
  (should (commandp 'org-workflow-history-panel))
  (should (commandp 'org-workflow-history-tracking))
  (should (commandp 'org-workflow-history-workbench)))

(ert-deftest workflow-history-command-outside-panel ()
  "Public controllers cannot replace or unmount a different vui buffer."
  (with-temp-buffer
    (let ((vui-mode-map (copy-keymap vui-mode-map))) (vui-mode))
    (insert "unrelated")
    (let ((before (buffer-string)))
      (dolist (command '(org-workflow-history-panel-refresh
                         org-workflow-history-panel-select-date
                         org-workflow-history-panel-close))
        (should-error (call-interactively command) :type 'user-error)
        (should (equal before (buffer-string)))))))
