;;; org-workflow-guidance-test.el -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-agenda)
(unless (fboundp 'org-workflow-store-test)
  (load (expand-file-name "org-workflow-store-test.el" (file-name-directory load-file-name)) nil t))
(ert-deftest workflow-guidance-missing-read-does-not-create ()
  (let ((directory (make-temp-file "guidance-" t)))
    (unwind-protect
        (cl-letf (((symbol-function 'org-workflow--directory) (lambda () directory)))
          (should-not (org-workflow-guidance-week-goals "2027-01-03"))
          (should-not (org-workflow-guidance-opening "2027-01-04"))
          (should (equal '("." "..") (directory-files directory)))
          (should (equal "2027-01-04" (org-workflow-week-start "2027-01-04"))))
      (delete-directory directory t))))
(ert-deftest workflow-guidance-sunday-target-and-clear ()
  (let* ((directory (make-temp-file "guidance-" t))
         (file (expand-file-name "journal/weekly/2027-01-04.org" directory))
         (answer "先重读昨日的笔记"))
    (unwind-protect
        (cl-letf (((symbol-function 'org-workflow--directory) (lambda () directory))
                  ((symbol-function 'org-workflow-target--today-string) (lambda () "2027-01-03"))
                  ((symbol-function 'read-string) (lambda (&rest _) answer))
                  ((symbol-function 'org-workflow--request-gnome-refresh) #'ignore)
                  ((symbol-function 'org-workflow-week-ensure)
                   (lambda (date)
                     (should (equal date "2027-01-04"))
                     (unless (file-exists-p file)
                       (make-directory (file-name-directory file) t)
                       (with-temp-file file (insert "* 周目标\n保留目标\n* 随记\n* 收集箱\n* 周回顾\n"))) file)))
          (org-workflow-guidance-edit-tomorrow)
          (should (equal answer (org-workflow-guidance-opening "2027-01-04")))
          (should (equal "保留目标" (org-workflow-guidance-week-goals "2027-01-04")))
          (setq answer "")
          (org-workflow-guidance-edit-tomorrow)
          (should-not (org-workflow-guidance-opening "2027-01-04")))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-directory directory t))))
