;;; org-workflow-leave-test.el --- Activity explanations -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-leave)
(require 'org-workflow-panel)
(unless (fboundp 'org-workflow-store-test)
  (load (expand-file-name "org-workflow-store-test.el" (file-name-directory load-file-name)) nil t))

(defmacro org-workflow-leave-test (&rest body)
  `(org-workflow-store-test
    (let* ((journal (expand-file-name "week.org" directory))
           (org-workflow-journal-finalized-hook nil)
           (org-workflow-panel--key nil)
           (org-workflow-store--extra-source-files nil))
      (with-temp-file journal (insert "#+filetags: :area:\n* 随记\n原有正文\n\n* 收集箱\n"))
      (unwind-protect
          (cl-letf (((symbol-function 'org-workflow-week-ensure) (lambda (&optional _) journal))
                    ((symbol-function 'org-workflow-collection-inbox--scheduled-files) (lambda () nil))
                    ((symbol-function 'org-workflow--request-gnome-refresh) #'ignore)
                    ((symbol-function 'org-workflow-web-export-history) #'ignore))
            ,@body)
        (when-let* ((buffer (get-file-buffer journal)))
          (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))))))

(ert-deftest workflow-leave-records-period-snapshot-without-changing-tasks ()
  (org-workflow-leave-test
   (erase-buffer)
   (insert "#+filetags: :project:\n* Stage\n** TODO [#A] Morning\nSCHEDULED: <2026-09-16 Wed>\n** TODO [#B] Overdue\nSCHEDULED: <2026-09-15 Tue>\n** TODO [#B] Afternoon\nSCHEDULED: <2026-09-16 Wed>\n** TODO [#B] Future\nSCHEDULED: <2026-09-17 Thu>\n** DONE [#B] Completed\nSCHEDULED: <2026-09-16 Wed>\n** TODO [#C] Evening\nSCHEDULED: <2026-09-16 Wed>\n")
   (let* ((before (buffer-string))
          (record (org-workflow-record-leave '("afternoon") "  朋友聚会  "))
          (tasks (plist-get record :tasks)))
     (should (equal before (buffer-string)))
     (should (equal (mapcar (lambda (task) (plist-get task :task)) tasks) '("Overdue" "Afternoon")))
     (let ((json (json-parse-string (json-serialize record) :object-type 'plist :null-object :null)))
       (should (eq :null (plist-get (aref (plist-get json :tasks) 0) :id))))
     (should (equal (plist-get record :reason) "朋友聚会"))
     (should-not (org-workflow-store-due "2026-09-16"))
     (should (equal (vector record) (org-workflow-store-leaves "2026-09-16")))
     (with-current-buffer (find-file-noselect journal)
       (should (string-match-p "原有正文" (buffer-string)))
       (should (string-match-p "请假条 · 下午" (buffer-string)))
       (should (string-match-p "涉及的未完成任务" (buffer-string)))
       (should-not (buffer-modified-p)))
     (sqlite-close org-workflow-store--connection)
     (setq org-workflow-store--connection nil)
     (should (equal (vector record) (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-empty-periods-and-validation ()
  (org-workflow-leave-test
   (dolist (args (list '(nil "reason") '(("night") "reason") '(("morning") " ")
                      (list '("morning") (concat "a" (string 10) "* injected"))
                      (list '("morning") (concat "a" (string 13) "b"))))
     (should-error (apply #'org-workflow-record-leave args) :type 'user-error))
   (should (= 0 (length (org-workflow-store-leaves "2026-09-16"))))
   (let ((record (org-workflow-record-leave '("evening" "morning" "evening") "* 临时事务")))
     (should (equal ["morning" "evening"] (plist-get record :slots)))
     (should (equal [] (plist-get record :tasks)))
     (with-current-buffer (find-file-noselect journal)
       (should (string-match-p ",\\* 临时事务" (buffer-string)))))
   (org-workflow-record-leave '("afternoon") "第二次活动")
   (should (= 2 (length (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-accepts-ordinary-letters-and-literal-escapes ()
  (org-workflow-leave-test
   (dolist (reason (list "aa" "dinner" (concat "折腾 org-workflow-core " (string 92) "n")))
     (let ((record (org-workflow-record-leave '("evening") reason)))
       (should (equal reason (plist-get record :reason)))))
   (should (= 3 (length (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-trims-boundary-newlines-before-validation ()
  (org-workflow-leave-test
   (dolist (reason (list (concat "折腾 org-workflow-core " (string 10))
                        (concat (string 13 10) " 折腾 org-workflow-core " (string 13 10))))
     (let ((record (org-workflow-record-leave '("evening") reason)))
       (should (equal "折腾 org-workflow-core" (plist-get record :reason)))))
   (should (= 2 (length (org-workflow-store-leaves "2026-09-16"))))
   (seq-doseq (record (org-workflow-store-leaves "2026-09-16"))
     (should (equal "折腾 org-workflow-core" (plist-get record :reason))))
   (dolist (reason (list (string 32 10 13 9) (concat "第一行" (string 10) "第二行")))
     (should-error (org-workflow-record-leave '("evening") reason) :type 'user-error))
   (should (= 2 (length (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-database-failure-rolls-back-journal ()
  (org-workflow-leave-test
   (let* ((buffer (find-file-noselect journal)) (before (with-current-buffer buffer (buffer-string))))
     (cl-letf (((symbol-function 'org-workflow-store-put-leave)
                (lambda (record)
                  (sqlite-execute (org-workflow-store--db) "INSERT INTO leave_records VALUES(?,?,?)"
                                  (list (plist-get record :id) (plist-get record :date) "nil"))
                  (error "injected database failure"))))
       (should-error (org-workflow-record-leave '("morning") "cancelled")))
     (should (equal before (with-current-buffer buffer (buffer-string))))
     (should (= 0 (length (org-workflow-store-leaves "2026-09-16"))))
     (should (equal before (with-temp-buffer (insert-file-contents journal) (buffer-string)))))))

(ert-deftest workflow-leave-readonly-journal-does-not-write-fact ()
  (org-workflow-leave-test
   (with-current-buffer (find-file-noselect journal) (setq buffer-read-only t))
   (should-error (org-workflow-record-leave '("evening") "read only") :type 'user-error)
   (should (= 0 (length (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-failed-save-keeps-recoverable-record ()
  (org-workflow-leave-test
   (cl-letf (((symbol-function 'save-buffer) (lambda (&rest _) (error "disk unavailable"))))
     (should-error (org-workflow-record-leave '("morning") "activity")))
   (should (= 1 (length (org-workflow-store-leaves "2026-09-16"))))
   (should (sqlite-select (org-workflow-store--db) "SELECT id FROM operations WHERE state='applied'"))
   (with-current-buffer (find-file-noselect journal)
     (should (buffer-modified-p))
     (should (string-match-p "activity" (buffer-string))))))

(ert-deftest workflow-leave-history-retains-real-totals-and-recompute ()
  (org-workflow-leave-test
   (org-workflow-record-leave '("evening") "social")
   (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) nil))
             ((symbol-function 'org-workflow-history--habit-records) (lambda (_) nil))
             ((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-17")))
     (let ((record (org-workflow-history-finalize "2026-09-16")))
       (should (= 0 (plist-get record :focusTotalMinutes)))
       (should (equal "untouch" (plist-get record :commitment)))
       (should (equal [] (plist-get record :minimumTasks)))
       (should (= 1 (length (plist-get record :leaveRecords))))
       (should (equal (plist-get record :leaveRecords)
                      (plist-get (org-workflow-history-finalize "2026-09-16" t) :leaveRecords)))))))

(ert-deftest workflow-leave-export-attaches-to-missing-and-finalized-without-fabrication ()
  (org-workflow-leave-test
   (org-workflow-record-leave '("evening") "social")
   (dolist (state '("missing" "finalized"))
     (let* ((day (list :date "2026-09-16" :recordState state))
            (output (aref (org-workflow-history--export-leaves (lambda () (vector day))) 0)))
       (should (equal state (plist-get output :recordState)))
       (should-not (plist-member output :focusTotalMinutes))
       (should (= 1 (length (plist-get output :leaveRecords))))
       (should-not (plist-member day :leaveRecords))))))

(ert-deftest workflow-leave-panel-distinguishes-completion-leave-and-unknown ()
  (org-workflow-leave-test
   (org-workflow-record-leave '("evening") "social")
   (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) nil))
             ((symbol-function 'org-workflow-history--habit-records) (lambda (_) nil)))
     (should (equal "leave" (plist-get (aref (org-workflow-panel--week "2026-09-16") 2) :state)))
     (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) '((:focusMinutes 5 :outcome "focused")))))
       (let ((day (aref (org-workflow-panel--week "2026-09-16") 2)))
         (should (equal "complete" (plist-get day :state)))
         (should (= 1 (length (plist-get day :leaveRecords))))))
     (cl-letf (((symbol-function 'org-workflow-history--tasks) (lambda (_) (error "missing source"))))
       (let ((day (aref (org-workflow-panel--week "2026-09-16") 2)))
         (should (equal "unknown" (plist-get day :state)))
         (should (= 1 (length (plist-get day :leaveRecords)))))))))

(ert-deftest workflow-leave-does-not-fulfill-existing-commitments ()
  (org-workflow-leave-test
   (org-schedule nil "2026-09-16")
   (org-priority ?C)
   (let ((before (buffer-string))
         (progress (org-workflow-history-progress "2026-09-16"))
         (rows (org-workflow-store-due "2026-09-16")))
     (org-workflow-record-leave '("evening") "social")
     (should (equal before (buffer-string)))
     (should (equal progress (org-workflow-history-progress "2026-09-16")))
     (should (equal rows (org-workflow-store-due "2026-09-16")))
     (should (eq :false (plist-get progress :commitmentComplete))))))

(ert-deftest workflow-leave-cancelled-input-does-not-record ()
  (org-workflow-leave-test
   (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "晚上"))
             ((symbol-function 'read-string) (lambda (&rest _) (signal 'quit nil))))
     (should (eq 'cancelled
                 (condition-case nil (call-interactively #'org-workflow-record-leave)
                   (quit 'cancelled)))))
   (should (= 0 (length (org-workflow-store-leaves "2026-09-16"))))))

(ert-deftest workflow-leave-yesterday-check-uses-sealed-result-and-explanation ()
  (org-workflow-leave-test
   (let ((yesterday "2026-09-15"))
     (should-not (org-workflow-leave--required-date))
     (dolist (state '("met" "untouch" "unmet"))
       (org-workflow-store-put-day yesterday (list :date yesterday :commitment state
                                                  :minimumTasks [(:task "Old task" :outcome "pending")]))
       (should (equal (org-workflow-leave--required-date) (and (equal state "unmet") yesterday))))
     (org-workflow-record-leave '("evening") "Yesterday reason" yesterday)
     (should-not (org-workflow-leave--required-date))
     (should (= 0 (length (org-workflow-store-leaves "2026-09-16")))))))

(ert-deftest workflow-leave-backfill-keeps-historical-tasks-and-settlement ()
  (org-workflow-leave-test
   (let* ((day '(:date "2026-09-15" :commitment "unmet" :focusTotalMinutes 25
                       :minimumTasks [(:task "Yesterday title" :outcome "pending")
                                      (:task "Already finished" :outcome "done")]))
          (before (buffer-string)) destination-date)
     (org-workflow-store-put-day "2026-09-15" day)
     (cl-letf (((symbol-function 'org-workflow-week-ensure) (lambda (date) (setq destination-date date) journal)))
       (let* ((record (org-workflow-record-leave '("evening") "social" "2026-09-15"))
              (tasks (plist-get record :tasks)))
         (should (equal "2026-09-15" destination-date))
         (should (equal [(:id :null :task "Yesterday title" :slot :null)] tasks))
         (should (equal before (buffer-string)))
         (should (equal day (org-workflow-store-day "2026-09-15")))
         (with-current-buffer (find-file-noselect journal)
           (should (string-match-p "2026-09-15 请假条" (buffer-string)))
           (should (string-match-p "时段未记录 · Yesterday title" (buffer-string))))
         (should (= 1 (length (plist-get (org-workflow-history--with-leaves day) :leaveRecords)))))))))

(ert-deftest workflow-leave-yesterday-uses-events-when-no-settlement ()
  (org-workflow-leave-test
   (let ((db (org-workflow-store--db)))
     (sqlite-execute db "INSERT INTO commitments VALUES('old','task-id','2026-09-15T09:00:00+08:00','2026-09-15','Old','Old','done',0)")
     (sqlite-execute db "INSERT INTO events(id,at,kind,payload) VALUES('old','2026-09-16T09:00:00+08:00','done','nil')")
     (should (equal "2026-09-15" (org-workflow-leave--required-date)))
     (sqlite-execute db "INSERT INTO events(id,at,kind,payload) VALUES('old','2026-09-15T21:00:00+08:00','done','nil')")
     (should-not (org-workflow-leave--required-date)))))

(ert-deftest workflow-leave-required-prompt-retries-empty-and-remains-after-quit ()
  (org-workflow-leave-test
   (org-workflow-store-put-day "2026-09-15" '(:date "2026-09-15" :commitment "unmet" :minimumTasks []))
   (let ((org-workflow-leave--checked-day nil) (org-workflow-leave--prompting nil) (answers '("" " " "social")))
     (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "晚上"))
               ((symbol-function 'read-string) (lambda (&rest _) (pop answers))))
       (org-workflow-leave-check-yesterday)
       (should-not answers)
       (should (equal "2026-09-16" org-workflow-leave--checked-day)))
     (sqlite-execute (org-workflow-store--db) "DELETE FROM leave_records")
     (setq org-workflow-leave--checked-day nil)
     (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (signal 'quit nil)))
               ((symbol-function 'completing-read) (lambda (&rest _) "全天")))
       (should (eq 'cancelled (condition-case nil (org-workflow-leave-check-yesterday) (quit 'cancelled)))))
     (should-not org-workflow-leave--checked-day)
     (should (equal "2026-09-15" (org-workflow-leave--required-date))))))

(ert-deftest workflow-leave-catchup-crosses-week-and-year-without-future-records ()
  (org-workflow-leave-test
   (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () "2026-01-05")))
     (org-workflow-store-put-day "2026-01-04" '(:date "2026-01-04" :commitment "unmet" :minimumTasks []))
     (should (equal "2026-01-04" (org-workflow-leave--required-date)))
     (should (equal "2025-12-29" (org-workflow-week-start (org-workflow-leave--required-date))))
     (should-error (org-workflow-record-leave '("morning") "future" "2026-01-06") :type 'user-error))))

(ert-deftest workflow-leave-startup-defers-daemon-and-deduplicates-frame-checks ()
  (let ((noninteractive nil) (after-init-time t) (org-workflow-store-enabled t)
        (org-workflow-leave--startup-timer nil)
        (org-workflow-leave--checked-day nil) (org-workflow-leave--prompting nil)
        client-name client calls)
    (cl-letf (((symbol-function 'daemonp) (lambda () t))
              ((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-16"))
              ((symbol-function 'frame-parameter) (lambda (_ property) (pcase property ('name client-name) ('client client))))
              ((symbol-function 'run-with-idle-timer)
               (lambda (&rest args) (push args calls) (timer-create))))
      (org-workflow-leave--startup)
      (should-not calls)
      (setq client t client-name "capture")
      (org-workflow-leave--startup)
      (should-not calls)
      (setq client-name "Emacs")
      (org-workflow-leave--startup)
      (org-workflow-leave--startup)
      (should (= 1 (length calls)))
      (setq org-workflow-leave--startup-timer nil org-workflow-leave--checked-day "2026-09-16")
      (org-workflow-leave--startup)
      (should (= 1 (length calls)))
      (setq org-workflow-leave--checked-day "2026-09-15")
      (org-workflow-leave--startup)
      (should (= 2 (length calls))))))

(ert-deftest workflow-leave-startup-waits-for-existing-minibuffer ()
  (let (calls (org-workflow-leave--startup-timer nil))
    (cl-letf (((symbol-function 'active-minibuffer-window) (lambda () t))
              ((symbol-function 'run-with-idle-timer) (lambda (&rest _) (push 'deferred calls) (timer-create)))
              ((symbol-function 'org-workflow-leave-check-yesterday) (lambda () (push 'prompt calls))))
      (org-workflow-leave--startup-check (selected-frame))
      (should (equal '(deferred) calls)))))

(ert-deftest workflow-leave-prompt-crossing-midnight-does-not-skip-new-day ()
  (org-workflow-leave-test
   (org-workflow-store-put-day "2026-09-15" '(:date "2026-09-15" :commitment "unmet" :minimumTasks []))
   (let ((today "2026-09-16") (org-workflow-leave--checked-day nil))
     (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () today))
               ((symbol-function 'org-workflow-leave--read-input)
                (lambda (date &optional _)
                  (setq today "2026-09-17")
                  (list '("evening") "late explanation" date))))
       (org-workflow-leave-check-yesterday)
       (should (equal "2026-09-16" org-workflow-leave--checked-day))
       (should (= 1 (length (org-workflow-store-leaves "2026-09-15"))))))))
