;;; org-workflow-select-test.el --- Selection behavior -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-core)

(ert-deftest org-workflow-select-scope-and-refresh ()
  (let* ((file (make-temp-file "workflow-select" nil ".org"
                "#+filetags: :project:\n#+TODO: TODO READY | DONE HOLD\n* DIVE Work\n** TODO [#A] Scheduled\nSCHEDULED: <2026-09-14 Mon>\n** READY [#B] Other\n** DONE Finished\n** HOLD Paused\n*** TODO Hidden\n* Outside\n** TODO Excluded\n"))
         (org-agenda-files (list file))
         (org-workflow-target-stack nil)
         (org-workflow-target-selected-marker nil)
         (org-workflow-target-selected-date nil)
         (org-workflow-current-changed-hook nil)
         (org-workflow-stack-empty-hook nil))
    (unwind-protect
        (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-14"))
                  ((symbol-function 'org-workflow-clock--clock-active-p) (lambda () nil)))
          (should (equal (mapcar (lambda (pair) (org-workflow-target-entry-title (cdr pair)))
                                (org-workflow-target--selection-entries))
                         '("Scheduled" "Other")))
          (org-workflow-target-refresh t)
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt table &rest _)
                       (let* ((all (all-completions "" table))
                              (metadata (completion-metadata "" table nil)))
                         (should (eq (completion-metadata-get metadata 'display-sort-function) 'identity))
                         (should (string-match-p "栈外 DIVE"
                                   (funcall (completion-metadata-get metadata 'group-function)
                                            (cadr all) nil)))
                         (cadr all)))))
            (org-workflow-target-select))
          (org-workflow-target-refresh t)
          (should (equal "Other" (org-workflow-target-entry-title (car org-workflow-target-stack))))
          (should (= 2 (length org-workflow-target-stack)))
          (org-with-point-at (org-workflow-target-current-marker) (org-todo "DONE"))
          (should-not org-workflow-target-selected-marker)
          (should (equal "Scheduled" (org-workflow-target-entry-title (car org-workflow-target-stack)))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file))))

(ert-deftest org-workflow-refresh-retains-clock-and-expires-selection ()
  (let* ((file (make-temp-file "workflow-select" nil ".org"
                "#+filetags: :area:\n* DIVE Tasks\n** TODO First\nSCHEDULED: <2026-09-14 Mon>\n** TODO Second\nSCHEDULED: <2026-09-14 Mon>\n"))
         (org-agenda-files (list file))
         (org-workflow-target-stack nil)
         (org-workflow-target-selected-marker nil)
         (org-workflow-target-selected-date "2026-09-14")
         (org-workflow-current-changed-hook nil)
         (org-workflow-stack-empty-hook nil)
         (today "2026-09-14") stopped)
    (unwind-protect
        (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () today))
                  ((symbol-function 'org-workflow-clock--clock-active-p) (lambda () t))
                  ((symbol-function 'org-workflow-clock--clock-matches-p) (lambda (_) t))
                  ((symbol-function 'org-workflow-clock--clock-stop) (lambda () (setq stopped t))))
          (org-workflow-target-refresh t)
          (setq org-workflow-target-selected-marker
                (org-workflow-target-entry-marker (cadr org-workflow-target-stack))
                org-workflow-target-selected-date today)
          (org-workflow-target-refresh t)
          (should-not stopped)
          (should (= 2 (length org-workflow-target-stack)))
          (should (equal "Second" (org-workflow-target-entry-title (car org-workflow-target-stack))))
          (setq today "2026-09-15")
          (org-workflow-target-refresh t)
          (should-not org-workflow-target-selected-marker)
          (should (equal "First" (org-workflow-target-entry-title (car org-workflow-target-stack)))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file))))
