;;; org-workflow-store-test.el --- Fact and recovery contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-core)
(require 'org-workflow-history)
(defmacro org-workflow-store-test (&rest body)
  `(let* ((directory (make-temp-file "workflow-store-" t))
          (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
          (org-workflow-store--connection nil) (org-workflow-store--path nil)
          (org-workflow-store-enabled t)
          (org-workflow-executing-marker nil)
          (org-workflow-target-selected-marker nil)
          (org-workflow-status-provider-function nil)
          (org-workflow-current-changed-hook nil)
          (org-workflow-commitment-streak-provider-function nil)
          (file (expand-file-name "project.org" directory))
          (org-agenda-files (list file)))
     (unwind-protect
         (progn
           (with-temp-file file (insert "#+filetags: :project:\n* Stage\n** TODO Task\n"))
           (with-current-buffer (find-file-noselect file)
             (goto-char (point-min)) (search-forward "** TODO") (beginning-of-line)
             (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-16"))) ,@body)))
       (when (and org-workflow-store--connection (org-workflow-store--live-p org-workflow-store--connection))
         (sqlite-close org-workflow-store--connection))
       (when-let* ((buffer (get-file-buffer file)))
         (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))
       (delete-directory directory t))))

(ert-deftest workflow-store-schedule-freezes-previous-day-responsibility ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (let ((id (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))
     (should id)
     (cl-letf (((symbol-function 'org-workflow-target--today-string) (lambda () "2026-09-17")))
       (org-schedule nil "2026-09-18")
       (should (equal "deferred" (nth 6 (org-workflow-store-commitment id))))
       (should-not (equal id (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))
       (should (= 1 (plist-get (org-workflow-history-progress "2026-09-17") :minimumTotal)))
       (should (= 0 (plist-get (org-workflow-history-progress "2026-09-17") :minimumSatisfied)))))))
(ert-deftest workflow-store-cancels-drafts-without-erasing-history ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (let ((id (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))
     (org-schedule nil "2026-09-16")
     (should (equal "cancelled" (nth 6 (org-workflow-store-commitment id))))
     (should-not (org-entry-get nil "WORKFLOW_COMMITMENT_ID"))
     (should-not (org-workflow-store-due "2026-09-17")))))
(ert-deftest workflow-store-operation-rolls-back-source-and-facts ()
  (org-workflow-store-test
   (let ((before (buffer-string)))
     (should-error
      (org-workflow-store--operation
       (lambda () (org-workflow-store-create "2026-09-17") (error "injected failure"))))
     (should (equal before (buffer-string)))
     (should-not (org-workflow-store-due "2026-09-17")))))
(ert-deftest workflow-store-recovers-multiple-unsaved-operations ()
  (org-workflow-store-test
   (let ((before (buffer-string)))
     (org-schedule nil "2026-09-17")
     (org-schedule nil "2026-09-18")
     (let ((after (buffer-string)))
       (erase-buffer) (insert before)
       (org-workflow-store-recover)
       (should (equal after (buffer-string)))))))
(ert-deftest workflow-store-refinement-transfers-clock-and-responsibility ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (org-end-of-meta-data t)
   (insert ":LOGBOOK:\nCLOCK: [2026-09-16 Wed 10:00]--[2026-09-16 Wed 10:25] =>  0:25\n:END:\n")
   (org-back-to-heading t)
   (let ((source (point-marker)) (id (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))
     (org-workflow-target--step "Plan the work" source)
     (goto-char source)
     (should-not (org-entry-get nil "WORKFLOW_COMMITMENT_ID"))
     (should-not (org-workflow--direct-clock-records))
     (outline-next-heading)
     (should (equal id (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))
     (should (= 1 (length (org-workflow--direct-clock-records))))
     (should (equal "TODO" (org-get-todo-state)))
     (org-todo "DONE")
     (should (equal "adjusted-done" (nth 6 (org-workflow-store-commitment id)))))))

(ert-deftest workflow-history-midnight-clocks-are-split-without-loss ()
  (org-workflow-store-test
   (org-end-of-meta-data t)
   (insert ":LOGBOOK:\nCLOCK: [2026-09-14 Mon 23:40]--[2026-09-15 Tue 00:20] =>  0:40\n:END:\n")
   (should (= 20 (plist-get (org-workflow-history--compute "2026-09-14") :focusTotalMinutes)))
   (should (= 20 (plist-get (org-workflow-history--compute "2026-09-15") :focusTotalMinutes)))
   (let ((first (org-workflow-history-finalize "2026-09-15")))
     (should (equal first (org-workflow-history-finalize "2026-09-15"))))))
(ert-deftest workflow-store-recovery-refuses-divergent-file ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (goto-char (point-max)) (insert "Independent change\n")
   (let ((before (buffer-string)))
     (should-error (org-workflow-store-recover))
     (should (equal before (buffer-string))))))

(ert-deftest workflow-store-save-acknowledges-later-manual-edits ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (goto-char (point-max)) (insert "My later edit\n")
   (save-buffer)
   (should (equal '("saved")
                  (car (sqlite-select (org-workflow-store--db) "SELECT state FROM operations"))))
   (let ((saved (buffer-string)))
     (org-workflow-store-recover)
     (should (equal saved (buffer-string)))
     (should-not (buffer-modified-p)))))

(ert-deftest workflow-store-checkpoint-does-not-acknowledge-unsaved-edits ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-17")
   (goto-char (point-max)) (insert "Unsaved manual edit\n")
   (org-workflow-store-checkpoint file)
   (should (equal "applied"
                  (caar (sqlite-select (org-workflow-store--db) "SELECT state FROM operations"))))
   (should-error (org-workflow-store-recover))))

(ert-deftest workflow-store-checkpoints-files-independently ()
  (org-workflow-store-test
   (let* ((other (expand-file-name "other.org" directory))
          (org-agenda-files (list file other)))
     (unwind-protect
         (progn
           (with-temp-file other (insert "* Other\n"))
           (org-workflow-store--operation
            (lambda ()
              (goto-char (point-max)) (insert "Workflow edit\n")
              (with-current-buffer (find-file-noselect other)
                (goto-char (point-max)) (insert "Pending other edit\n"))))
           (goto-char (point-max)) (insert "Later manual edit\n")
           (save-buffer)
           (let ((images (org-workflow-store--decode
                          (caar (sqlite-select (org-workflow-store--db)
                                               "SELECT after_text FROM operations WHERE state='applied'")))))
             (should (equal (mapcar #'car images) (list other))))
           (with-current-buffer (get-file-buffer other) (revert-buffer t t))
           (org-workflow-store-recover)
           (should (string-suffix-p "Later manual edit\n" (buffer-string)))
           (with-current-buffer (get-file-buffer other)
             (should (string-suffix-p "Pending other edit\n" (buffer-string)))
             (save-buffer))
           (should-not (sqlite-select (org-workflow-store--db)
                                     "SELECT id FROM operations WHERE state='applied'")))
       (when-let* ((buffer (get-file-buffer other)))
         (with-current-buffer buffer (set-buffer-modified-p nil))
         (kill-buffer buffer))))))

(ert-deftest workflow-store-checkpoints-saves-inside-operation-after-commit ()
  (org-workflow-store-test
   (org-workflow-store--operation
    (lambda () (goto-char (point-max)) (insert "Saved inside\n") (save-buffer)))
   (should (equal "saved"
                  (caar (sqlite-select (org-workflow-store--db) "SELECT state FROM operations"))))))
(ert-deftest workflow-execution-stays-current-when-plans-change ()
  (org-workflow-store-test
   (org-schedule nil "2026-09-16")
   (setq org-workflow-executing-marker (point-marker))
   (let ((marker (point-marker)))
     (goto-char (point-max)) (insert "** TODO Other\nSCHEDULED: <2026-09-16 Wed>\n")
     (cl-letf (((symbol-function 'org-workflow-target--sorted-entries)
                (lambda () nil)))
       (org-workflow-target-refresh t)
       (should (org-workflow-target--same-marker-p marker (org-workflow-target-current-marker)))))))

(require 'org-workflow-migrate)
(ert-deftest workflow-migration-is-idempotent-and-backs-up-source ()
  (org-workflow-store-test
   (let ((user-emacs-directory (file-name-as-directory directory))
         (org-workflow-store-enabled nil))
     (org-toggle-tag "promise" 'on)
     (org-add-planning-info 'scheduled "2026-09-17")
     (save-buffer)
     (cl-letf (((symbol-function 'org-workflow-migrate--legacy-days) (lambda () nil))
               ((symbol-function 'org-workflow-web-export--candidate-records) (lambda () nil))
               ((symbol-function 'org-workflow-collection-inbox--review-files) (lambda () nil)))
       (org-workflow-migrate)
       (should (org-entry-get nil "WORKFLOW_COMMITMENT_ID"))
       (should-not (nth 2 (org-workflow-store-commitment
                           (org-entry-get nil "WORKFLOW_COMMITMENT_ID"))))
       (should-not (org-entry-get nil "WORKFLOW_COMMITTED_AT"))
       (should-not (org-entry-get nil "WORKFLOW_COMMITTED_FOR"))
       (should-not (member "promise" (org-get-tags nil t)))
       (should (file-directory-p (org-workflow-store-meta "backup")))
       (org-workflow-migrate)
       (should (= 1 (length (org-workflow-store-due "2026-09-17"))))))))

(require 'org-workflow-weekly)
(ert-deftest workflow-week-document-is-idempotent-and-indexable ()
  (org-workflow-store-test
   (let ((vulpea-default-notes-directory directory)
         (vulpea-db-location (expand-file-name "vulpea.sqlite" directory))
         (vulpea-db--connection nil)
         (vulpea-db-sync-directories (list directory)))
     (let ((file (org-workflow-week-ensure "2027-01-01")))
       (should (string-suffix-p "journal/weekly/2026-12-28.org" file))
       (with-current-buffer (find-file-noselect file)
         (org-workflow-week-detect)
         (should (equal org-workflow-week "2026-12-28"))
         (goto-char (point-max)) (insert "My own review\n") (save-buffer))
       (should (equal file (org-workflow-week-ensure "2027-01-03")))
       (with-temp-buffer (insert-file-contents file)
         (should (string-match-p "My own review" (buffer-string)))
         (should (string-match-p ":ID:" (buffer-string))))
       (kill-buffer (get-file-buffer file))))))

(ert-deftest workflow-completing-execution-updates-desktop-task ()
  "Completing the timed task releases its selection and publishes its successor."
  (org-workflow-store-test
   (org-schedule nil "2026-09-16")
   (let ((first (point-marker))
         (org-workflow-target-stack nil)
         (org-log-done nil)
         (org-workflow-current-changed-hook nil)
         (signals 0))
     (goto-char (point-max))
     (insert "** TODO Successor\nSCHEDULED: <2026-09-16 Wed>\n")
     (goto-char first)
     (setq org-workflow-executing-marker (copy-marker first)
           org-workflow-target-selected-marker (copy-marker first))
     (add-hook 'org-workflow-current-changed-hook (lambda () (cl-incf signals)))
     (cl-letf (((symbol-function 'org-workflow-clock--clock-active-p) (lambda () nil))
               ((symbol-function 'org-workflow-clock--clock-matches-p) (lambda (_) nil)))
       (org-workflow-target-complete))
     (should-not org-workflow-executing-marker)
     (should-not org-workflow-target-selected-marker)
     (should (equal "Successor" (plist-get (org-workflow-status) :task)))
     (should (> signals 0)))))
