;;; org-workflow-agenda-journal-test.el --- Daily inbox capture tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-agenda)
(require 'org-capture)
(require 'vulpea-journal)
(require 'org-workflow-weekly)

(ert-deftest note-gtd-journal-captures-into-week-and-keeps-daily-date ()
  (let* ((directory (make-temp-file "weekly-inbox-" t))
         (org-capture-mode-hook nil) (org-capture-after-finalize-hook nil)
         (date (encode-time 0 0 20 8 9 2026)))
    (unwind-protect
        (cl-letf (((symbol-function 'current-time) (lambda () date))
                  ((symbol-function 'org-workflow-target--today-string) (lambda () (format-time-string "%F" date)))
                  ((symbol-function 'org-workflow-week-ensure)
                   (lambda (&optional _) (let ((file (expand-file-name
                                  (concat (org-workflow-week-start) ".org") directory)))
                     (unless (file-exists-p file)
                       (with-temp-file file (insert "#+title: Week\n* 周目标\nKeep me\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: "
                                                   (org-workflow-week-start) "\n:END:\n"))) file))))
          (org-capture nil "t") (insert "Task one") (org-capture-finalize)
          (setq date (encode-time 0 1 0 9 9 2026))
          (org-capture nil "t") (insert "Next day") (org-capture-finalize)
          (with-temp-buffer
            (insert-file-contents (expand-file-name "2026-09-07.org" directory))
            (should (string-match-p "Task one" (buffer-string)))
            (should (string-match-p "Next day" (buffer-string)))
            (should (string-match-p "CAPTURED_ON: 2026-09-08" (buffer-string)))
            (should (string-match-p "CAPTURED_ON: 2026-09-09" (buffer-string)))
            (should (string-match-p "Keep me" (buffer-string))))
          (setq date (encode-time 0 0 10 14 9 2026))
          (org-capture nil "t") (insert "Next week") (org-capture-finalize)
          (should (file-exists-p (expand-file-name "2026-09-14.org" directory))))
      (when (bound-and-true-p org-capture-mode) (org-capture-kill))
      (dolist (buffer (buffer-list))
        (when (and (buffer-file-name buffer) (string-prefix-p directory (buffer-file-name buffer)))
          (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest note-gtd-week-boundaries-cross-year ()
  (should (equal "2026-12-28" (org-workflow-week-start "2027-01-01")))
  (should (equal "2026-12-28" (org-workflow-week-start "2027-01-03")))
  (should (equal "2027-01-04" (org-workflow-week-start "2027-01-04"))))

(ert-deftest note-gtd-journal-template-install-preserves-current-target ()
  (let ((org-capture-templates '(("c" "Current" plain (function ignore) "Keep"))))
    (org-workflow-install-inbox-capture-templates)
    (org-workflow-install-inbox-capture-templates)
    (should (= 5 (length org-capture-templates)))
    (should (equal "Keep" (nth 4 (assoc "c" org-capture-templates))))))

(ert-deftest note-gtd-journal-classification-saves-non-agenda-source ()
  (let* ((directory (make-temp-file "journal-refile-" t))
         (journal (expand-file-name "day.org" directory))
         (org-workflow-inbox-file (expand-file-name "legacy.org" directory))
         (org-workflow-projects-file (expand-file-name "projects.org" directory))
         (org-agenda-files (list org-workflow-projects-file)))
    (unwind-protect
        (progn
          (with-temp-file journal
            (insert "* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-08\n:END:\n** TODO Later idea\nBody\n"))
          (with-temp-file org-workflow-projects-file (insert "* Someday\n"))
          (with-current-buffer (find-file-noselect journal)
            (goto-char (point-max))
            (org-workflow-inbox-classify-someday))
          (with-temp-buffer
            (insert-file-contents journal)
            (should-not (string-match-p "Later idea" (buffer-string))))
          (with-temp-buffer
            (insert-file-contents org-workflow-projects-file)
            (should (string-match-p "Later idea" (buffer-string)))))
      (dolist (file (list journal org-workflow-projects-file))
        (when-let* ((buffer (get-file-buffer file)))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest note-gtd-journal-review-groups-original-items-without-copying ()
  (let* ((file (make-temp-file "journal-history-" nil ".org"
                 "* Older\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-08-01\n:END:\n** SEED Old idea\n* Inbox\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-08\n:END:\n** TODO Work\n*** TODO Nested\n** DONE Finished but unfiled\n** SEED Thought\n* Workflow\n** TODO Not collection\n")))
    (unwind-protect
        (cl-letf (((symbol-function 'current-time) (lambda () (encode-time 0 0 20 8 9 2026))))
          (let ((entries (org-workflow-collection-inbox--pending (list file))))
            (should (equal '("TODO Work" "SEED Thought")
                           (mapcar #'cadr entries)))
            (should (cl-every (lambda (e) (markerp (nth 2 e))) entries)))
          (should (= 3 (length (org-workflow-collection-inbox--pending (list file) t))))
          (with-current-buffer (find-file-noselect file)
            (should-not (buffer-modified-p))))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-file file))))

(ert-deftest note-gtd-refile-saves-both-participants-but-not-unrelated-buffer ()
  (let* ((directory (make-temp-file "refile-save-" t))
         (source (expand-file-name "source.org" directory))
         (target (expand-file-name "target.org" directory))
         (unrelated (expand-file-name "unrelated.org" directory))
         (org-agenda-files (list unrelated)))
    (unwind-protect
        (progn
          (with-temp-file source (insert "* TODO Move this\n"))
          (with-temp-file target (insert "* Destination\n"))
          (with-temp-file unrelated (insert "Original\n"))
          (with-current-buffer (find-file-noselect unrelated)
            (goto-char (point-max)) (insert "Unrelated edit\n"))
          (with-current-buffer (find-file-noselect source)
            (goto-char (point-min))
            (org-refile nil nil (list "Destination" target nil 1)))
          (with-temp-buffer (insert-file-contents source)
                            (should-not (string-match-p "Move this" (buffer-string))))
          (with-temp-buffer (insert-file-contents target)
                            (should (string-match-p "Move this" (buffer-string))))
          (with-temp-buffer (insert-file-contents unrelated)
                            (should (equal "Original\n" (buffer-string)))))
      (dolist (file (list source target unrelated))
        (when-let* ((buffer (get-file-buffer file)))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest note-gtd-journal-review-refiles-original-and-refreshes ()
  (let* ((directory (make-temp-file "review-action-" t))
         (source (expand-file-name "journal.org" directory))
         (target (expand-file-name "notes.org" directory)))
    (unwind-protect
        (progn
          (with-temp-file source
            (insert "* Collection\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-08\n:END:\n** SEED Review me\nBody\n** TODO Next item\n"))
          (with-temp-file target (insert "* Notes\n"))
          (cl-letf (((symbol-function 'org-workflow-collection-inbox--review-files) (lambda () (list source)))
                    ((symbol-function 'org-refile-get-location)
                     (lambda (&rest _) (list "Notes" target nil 1))))
            (with-temp-buffer
              (org-workflow-collection-review-mode)
              (setq org-workflow-collection-review-all t)
              (org-workflow-collection-review-refresh)
              (search-forward "Review me")
              (beginning-of-line)
              (should (markerp (org-workflow-collection-review--marker)))
              (should-not (org-workflow-inbox--classify-todo-p))
              (org-workflow-inbox-classify-refile)
              (should (string-match-p "Next item" (thing-at-point 'line t)))
              (should (= 1 org-workflow-collection-review-count))
              (should-not (string-match-p "Review me" (buffer-string)))))
          (with-temp-buffer (insert-file-contents target)
                            (should (string-match-p "Review me" (buffer-string)))))
      (dolist (file (list source target))
        (when-let* ((buffer (get-file-buffer file)))
          (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest note-gtd-journal-classification-validates-source-and-cancel ()
  (with-temp-buffer
    (org-mode)
    (insert "* Collection\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-08\n:END:\n** TODO Item\nLink and body\n* Elsewhere\n")
    (goto-char (point-min))
    (should-error (org-workflow-inbox--classification-marker) :type 'user-error)
    (search-forward "TODO Item")
    (should (org-workflow-inbox--classify-todo-p))
    (let ((before (buffer-string)))
      (cl-letf (((symbol-function 'org-refile)
                 (lambda (&rest _) (interactive) (user-error "Cancelled"))))
        (should-error (org-workflow-inbox-classify-refile) :type 'user-error))
      (should (equal before (buffer-string))))
    (goto-char (point-max))
    (should-error (org-workflow-inbox--classification-marker) :type 'user-error)))

(ert-deftest note-gtd-journal-classification-project-restricts-destinations ()
  "Workflow files need not be indexed in Vulpea to receive collected items."
  (let* ((directory (make-temp-file "classification-project-" t))
         (project (expand-file-name "project.org" directory))
         (area (expand-file-name "area.org" directory))
         (other (expand-file-name "other.org" directory))
         (org-agenda-files (list project area other)))
    (unwind-protect
        (progn
          (with-temp-file project (insert "#+filetags: :project:\n* Project\n"))
          (with-temp-file area (insert "#+filetags: :area:\n* Area\n"))
          (with-temp-file other (insert "* Other\n"))
          (with-temp-buffer
            (org-mode)
            (insert "* Collection\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-08\n:END:\n** TODO Item\n")
            (goto-char (point-max))
            (cl-letf (((symbol-function 'vulpea-db-query-by-tags-every)
                       (lambda (&rest _) (ert-fail "Must not query Vulpea")))
                      ((symbol-function 'org-refile)
                       (lambda (&rest _)
                         (interactive)
                         (should (equal org-refile-targets
                                        `(((,project ,area) :maxlevel . 5))))
                         (should-not org-refile-use-cache))))
              (org-workflow-inbox-classify-project))))
      (dolist (file (list project area other))
        (when-let* ((buffer (get-file-buffer file)))
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer)))
      (delete-directory directory t))))
