;;; org-workflow-agenda-agenda-create-test.el --- Sprint direct creation -*- lexical-binding: t; -*-
(require 'ert)
(require 'evil)
(require 'org-workflow-agenda)
(require 'org-workflow-weekly)
(require 'org-workflow-evening)

(ert-deftest note-gtd-sprint-creates-task-from-empty-period ()
  (let* ((directory (make-temp-file "sprint-create-" t))
         (file (expand-file-name "2026-09-21.org" directory))
         (org-agenda-files (list file))
         (org-agenda-buffer-name "*Sprint create test*")
         (org-workflow-agenda-columns-enabled nil))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "#+filetags: :area:\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2026-09-21\n:END:\n"))
          (cl-letf (((symbol-function 'org-workflow-target--today-string)
                     (lambda () "2026-09-23"))
                    ((symbol-function 'org-workflow-week-ensure)
                     (lambda (&optional _) file))
                    ((symbol-function 'read-string)
                     (lambda (&rest _) "新增练习")))
            (org-agenda nil "d")
            (with-current-buffer org-agenda-buffer-name
              (goto-char (point-min))
              (search-forward "上午")
              (beginning-of-line)
              (should (equal '(task "2026-09-23" 65)
                             (get-text-property (point) 'org-workflow-agenda-create-context)))
              (org-workflow-agenda-create-at-point)
              (should (search-forward "新增练习" nil t))
              (should (org-get-at-bol 'org-hd-marker)))
            (with-temp-buffer
              (insert-file-contents file)
              (should (string-match-p "\\*\\* TODO \\[#[A]\\] 新增练习" (buffer-string)))
              (should (string-match-p "SCHEDULED: <2026-09-23" (buffer-string))))))
      (when-let* ((buffer (get-buffer org-agenda-buffer-name))) (kill-buffer buffer))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest note-gtd-week-agenda-rotates-only-past-journals ()
  (let* ((directory (make-temp-file "week-rotate-" t))
         (vulpea-default-notes-directory directory)
         (current (org-workflow-week-file "2026-09-23"))
         (old (org-workflow-week-file "2026-09-16"))
         (future (org-workflow-week-file "2026-09-30"))
         (other (expand-file-name "project.org" directory))
         (org-agenda-files (list old future other)))
    (unwind-protect
        (progn
          (make-directory (file-name-directory current) t)
          (dolist (file (list old future current))
            (with-temp-file file (insert "#+filetags: :journal-week:\n* 收集箱\n")))
          (with-temp-file other (insert "#+filetags: :project:\n"))
          (cl-letf (((symbol-function 'org-workflow-target--today-string)
                     (lambda () "2026-09-23"))
                    ((symbol-function 'org-store-new-agenda-file-list)
                     (lambda (files) (setq org-agenda-files files)))
                    ((symbol-function 'org-install-agenda-files-menu) #'ignore))
            (org-workflow-week-ensure)
            (should (member current (mapcar #'expand-file-name org-agenda-files)))
            (should (member future (mapcar #'expand-file-name org-agenda-files)))
            (should (member other (mapcar #'expand-file-name org-agenda-files)))
            (should-not (member old (mapcar #'expand-file-name org-agenda-files)))
            (with-current-buffer (find-file-noselect current)
              (should (member "area" org-file-tags)))))
      (dolist (file (list current old future other))
        (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest note-gtd-sprint-creates-habit-from-habit-section ()
  (let* ((directory (make-temp-file "sprint-habit-" t))
         (org-workflow-habit-file (expand-file-name "habits.org" directory))
         (org-agenda-files nil)
         (org-agenda-buffer-name "*Sprint habit create test*")
         (org-workflow-agenda-columns-enabled nil))
    (unwind-protect
        (cl-letf (((symbol-function 'org-workflow-target--today-string)
                   (lambda () "2026-09-23"))
                  ((symbol-function 'read-string)
                   (lambda (&rest _) "每日复习")))
          (org-agenda nil "d")
          (with-current-buffer org-agenda-buffer-name
            (goto-char (point-min))
            (search-forward "习惯")
            (should (eq 'org-workflow-agenda-habit (get-text-property (1- (point)) 'face)))
            (should (get-text-property (1- (point)) 'org-agenda-structural-header))
            (beginning-of-line)
            (should (eq 'habit (get-text-property (point) 'org-workflow-agenda-create-context)))
            (org-workflow-agenda-create-at-point))
          (with-temp-buffer
            (insert-file-contents org-workflow-habit-file)
            (should (string-match-p "\\* TODO 每日复习" (buffer-string)))
            (should (string-match-p ":STYLE: habit" (buffer-string)))))
      (when-let* ((buffer (get-buffer org-agenda-buffer-name))) (kill-buffer buffer))
      (when-let* ((buffer (get-file-buffer org-workflow-habit-file))) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest note-gtd-sprint-creates-task-in-future-period ()
  (let* ((directory (make-temp-file "sprint-future-create-" t))
         (file (expand-file-name "2026-09-21.org" directory))
         (org-agenda-files (list file))
         (org-agenda-buffer-name "*Sprint future create test*")
         (org-workflow-agenda-columns-enabled nil)
         (org-workflow-agenda-future-expanded t))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "#+filetags: :area:\n* 收集箱\n** TODO [#B] Existing\nSCHEDULED: <2026-09-24 Thu>\n"))
          (cl-letf (((symbol-function 'org-workflow-target--today-string)
                     (lambda () "2026-09-23"))
                    ((symbol-function 'org-workflow-week-ensure)
                     (lambda (&optional _) file))
                    ((symbol-function 'read-string)
                     (lambda (&rest _) "未来任务")))
            (org-agenda nil "d")
            (with-current-buffer org-agenda-buffer-name
              (org-workflow-agenda-set-day t)
              (goto-char (point-min))
              (search-forward "Existing")
              (beginning-of-line)
              (should (equal '(task "2026-09-24" 66)
                             (get-text-property (point) 'org-workflow-agenda-create-context)))
              (org-workflow-agenda-create-at-point)
              (should (search-forward "未来任务" nil t)))
            (with-temp-buffer
              (insert-file-contents file)
              (should (string-match-p "\\*\\* TODO \\[#[B]\\] 未来任务" (buffer-string)))
              (should (string-match-p "SCHEDULED: <2026-09-24" (buffer-string))))))
      (when-let* ((buffer (get-buffer org-agenda-buffer-name))) (kill-buffer buffer))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-directory directory t))))
