;;; org-workflow-history-chart-test.el --- SVG mapping contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'dom)
(require 'org-workflow-history-chart)
(unless (featurep 'org-workflow-history-view-test)
  (load (expand-file-name "org-workflow-history-view-test.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(defconst workflow-history-chart-test--style
  '(:width 420 :unit 20 :font 12 :bg "#ffffff" :fg "#202020" :muted "#666666"
    :levels ("#eeeeee" "#cceeee" "#88bbbb" "#447777" "#004444")
    :series ("#004488" "#884400" "#440088")))
(defun workflow-history-chart-test--days (count)
  (cl-loop for i below count collect
           (workflow-history-view-test--day (org-workflow-web-export--date-add-days "2026-09-02" i))))
(ert-deftest workflow-history-chart-five-bin-boundaries ()
  (dolist (pair '((0 . 0) (1 . 1) (24 . 1) (25 . 2) (49 . 2) (50 . 3) (89 . 3) (90 . 4) (2000 . 4)))
    (let ((day (workflow-history-view-test--day "2026-09-02" "untouch")))
      (setf (plist-get day :focusTotalMinutes) (car pair))
      (should (eq (cdr pair) (org-workflow-history-chart-level day)))))
  (should (eq 'missing (org-workflow-history-chart-level '(:date "2026-09-02" :recordState "missing" :focusTotalMinutes 0)))))
(ert-deftest workflow-history-chart-unknown-is-not-zero-or-derived ()
  (let ((day (workflow-history-view-test--day "2026-09-02")))
    (setf (plist-get day :focusTotalMinutes) 999)
    (should (equal '(25 5 0) (org-workflow-history-chart-values day)))
    (should (equal '(25 5 nil) (org-workflow-history-chart-values
                              (workflow-history-view-test--without day :habitFocusMinutes))))
    (should-not (org-workflow-history-chart-values '(:recordState "missing" :habitFocusMinutes 5)))))
(ert-deftest workflow-history-chart-all-dates-weekday-and-narrow-splits ()
  (let* ((days (workflow-history-chart-test--days 84))
         (payload (apply #'workflow-history-view-test--payload days))
         (before (copy-tree payload t)))
    (dolist (width '(120 420 1000))
      (let* ((style (plist-put (copy-tree workflow-history-chart-test--style) :width width))
             (charts (org-workflow-history-chart-build payload "2026-09-02" style)))
        (dolist (kind '(:heatmaps :trends))
          (let ((all (apply #'append (mapcar (lambda (c) (plist-get c :map)) (plist-get charts kind)))))
            (should (= 84 (length all)))
            (should (equal (mapcar (lambda (d) (concat "workflow-history-day-" (plist-get d :date))) days)
                           (mapcar (lambda (h) (symbol-name (cadr h))) all))))
          (dolist (chart (plist-get charts kind))
            (should (<= (dom-attr (plist-get chart :svg) 'width) width))
            (dolist (spot (plist-get chart :map))
              (let ((coords (cdar spot)))
                (should (<= 0 (caar coords) (cadr coords) (dom-attr (plist-get chart :svg) 'width)))
                (should (<= 0 (cdar coords) (cddr coords) (dom-attr (plist-get chart :svg) 'height)))))))))
    (let* ((chart (car (plist-get (org-workflow-history-chart-build payload "2026-09-02" workflow-history-chart-test--style) :heatmaps)))
           (coords (cdar (car (plist-get chart :map)))))
      ;; Wednesday starts at row 2, not at Monday or arbitrary index zero.
      (should (= 80 (cdar coords))))
    (should (equal-including-properties payload before))))
(ert-deftest workflow-history-chart-trend-breaks-unknown-and-common-scale ()
  (let* ((days (workflow-history-chart-test--days 3))
         (_ (setf (nth 1 days) (workflow-history-view-test--without (nth 1 days) :habitFocusMinutes)))
         (chart (car (org-workflow-history-chart--trend days nil workflow-history-chart-test--style)))
         (svg (plist-get chart :svg))
         (lines (dom-by-tag svg 'line)))
    ;; Only commitment/optional connect both day pairs; habit zero has isolated points.
    (should (= 4 (cl-count-if (lambda (l) (= 2 (or (dom-attr l 'stroke-width) 0))) lines)))
    (should (= 8 (length (dom-by-tag svg 'circle))))
    (should (= 3 (length (plist-get chart :map))))
    (let ((all-missing (org-workflow-history-chart--trend
                        (list '(:date "2026-09-02" :recordState "missing")) nil workflow-history-chart-test--style)))
      (should-not (dom-by-tag (plist-get (car all-missing) :svg) 'circle)))))
(ert-deftest workflow-history-chart-native-map-shared-selection ()
  (let* ((days (workflow-history-chart-test--days 2))
         (payload (apply #'workflow-history-view-test--payload days))
         (charts (org-workflow-history-chart-build payload "2026-09-03" workflow-history-chart-test--style)))
    (workflow-history-view-test--panel payload
      (dolist (kind '(:heatmaps :trends))
        (cl-letf (((symbol-function 'svg-image) (lambda (_svg &rest props) (cons 'image props)))
                  ((symbol-function 'org-workflow-history-read) (lambda (&rest _) (ert-fail "Click reread backend"))))
          (let* ((chart (car (plist-get charts kind)))
                 (image (org-workflow-history-chart-image chart #'org-workflow-history-panel-select-date))
                 (id (cadr (car (plist-get chart :map)))))
            (should (= 1.0 (plist-get (cdar image) :scale)))
            (save-window-excursion
              (set-window-buffer (selected-window) (current-buffer))
              (funcall (lookup-key (cdr image) (vector id 'mouse-1))
                       (list 'mouse-1 (list (selected-window) (point-min) '(0 . 0) 0))))
            (should (equal "2026-09-02" (plist-get org-workflow-history-panel--model :selected-date)))
            (should (eq (car days) (plist-get org-workflow-history-panel--model :detail)))))))))
(provide 'org-workflow-history-chart-test)

(ert-deftest workflow-history-chart-lifecycle-observers-and-no-timers ()
  (let ((before-enable (copy-sequence enable-theme-functions))
        (before-disable (copy-sequence disable-theme-functions))
        (timers (copy-sequence timer-list)) (idle-timers (copy-sequence timer-idle-list))
        (payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-02"))))
    (workflow-history-view-test--panel payload
      (dotimes (_ 3)
        (org-workflow-history-panel--activate)
        (should (= 1 (cl-count #'org-workflow-history-panel--theme-changed enable-theme-functions)))
        (should (memq #'org-workflow-history-panel--adapt window-size-change-functions))
        (cl-letf (((symbol-function 'quit-window) #'ignore)) (org-workflow-history-panel-close))
        (should-not vui--root-instance)
        (should-not (memq #'org-workflow-history-panel--theme-changed enable-theme-functions))
        (should-not (memq #'org-workflow-history-panel--adapt window-size-change-functions))
        (org-workflow-history-panel)))
    (should (equal before-enable enable-theme-functions))
    (should (equal before-disable disable-theme-functions))
    (should (equal timers timer-list))
    (should (equal idle-timers timer-idle-list))))
(ert-deftest workflow-history-chart-evil-date-keys-and-bounds ()
  (require 'evil)
  (workflow-history-view-test--panel
      (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-02" "missing")
                                          (workflow-history-view-test--day "2026-09-03"))
    (evil-local-mode 1)
    (dolist (state '(normal motion emacs))
      (evil-change-state state)
      (dolist (pair '(("d" . org-workflow-history-panel-select-date)
                      ("n" . org-workflow-history-panel-next-date)
                      ("p" . org-workflow-history-panel-previous-date)
                      ("g" . org-workflow-history-panel-refresh)
                      ("q" . org-workflow-history-panel-close)))
        (should (eq (cdr pair) (key-binding (kbd (car pair)))))))
    (org-workflow-history-panel-previous-date)
    (should (equal "2026-09-02" (plist-get org-workflow-history-panel--model :selected-date)))
    (org-workflow-history-panel-previous-date)
    (should (equal "2026-09-02" (plist-get org-workflow-history-panel--model :selected-date)))
    (org-workflow-history-panel-next-date)
    (should (equal "2026-09-03" (plist-get org-workflow-history-panel--model :selected-date)))
    (org-workflow-history-panel-next-date)
    (should (equal "2026-09-03" (plist-get org-workflow-history-panel--model :selected-date)))))

(ert-deftest workflow-history-chart-trend-date-labels-do-not-overlap ()
  "The final date must not collide with the preceding weekly tick."
  (dolist (count '(1 2 3 9 16 37))
    (let* ((style (plist-put (copy-tree workflow-history-chart-test--style) :width 1100))
           (charts (org-workflow-history-chart--trend (workflow-history-chart-test--days count) nil style)))
      (dolist (chart charts)
        (let ((labels (cl-remove-if-not
                       (lambda (node) (string-match-p "^[0-9][0-9]-[0-9][0-9]$" (dom-text node)))
                       (dom-by-tag (plist-get chart :svg) 'text))))
          (cl-loop for (a b) on labels while b do
                   (should (>= (- (dom-attr b 'x) (dom-attr a 'x)) 36))))))))

(ert-deftest workflow-history-chart-click-in-nonselected-window ()
  "Mouse activation uses its event window, even if another buffer owns focus."
  (workflow-history-view-test--panel
      (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-02")
                                          (workflow-history-view-test--day "2026-09-03"))
    (save-window-excursion
      (let ((panel (current-buffer)) (window (selected-window)))
        (set-window-buffer window panel)
        (let* ((chart (car (org-workflow-history-chart--heatmap
                            (workflow-history-chart-test--days 2) "2026-09-03" workflow-history-chart-test--style)))
               (image (cl-letf (((symbol-function 'svg-image) (lambda (&rest _) nil)))
                        (org-workflow-history-chart-image chart #'org-workflow-history-panel-select-date)))
               (command (lookup-key (cdr image) (vector (cadr (car (plist-get chart :map))) 'mouse-1)))
               (other (split-window-below)))
          (set-window-buffer other (get-buffer-create " *history-other-window*"))
          (unwind-protect
              (with-selected-window other
                (funcall command (list 'mouse-1 (list window 1 '(50 . 50) 0)))
                (should (eq other (selected-window)))
                (should (equal "2026-09-02" (plist-get (buffer-local-value 'org-workflow-history-panel--model panel) :selected-date))))
            (kill-buffer " *history-other-window*")))))))

(ert-deftest workflow-history-chart-hotspot-inherits-wheel-bindings ()
  "Date prefixes must retain ordinary wheel and configured modifier actions."
  (require 'mwheel)
  (let* ((chart (car (org-workflow-history-chart--heatmap
                      (workflow-history-chart-test--days 2) nil workflow-history-chart-test--style)))
         (original (current-global-map))
         (global (copy-keymap (current-global-map))))
    (let ((global-map global))
      (use-global-map global)
      (unwind-protect
          (progn
            (define-key global [C-wheel-up] #'text-scale-increase)
            (let* ((image (cl-letf (((symbol-function 'svg-image) (lambda (&rest _) nil)))
                            (org-workflow-history-chart-image chart #'ignore)))
                   (map (cdr image)))
              (dolist (spot (plist-get chart :map))
                (dolist (event '(wheel-up wheel-down wheel-left wheel-right mouse-4 mouse-5 C-wheel-up))
                  (should (eq (lookup-key global (vector event))
                              (lookup-key map (vector (cadr spot) event)))))
                (should (eq #'text-scale-increase (lookup-key map (vector (cadr spot) 'C-wheel-up)))))))
        (use-global-map original)))))
