;;; org-workflow-agenda-mouse-test.el --- Sprint mouse regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org-workflow-agenda-workbench-test
         (expand-file-name "org-workflow-agenda-workbench-test.el"
                           (file-name-directory (or load-file-name buffer-file-name))))
(require 'org-workflow-agenda-mouse)

(defun my/org-mouse-test-open ()
  "Open the candidate pane for mouse tests of unscheduled project tasks."
  (org-workflow-workbench-test-open)
  (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
    (select-window (get-buffer-window candidate))))

(defun my/org-mouse-test-row (title)
  "Move to the task named TITLE and return its native source marker."
  (goto-char (point-min))
  (let (found)
    (while (and (not found) (< (point) (point-max)))
      (when-let* ((marker (org-get-at-bol 'org-hd-marker)))
        (when (equal title (org-with-point-at marker (org-get-heading t t t t)))
          (setq found marker)))
      (unless found (forward-line)))
    (should found)
    found))

(defun my/org-mouse-test-selected ()
  "Return sorted source titles selected through native Agenda bulk marks."
  (sort (mapcar (lambda (marker)
                 (org-with-point-at marker (org-get-heading t t t t)))
               org-agenda-bulk-marked-entries)
        #'string-lessp))

(defun my/org-mouse-test-event (type)
  "Build a buffer-position event for the selected test window."
  (list type (list (selected-window) (point) '(10 . 10) 0)))

(ert-deftest my/org-mouse-right-press-overrides-global-context-menu ()
  (let ((was-enabled context-menu-mode))
    (unwind-protect
        (progn
          (context-menu-mode 1)
          (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
            (my/org-mouse-test-open)
            (my/org-mouse-test-row "First")
            (dolist (evil-enabled '(nil t))
              (if evil-enabled (evil-local-mode 1) (evil-local-mode -1))
              (when evil-enabled (evil-normal-state))
              (org-workflow-agenda-mouse--setup)
              (should (eq (key-binding [down-mouse-3]) #'org-workflow-agenda-mouse-menu))
              (should (eq (key-binding [mouse-3]) #'ignore))
              (let (menu)
                (cl-letf (((symbol-function 'popup-menu)
                           (lambda (value &rest _) (setq menu value))))
                  (funcall (key-binding [down-mouse-3])
                           (my/org-mouse-test-event 'down-mouse-3)))
                (should (assq 'morning (cdr menu)))
                (should (equal '("First") (my/org-mouse-test-selected))))))
          (with-temp-buffer
            (org-agenda-mode)
            (org-workflow-agenda-mouse--setup)
            (should-not org-workflow-agenda-mouse-mode)
            (should-not (eq (key-binding [down-mouse-3]) #'org-workflow-agenda-mouse-menu))
            (should (keymapp (key-binding [down-mouse-3])))))
      (context-menu-mode (if was-enabled 1 -1)))))

(ert-deftest my/org-mouse-single-and-control-use-native-bulk-marks ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (should (equal '("First") (my/org-mouse-test-selected)))
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'control)
    (should (equal '("First" "Second") (my/org-mouse-test-selected)))
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") 'control)
    (should (equal '("Second") (my/org-mouse-test-selected)))
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Third") nil)
    (should (equal '("Third") (my/org-mouse-test-selected)))
    (should (equal "Third"
                   (org-with-point-at org-workflow-agenda-mouse--anchor
                     (org-get-heading t t t t))))))

(ert-deftest my/org-mouse-shift-selects-inclusive-visible-range ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Third") 'shift)
        (should (equal '("First" "Second" "Third") (my/org-mouse-test-selected)))
        (org-workflow-agenda--clear-selection)
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'shift)
        (should (equal '("Second") (my/org-mouse-test-selected)))))))

(ert-deftest my/org-mouse-shift-skips-filtered-tasks ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n* DIVE Project\n** TODO First :@deep:\n** TODO Hidden :@flow:\n** TODO Last :@deep:\n")
    (my/org-mouse-test-open)
    (org-workflow-agenda--filter-tag "@deep")
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Last") 'shift)
    (should (equal '("First" "Last") (my/org-mouse-test-selected)))))

(ert-deftest my/org-mouse-selection-is-exclusive-to-one-pane ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil))
      (with-current-buffer primary
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Today") nil)
        (should (equal '("Today") (my/org-mouse-test-selected))))
      (with-current-buffer candidate
        (should-not org-agenda-bulk-marked-entries)
        (should-not org-workflow-agenda-mouse--anchor)))))

(ert-deftest my/org-mouse-day-filter-and-group-clear-anchor ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
        (org-workflow-agenda-set-day t)
        (should-not org-agenda-bulk-marked-entries)
        (should-not org-workflow-agenda-mouse--anchor)
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
        (org-workflow-agenda--filter-tag "@deep")
        (should-not org-agenda-bulk-marked-entries)
        (should-not org-workflow-agenda-mouse--anchor)
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
        (funcall (alist-get 'select (cadr (org-workflow-agenda-candidate-tabs))))
        (should-not org-agenda-bulk-marked-entries)
        (should-not org-workflow-agenda-mouse--anchor)))))

(ert-deftest my/org-mouse-redo-retains-visible-selection ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
        (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'control)
        (org-agenda-redo)
        (should (equal '("First" "Second") (my/org-mouse-test-selected)))
        (should (marker-buffer org-workflow-agenda-mouse--anchor)))
      (with-current-buffer primary (should-not org-agenda-bulk-marked-entries)))))

(ert-deftest my/org-mouse-row-classification-and-local-mode ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (should org-workflow-agenda-mouse-mode)
    (my/org-mouse-test-row "First")
    (should (eq 'task (org-workflow-agenda-mouse--row-kind)))
    (goto-char (point-min))
    (should-not (org-workflow-agenda-mouse--row-kind))
    (with-temp-buffer
      (org-agenda-mode)
      (should-not org-workflow-agenda-mouse-mode)
      (should-not org-workflow-agenda--sprint-buffer-p))))

(ert-deftest my/org-mouse-menu-does-not-mutate-source ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (let ((source (with-current-buffer (find-file-noselect (car files)) (buffer-string))))
      (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
      (should (keymapp (org-workflow-agenda-mouse--menu)))
      (should (equal source (with-current-buffer (find-file-noselect (car files))
                              (buffer-string)))))))

(ert-deftest my/org-mouse-batch-menu-disables-access-and-reordering ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'control)
    (let ((menu (org-workflow-agenda-mouse--menu)))
      (dolist (key '(open up down))
        (let ((definition (cdr (assq key (cdr menu)))))
          (should (eq (car definition) 'menu-item))
          (should-not (plist-get (nthcdr 3 definition) :enable))))
      (should (plist-get (nthcdr 3 (cdr (assq 'morning (cdr menu)))) :enable)))))

(ert-deftest my/org-mouse-habits-do-not-join-control-or-shift-ranges ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (let ((habit (my/org-mouse-test-row "First")))
      (org-with-point-at habit (org-entry-put nil "STYLE" "habit"))
      (should (eq 'habit (org-workflow-agenda-mouse--row-kind)))
      (org-workflow-agenda-mouse--select habit nil)
      (should (equal '("First") (my/org-mouse-test-selected)))
      (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'control)
      (should (equal '("Second") (my/org-mouse-test-selected)))
      (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Third") 'shift)
      (should (equal '("Second" "Third") (my/org-mouse-test-selected))))))

(ert-deftest my/org-mouse-completed-rows-only-offer-access ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (let ((marker (my/org-mouse-test-row "First")))
      (org-with-point-at marker
        (let ((org-inhibit-logging t)) (org-todo "DONE")))
      (should (eq 'completed (org-workflow-agenda-mouse--row-kind)))
      (org-workflow-agenda-mouse--select marker nil)
      (should-not org-agenda-bulk-marked-entries)
      (let ((menu (org-workflow-agenda-mouse--menu)))
        (should (assq 'open (cdr menu)))
        (should-not (assq 'morning (cdr menu)))
        (should-not (assq 'complete (cdr menu)))))))

(ert-deftest my/org-mouse-single-column-open-uses-native-visit ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (my/org-mouse-test-row "Today")
    (let (visited)
      (cl-letf (((symbol-function 'org-agenda-switch-to)
                 (lambda (&rest _) (setq visited t))))
        (org-workflow-agenda-mouse-open))
      (should visited))))

(ert-deftest my/org-mouse-right-click-preserves-group-or-selects-new-row ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Second") 'control)
    (cl-letf (((symbol-function 'popup-menu) (lambda (&rest _) nil)))
      (my/org-mouse-test-row "First")
      (org-workflow-agenda-mouse-menu (my/org-mouse-test-event 'mouse-3))
      (should (equal '("First" "Second") (my/org-mouse-test-selected)))
      (my/org-mouse-test-row "Third")
      (org-workflow-agenda-mouse-menu (my/org-mouse-test-event 'mouse-3))
      (should (equal '("Third") (my/org-mouse-test-selected))))))

(ert-deftest my/org-mouse-blank-click-clears-selection-and-anchor ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (goto-char (point-min))
    (while (and (< (point) (point-max))
                (or (not (looking-at-p "[ \t]*$")) (button-at (point))))
      (forward-line))
    (should (< (point) (point-max)))
    (should-not (org-get-at-bol 'org-hd-marker))
    (org-workflow-agenda-mouse-click (my/org-mouse-test-event 'mouse-1))
    (should-not org-agenda-bulk-marked-entries)
    (should-not org-workflow-agenda-mouse--anchor)))

(ert-deftest my/org-mouse-dedicated-open-restores-origin-tab-and-keeps-panes ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let ((saved-tabs (frame-parameter nil 'tabs)))
      (unwind-protect
          (progn
            (switch-to-buffer (get-buffer-create "*Mouse original editor*"))
            (let ((origin-index (tab-bar--current-tab-index)))
              (org-workflow-agenda-open-workbench)
              (let* ((state org-workflow-agenda--workbench)
                     (candidate (org-workflow-agenda-workbench-candidates state))
                     (primary (org-workflow-agenda-workbench-primary state))
                     (count (length (tab-bar-tabs))))
                (select-window (get-buffer-window candidate))
                (let ((marker (my/org-mouse-test-row "First")))
                  (org-workflow-agenda-mouse-open)
                  (should (= origin-index (tab-bar--current-tab-index)))
                  (should (= count (length (tab-bar-tabs))))
                  (should (eq (current-buffer) (marker-buffer marker)))
                  (should (= (point) (marker-position marker))))
                (let ((index (seq-position (tab-bar-tabs) state
                                          (lambda (tab workbench)
                                            (eq (alist-get 'org-workflow-agenda-workbench tab)
                                                workbench)))))
                  (should index)
                  (tab-bar-select-tab (1+ index))
                  (should (get-buffer-window primary))
                  (should (get-buffer-window candidate))
                  (tab-bar-close-tab)))))
        (set-frame-parameter nil 'tabs saved-tabs)))))

(ert-deftest my/org-mouse-dedicated-open-creates-tab-if-origin-closed ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let ((saved-tabs (frame-parameter nil 'tabs)))
      (unwind-protect
          (progn
            (org-workflow-agenda-open-workbench)
            (let* ((state org-workflow-agenda--workbench)
                   (token (gethash 'mouse-origin-tab
                                   (org-workflow-agenda-workbench-settings state)))
                   (origin (seq-position (tab-bar-tabs) token
                                         (lambda (tab id)
                                           (eq (alist-get 'org-workflow-agenda-origin tab) id)))))
              (should origin)
              (tab-bar-close-tab (1+ origin))
              (select-window (get-buffer-window (org-workflow-agenda-workbench-candidates state)))
              (let ((marker (my/org-mouse-test-row "First"))
                    (count (length (tab-bar-tabs))))
                (org-workflow-agenda-mouse-open)
                (should (= (1+ count) (length (tab-bar-tabs))))
                (should (eq (current-buffer) (marker-buffer marker)))
                (should (= (point) (marker-position marker)))
                (should (buffer-live-p (org-workflow-agenda-workbench-primary state)))
                (should (buffer-live-p (org-workflow-agenda-workbench-candidates state)))
                (tab-bar-close-tab))))
        (set-frame-parameter nil 'tabs saved-tabs)))))

(ert-deftest my/org-mouse-drop-plans-explicit-day-and-refreshes-both-panes ()
  (dolist (date '("2026-08-17" "2026-08-18" "2026-08-23"))
    (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
      (let ((org-workflow-store-enabled nil))
        (my/org-mouse-test-open)
        (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
          (with-current-buffer candidate
            (let ((first (copy-marker (my/org-mouse-test-row "First")))
                  (second (copy-marker (my/org-mouse-test-row "Second"))))
              (org-workflow-agenda-mouse--drop (list first second) date ?B)
              (dolist (marker (list first second))
                (org-with-point-at marker
                  (should (= ?B (nth 3 (org-heading-components))))
                  (should (equal date (org-workflow-target--timestamp-date
                                      (org-entry-get nil "SCHEDULED"))))))
              (should-not org-agenda-bulk-marked-entries)
              (should-not org-workflow-agenda-mouse--anchor)
              (should (equal "2026-08-17" (org-workflow-agenda-target-date)))
              (should-not (member "First" (org-workflow-workbench-test-titles candidate)))
              (should-not (member "Second" (org-workflow-workbench-test-titles candidate)))
              (if (equal date "2026-08-17")
                  (progn
                    (should (member "First" (org-workflow-workbench-test-titles primary)))
                    (should (member "Second" (org-workflow-workbench-test-titles primary))))
                (should-not (member "First" (org-workflow-workbench-test-titles primary)))
                (should-not (member "Second" (org-workflow-workbench-test-titles primary)))))))))))

(ert-deftest my/org-mouse-drop-no-op-keeps-source-and-undo-record ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n* Project :CURR:\n** TODO [#B] Already\nSCHEDULED: <2026-08-17 Mon>\n")
    (let ((org-workflow-store-enabled nil)
          (org-workflow-agenda-last-plan '(previous-plan)))
      (org-workflow-workbench-test-open)
      (let ((marker (my/org-mouse-test-row "Already"))
            (source (with-current-buffer (find-file-noselect (car files)) (buffer-string))))
        (cl-letf (((symbol-function 'org-workflow-agenda-plan-at)
                   (lambda (&rest _) (ert-fail "No-op must not arrange again"))))
          (org-workflow-agenda-mouse--drop (list marker) "2026-08-17" ?B))
        (should (equal '(previous-plan) org-workflow-agenda-last-plan))
        (should (equal source (with-current-buffer (marker-buffer marker) (buffer-string))))))))

(ert-deftest my/org-mouse-drop-rejects-invalid-readonly-and-hidden-batch ()
  (dolist (invalid-kind '(invalid readonly hidden))
    (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
      (let ((org-workflow-store-enabled nil))
        (my/org-mouse-test-open)
        (let* ((first (copy-marker (my/org-mouse-test-row "First")))
               (second (copy-marker (my/org-mouse-test-row "Second")))
               (source-buffer (marker-buffer first))
               (source (with-current-buffer source-buffer (buffer-string))))
          (unwind-protect
              (progn
                (pcase invalid-kind
                  ('invalid (set-marker second nil))
                  ('readonly (with-current-buffer source-buffer (setq buffer-read-only t)))
                  ('hidden (org-workflow-agenda--filter-tag "@deep")))
                (should-error (org-workflow-agenda-mouse--drop (list first second) "2026-08-18" ?A)
                              :type 'user-error)
                (should (equal source (with-current-buffer source-buffer (buffer-string)))))
            (with-current-buffer source-buffer (setq buffer-read-only nil))))))))

(ert-deftest my/org-mouse-drop-rolls-back-on-mid-batch-failure ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let ((org-workflow-store-enabled nil))
      (my/org-mouse-test-open)
      (let* ((first (copy-marker (my/org-mouse-test-row "First")))
             (second (copy-marker (my/org-mouse-test-row "Second")))
             (source-buffer (marker-buffer first))
             (source (with-current-buffer source-buffer (buffer-string)))
             (original (symbol-function 'org-agenda-schedule))
             (calls 0))
        (cl-letf (((symbol-function 'org-agenda-schedule)
                   (lambda (&rest args)
                     (if (= (cl-incf calls) 2)
                         (error "Injected second-task failure")
                       (apply original args)))))
          (should-error (org-workflow-agenda-mouse--drop (list first second) "2026-08-18" ?A)))
        (should (= calls 2))
        (should (equal source (with-current-buffer source-buffer (buffer-string))))))))

(ert-deftest my/org-mouse-drop-batch-undo-restores-source-and-two-panes ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let* ((directory (make-temp-file "mouse-undo-" t))
           (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
           (org-workflow-store--connection nil)
           (org-workflow-store--path nil)
           (org-workflow-store-enabled t)
           (org-id-locations-file (expand-file-name "ids" directory))
           (org-id-locations (make-hash-table :test #'equal))
           (org-id-files nil)
           (org-workflow-agenda-last-plan nil)
           (org-workflow-executing-marker nil)
           (org-workflow-target-selected-marker nil)
           (org-workflow-current-changed-hook nil))
      (unwind-protect
          (progn
            (my/org-mouse-test-open)
            (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
              (with-current-buffer candidate
                (let ((markers (list (copy-marker (my/org-mouse-test-row "First"))
                                     (copy-marker (my/org-mouse-test-row "Second")))))
                  (org-workflow-agenda-mouse--drop markers "2026-08-18" ?C)
                  (should org-workflow-agenda-last-plan)
                  (should (= 2 (length (plist-get org-workflow-agenda-last-plan :markers))))
                  (org-workflow-agenda-undo-plan)
                  (dolist (marker markers)
                    (org-with-point-at marker
                      (should-not (org-entry-get nil "SCHEDULED"))
                      (should-not (nth 3 (org-heading-components)))))))
              (should-not org-workflow-agenda-last-plan)
              (should (member "First" (org-workflow-workbench-test-titles candidate)))
              (should (member "Second" (org-workflow-workbench-test-titles candidate)))
              (should-not (member "First" (org-workflow-workbench-test-titles primary)))
              (should-not (member "Second" (org-workflow-workbench-test-titles primary)))))
        (when (and org-workflow-store--connection
                   (org-workflow-store--live-p org-workflow-store--connection))
          (sqlite-close org-workflow-store--connection))
        (delete-directory directory t)))))

(defun my/org-mouse-test-target-position (window date period)
  "Return a native position inside WINDOW's DATE and PERIOD band."
  (with-current-buffer (window-buffer window)
    (let ((position (point-min)) found)
      (while (and (< position (point-max)) (not found))
        (if (equal (list 'task date period)
                   (get-text-property position 'org-workflow-agenda-create-context))
            (setq found position)
          (setq position (next-single-property-change
                          position 'org-workflow-agenda-create-context nil (point-max)))))
      (should found)
      (list window found '(30 . 30) 0))))

(ert-deftest my/org-mouse-drop-target-rejects-candidates-and-other-workbench ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (let* ((state (buffer-local-value 'org-workflow-agenda--workbench primary))
             (position (my/org-mouse-test-target-position
                        (get-buffer-window primary) "2026-08-17" ?C)))
        (should (equal '(task "2026-08-17" ?C)
                       (nth 1 (org-workflow-agenda-mouse--target position state))))
        (should-not (org-workflow-agenda-mouse--target position
                                               (org-workflow-agenda-workbench-create)))
        (select-window (get-buffer-window candidate))
        (my/org-mouse-test-row "First")
        (should-not (org-workflow-agenda-mouse--target
                     (event-start (my/org-mouse-test-event 'mouse-1)) state))))))

(ert-deftest my/org-mouse-drag-release-arranges-and-cancel-cleans-highlight ()
  (dolist (cancel '(nil 27 7 release-only))
    (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
      (let ((org-workflow-store-enabled nil))
        (my/org-mouse-test-open)
        (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
          (let* ((target-window (get-buffer-window primary))
                 (position (my/org-mouse-test-target-position target-window "2026-08-17" ?C)))
            (select-window (get-buffer-window candidate))
            (let* ((marker (copy-marker (my/org-mouse-test-row "First")))
                   (source (with-current-buffer (marker-buffer marker) (buffer-string)))
                   (events (if (eq cancel 'release-only)
                               (list (list 'drag-mouse-1
                                           (event-start (my/org-mouse-test-event 'down-mouse-1))
                                           position))
                             (list (list 'mouse-movement position)
                                   (or cancel (list 'mouse-1 position))))))
              (cl-letf (((symbol-function 'read-event)
                         (lambda (&rest _) (or (pop events) (ert-fail "Unexpected event read"))))
                        ((symbol-function 'org-workflow-agenda-mouse--scroll-target) #'ignore))
                (org-workflow-agenda-mouse-down (my/org-mouse-test-event 'down-mouse-1)))
              (if (memq cancel '(27 7))
                  (should (equal source (with-current-buffer (marker-buffer marker) (buffer-string))))
                (org-with-point-at marker
                  (should (equal "2026-08-17"
                                 (org-workflow-target--timestamp-date (org-entry-get nil "SCHEDULED"))))
                  (should (= ?C (nth 3 (org-heading-components))))))
              (with-current-buffer primary
                (should-not (seq-some (lambda (overlay)
                                       (and (eq (overlay-get overlay 'face) 'highlight)
                                            (overlay-get overlay 'window)))
                                     (overlays-in (point-min) (point-max))))))))))))

(ert-deftest my/org-mouse-auto-scroll-only-originating-workbench ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (let ((window (selected-window))
          (state org-workflow-agenda--workbench)
          scrolls)
      (cl-letf (((symbol-function 'scroll-down)
                 (lambda (amount) (push (list 'down amount) scrolls)))
                ((symbol-function 'scroll-up)
                 (lambda (amount) (push (list 'up amount) scrolls)))
                ((symbol-function 'window-body-height) (lambda (&rest _) 400)))
        (org-workflow-agenda-mouse--scroll-target (list window (point) '(20 . 0) 0) state)
        (org-workflow-agenda-mouse--scroll-target
         (list window (point) (cons 20 (window-body-height window t)) 0) state)
        (should (equal '((up 1) (down 1)) scrolls))
        (org-workflow-agenda-mouse--scroll-target
         (list window (point) '(20 . 0) 0) (org-workflow-agenda-workbench-create))
        (let ((org-workflow-agenda--pane-role 'candidates))
          (org-workflow-agenda-mouse--scroll-target
           (list window (point) '(20 . 0) 0) state))
        (should (= 2 (length scrolls)))))))

(ert-deftest my/org-mouse-mixed-drop-skips-already-correct-task ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n* Project :CURR:\n** TODO [#B] Already\nSCHEDULED: <2026-08-17 Mon>\n** TODO [#A] New\nSCHEDULED: <2026-08-17 Mon>\n")
    (let ((org-workflow-store-enabled nil))
      (org-workflow-workbench-test-open)
      (let ((already (copy-marker (my/org-mouse-test-row "Already")))
            (new (copy-marker (my/org-mouse-test-row "New")))
            (original (symbol-function 'org-agenda-schedule))
            scheduled)
        (cl-letf (((symbol-function 'org-agenda-schedule)
                   (lambda (&rest args)
                     (push (copy-marker (org-get-at-bol 'org-hd-marker)) scheduled)
                     (apply original args))))
          (org-workflow-agenda-mouse--drop (list already new) "2026-08-17" ?B))
        (should (= 1 (length scheduled)))
        (should (equal new (car scheduled)))))))

(ert-deftest my/org-mouse-menu-items-are-real-interactive-commands ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (my/org-mouse-test-open)
    (org-workflow-agenda-mouse--select (my/org-mouse-test-row "First") nil)
    (dolist (entry (cdr (org-workflow-agenda-mouse--menu)))
      (when (and (consp entry) (eq (cadr entry) 'menu-item))
        (should (commandp (nth 3 entry)))))))

(ert-deftest my/org-mouse-batch-commitment-updates-all-and-rolls-back-bad-date ()
  (dolist (bad-date '(nil t))
    (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
      (let* ((directory (make-temp-file "mouse-commitment-" t))
             (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
             (org-workflow-store--connection nil)
             (org-workflow-store--path nil)
             (org-workflow-store-enabled t)
             (org-id-locations-file (expand-file-name "ids" directory))
             (org-id-locations (make-hash-table :test #'equal))
             (org-id-files nil)
             (org-workflow-agenda-last-plan nil)
             (org-workflow-executing-marker nil)
             (org-workflow-target-selected-marker nil)
             (org-workflow-current-changed-hook nil))
        (unwind-protect
            (progn
              (org-workflow-workbench-test-open)
              ;; Exercise the legacy renderer API; Sprint itself hides this section.
              (org-workflow-agenda-future nil)
              (let* ((first (copy-marker (my/org-mouse-test-row (if bad-date "Today" "Tomorrow"))))
                     (second (copy-marker (my/org-mouse-test-row "Later")))
                     (source-buffer (marker-buffer first))
                     (source (with-current-buffer source-buffer (buffer-string))))
                ;; Native bulk marks prepend; Later is processed before the bad Today date.
                (org-workflow-agenda-mouse--select first nil)
                (org-workflow-agenda-mouse--select second 'control)
                (if bad-date
                    (progn
                      (should-error (org-workflow-agenda-mouse-toggle-commitment) :type 'user-error)
                      (should (equal source (with-current-buffer source-buffer (buffer-string))))
                      (should (= 0 (caar (sqlite-select
                                          (org-workflow-store--db)
                                          "SELECT count(*) FROM commitments")))))
                  (org-workflow-agenda-mouse-toggle-commitment)
                  (dolist (marker (list first second))
                    (org-with-point-at marker
                      (should (org-workflow-store-commitment
                               (org-entry-get nil "WORKFLOW_COMMITMENT_ID")))))
                  (should org-workflow-agenda-last-plan)
                  (should-not org-agenda-bulk-marked-entries))))
          (when (and org-workflow-store--connection
                     (org-workflow-store--live-p org-workflow-store--connection))
            (sqlite-close org-workflow-store--connection))
          (delete-directory directory t))))))

(provide 'org-workflow-agenda-mouse-test)
;;; org-workflow-agenda-mouse-test.el ends here
