;;; org-workflow-history-view-test.el --- Historical facts -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-history-panel)

(defun workflow-history-view-test--day (date &optional state)
  (if (equal state "missing") (list :date date :recordState state)
    (copy-tree (list :date date :recordState "finalized" :commitment (or state "met")
          :commitmentFocusMinutes 25 :optionalFocusMinutes 5 :focusTotalMinutes 30
          :optionalCompleted 0 :finalizedAt "2026-09-17T00:00:00+08:00"
          :minimumTasks [(:task "长标题：原始任务" :outcome "pending" :focusMinutes 25 :satisfied t)]
          :optionalTasks [(:task "可选" :outcome "focused" :focusMinutes 5)]
          :habitFocusMinutes 0 :habitCompleted 0 :habitTasks []) t)))
(defun workflow-history-view-test--payload (&rest days)
  (list :schema "org-workflow-history" :schemaVersion 1
        :generatedAt "2026-09-17T12:00:00+08:00" :timezone "Asia/Shanghai"
        :coverage (if days (list :trackingStarted (plist-get (car days) :date)
                                :eligibleThrough (plist-get (car (last days)) :date)) :null)
        :days (vconcat days)))
(defun workflow-history-view-test--leave (date)
  (copy-tree (vector (list :id "leave" :date date :slots ["morning"] :reason "休息原文"
                :recordedAt "2026-09-17T12:00:00+08:00"
                :tasks [(:id :null :task "相关任务" :slot :null)])) t))
(defmacro workflow-history-view-test--panel (payload &rest body)
  (declare (indent 1))
  `(unwind-protect
       (cl-letf (((symbol-function 'org-workflow-history-read) (lambda (&rest _) ,payload))
                 ((symbol-function 'display-buffer) #'ignore))
         (with-current-buffer (org-workflow-history-panel) ,@body))
     (when (get-buffer "*Workflow History*") (kill-buffer "*Workflow History*"))))

(ert-deftest workflow-history-detail-tracer-finalized ()
  (let* ((date "2026-09-16") (day (workflow-history-view-test--day date))
         (payload (workflow-history-view-test--payload
                   (workflow-history-view-test--day "2026-09-15" "missing")
                   (plist-put day :leaveRecords (workflow-history-view-test--leave date)))))
    (workflow-history-view-test--panel payload
      (should (equal date (plist-get org-workflow-history-panel--model :selected-date)))
      (dolist (text '("累计投入 30 分钟" "连续达标 1 天"
                      "承诺状态：已达标（met）" "任务状态：待完成；投入：25 分钟"
                      "承诺履行：已满足" "习惯投入：0 分钟；习惯完成：0 项"
                      "无习惯任务" "结算时间：" "理由：休息原文" "时段未指定"))
        (should (string-match-p (regexp-quote text) (buffer-string)))))))
(ert-deftest workflow-history-detail-tracer-missing ()
  (let* ((date "2026-09-15")
         (day (plist-put (workflow-history-view-test--day date "missing")
                         :leaveRecords (workflow-history-view-test--leave date)))
         (payload (workflow-history-view-test--payload day (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (let ((reads 0))
        (cl-letf (((symbol-function 'org-workflow-history-read)
                   (lambda (&rest _) (cl-incf reads) (ert-fail "Selection reread"))))
          (workflow-history-test--no-writes (org-workflow-history-panel-select-date date)))
        (should (= 0 reads)))
      (should (equal date (plist-get org-workflow-history-panel--model :selected-date)))
      (should (equal day (plist-get org-workflow-history-panel--model :detail)))
      (should (string-match-p "记录缺失（missing）" (buffer-string)))
      (should (string-match-p "理由：休息原文" (buffer-string)))
      (should-not (string-match-p "承诺状态：\|任务状态：\|结算时间：" (buffer-string))))))
(defun workflow-history-view-test--without (object &rest keys)
  (cl-loop for (key value) on object by #'cddr unless (memq key keys) append (list key value)))

(ert-deftest workflow-history-view-empty-valid ()
  (let ((payload (workflow-history-view-test--payload)))
    (should (eq payload (org-workflow-history-view-validate payload)))
    (should-not (org-workflow-history-view-date-options payload))))
(ert-deftest workflow-history-view-four-states-and-source-identity ()
  (let* ((days (cl-loop for date in '("2026-09-13" "2026-09-14" "2026-09-15" "2026-09-16")
                        for state in '("met" "unmet" "untouch" "missing")
                        collect (workflow-history-view-test--day date state)))
         (payload (apply #'workflow-history-view-test--payload days)))
    (should (eq payload (org-workflow-history-view-validate payload)))
    (should (equal '("2026-09-13 · 已达标" "2026-09-14 · 未达标" "2026-09-15 · 未触及" "2026-09-16 · 记录缺失")
                   (mapcar #'cdr (org-workflow-history-view-date-options payload))))
    (cl-loop for day in days do (should (eq day (org-workflow-history-view-detail payload (plist-get day :date)))))))
(ert-deftest workflow-history-view-presence-false-zero-empty-null-independent ()
  (let* ((day (workflow-history-view-test--day "2026-09-16"))
         (task (aref (plist-get day :minimumTasks) 0)))
    (setf (plist-get task :satisfied) :false)
    (setf (plist-get day :leaveRecords) (workflow-history-view-test--leave "2026-09-16"))
    (let ((payload (workflow-history-view-test--payload day)))
      (should (eq payload (org-workflow-history-view-validate payload)))
      (workflow-history-view-test--panel payload
        (dolist (text '("承诺履行：未满足" "习惯投入：0 分钟" "无习惯任务" "时段未指定"))
          (should (string-match-p text (buffer-string))))))
    (let* ((old (workflow-history-view-test--without day :habitFocusMinutes :habitCompleted :habitTasks :leaveRecords))
           (old-task (workflow-history-view-test--without task :satisfied)))
      (setf (plist-get old :minimumTasks) (vector old-task))
      (workflow-history-view-test--panel (workflow-history-view-test--payload old)
        (dolist (text '("承诺履行：未知（旧记录未追踪）" "习惯投入：未知（旧记录未追踪）"
                        "习惯完成：未知（旧记录未追踪）" "习惯任务：未知（旧记录未追踪）" "未提供请假记录"))
          (should (string-match-p (regexp-quote text) (buffer-string))))))))
(ert-deftest workflow-history-view-detail-independent-habit-fields ()
  (dolist (field '(:habitFocusMinutes :habitCompleted :habitTasks))
    (let* ((day (workflow-history-view-test--without (workflow-history-view-test--day "2026-09-16")
                                                  :habitFocusMinutes :habitCompleted :habitTasks))
           (day (plist-put day field (if (eq field :habitTasks) [] 0)))
           (payload (workflow-history-view-test--payload day)))
      (should (eq payload (org-workflow-history-view-validate payload)))
      (workflow-history-view-test--panel payload
        (should (string-match-p "旧记录未追踪" (buffer-string)))))))
(ert-deftest workflow-history-view-detail-zero-one-many-ordered-titles-outcomes ()
  (let* ((title (make-string 180 ?长)) (day (workflow-history-view-test--day "2026-09-16"))
         (tasks (vconcat (cl-loop for outcome in '("pending" "done" "ready" "held" "focused")
                                 collect (list :task title :outcome outcome :focusMinutes 0)))))
    (setf (plist-get day :minimumTasks) [] (plist-get day :optionalTasks) tasks
          (plist-get day :habitTasks) [(:task "一个习惯" :outcome "done" :focusMinutes 0)]
          (plist-get day :leaveRecords) [])
    (workflow-history-view-test--panel (workflow-history-view-test--payload day)
      (should (string-match-p "无承诺任务" (buffer-string)))
      (should (string-match-p "无请假记录" (buffer-string)))
      (should (string-match-p (regexp-quote title) (buffer-string)))
      (let ((last 0))
        (dolist (label '("待完成" "已完成" "已就绪" "已暂缓" "已投入"))
          (let ((pos (string-match (concat "任务状态：" label) (buffer-string) last)))
            (should pos) (setq last (1+ pos))))))))
(ert-deftest workflow-history-view-summary-finalized-only-and-all-missing ()
  (let* ((missing (workflow-history-view-test--day "2026-09-15" "missing"))
         (payload (workflow-history-view-test--payload missing (workflow-history-view-test--day "2026-09-16"))))
    (should (equal '(:total 30 :finalized 1 :missing 1 :streak 1) (org-workflow-history-view-summary payload)))
    (workflow-history-view-test--panel (workflow-history-view-test--payload missing)
      (should (string-match-p "累计投入 0 分钟" (buffer-string)))
      (should (string-match-p "已结算 0 天 · 缺失 1 天" (buffer-string)))
      (should-not (string-match-p "任务状态：" (buffer-string))))))
(ert-deftest workflow-history-view-summary-suffix-breaks ()
  (dolist (break '("missing" "unmet" "untouch"))
    (let ((payload (workflow-history-view-test--payload
                    (workflow-history-view-test--day "2026-09-13")
                    (workflow-history-view-test--day "2026-09-14" break)
                    (workflow-history-view-test--day "2026-09-15")
                    (workflow-history-view-test--day "2026-09-16"))))
      (should (= 2 (plist-get (org-workflow-history-view-summary payload) :streak)))))
  (should (= 0 (plist-get (org-workflow-history-view-summary
                          (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16" "untouch"))) :streak))))

(defun workflow-history-view-test--invalid (payload path)
  (let ((err (should-error (org-workflow-history-view-validate payload))))
    (should (eq 'org-workflow-history-view-invalid (car err)))
    (should (string-match-p (regexp-quote path) (error-message-string err)))
    (should (< (length (error-message-string err)) 200))
    (should-not (string-match-p "秘密标题" (error-message-string err)))))
(ert-deftest workflow-history-view-invalid-required-envelope ()
  (dolist (key '(:schema :schemaVersion :generatedAt :timezone :coverage :days))
    (workflow-history-view-test--invalid (workflow-history-view-test--without (workflow-history-view-test--payload) key)
                                        (substring (symbol-name key) 1)))
  (dolist (pair '((:schema . "wrong") (:schemaVersion . 2) (:generatedAt . "2026-02-30T00:00:00Z")
                  (:timezone . "") (:coverage . nil) (:days . nil)))
    (workflow-history-view-test--invalid (plist-put (workflow-history-view-test--payload) (car pair) (cdr pair))
                                        (substring (symbol-name (car pair)) 1))))
(ert-deftest workflow-history-view-invalid-calendar-sequence-and-timestamps ()
  (dolist (date '("2026-02-29" "2026-13-01" "2026-00-01" "2026-09-00" "no-date"))
    (workflow-history-view-test--invalid (workflow-history-view-test--payload (workflow-history-view-test--day date)) "coverage.trackingStarted"))
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-16"))))
    (dolist (stamp '("yesterday" "2026-09-16T24:00:00Z" "2026-09-16T12:60:00Z" "2026-09-16T12:00:00+24:00"))
      (workflow-history-view-test--invalid (plist-put (copy-tree payload t) :generatedAt stamp) "generatedAt"))
    (setf (plist-get (plist-get payload :coverage) :eligibleThrough) "2026-09-15")
    (workflow-history-view-test--invalid payload "coverage"))
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-14")
                                                     (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--invalid payload "days[1].date"))
  (workflow-history-view-test--invalid (plist-put (workflow-history-view-test--payload)
                                                 :days (vector (workflow-history-view-test--day "2026-09-16"))) "coverage"))
(ert-deftest workflow-history-view-invalid-day-required-fields ()
  (let ((base (workflow-history-view-test--day "2026-09-16")))
    (dolist (key '(:date :recordState :commitment :commitmentFocusMinutes :optionalFocusMinutes
                   :focusTotalMinutes :optionalCompleted :finalizedAt :minimumTasks :optionalTasks))
      (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--without base key))))
        ;; Keep coverage valid to exercise missing day fields directly.
        (setf (plist-get payload :coverage) '(:trackingStarted "2026-09-16" :eligibleThrough "2026-09-16"))
        (workflow-history-view-test--invalid payload (concat "days[0]." (substring (symbol-name key) 1)))))
    (dolist (pair '((:recordState . "other") (:commitment . "done") (:focusTotalMinutes . -1)
                    (:optionalCompleted . 1.5) (:minimumTasks . nil) (:habitFocusMinutes . :null)
                    (:habitCompleted . :false) (:habitTasks . :null) (:leaveRecords . nil)))
      (workflow-history-view-test--invalid
       (workflow-history-view-test--payload (plist-put (copy-tree base t) (car pair) (cdr pair)))
       (concat "days[0]." (substring (symbol-name (car pair)) 1))))))
(ert-deftest workflow-history-view-invalid-task-and-satisfied ()
  (dolist (pair '((:task . "") (:task . 42) (:outcome . "adjusted-done") (:focusMinutes . -1)
                  (:satisfied . nil) (:satisfied . :null) (:satisfied . "yes")))
    (let ((day (workflow-history-view-test--day "2026-09-16")))
      (setf (plist-get day :minimumTasks) (vector (plist-put (list :task "秘密标题" :outcome "pending" :focusMinutes 0)
                                                          (car pair) (cdr pair))))
      (workflow-history-view-test--invalid (workflow-history-view-test--payload day)
                                          (concat "days[0].minimumTasks[0]." (substring (symbol-name (car pair)) 1))))))
(ert-deftest workflow-history-view-invalid-leave-nesting ()
  (dolist (pair '((:id . "") (:date . "2026-09-15") (:slots . []) (:slots . ["night"])
                  (:slots . ["morning" "morning"]) (:reason . "") (:recordedAt . "bad") (:tasks . nil)))
    (let ((day (workflow-history-view-test--day "2026-09-16")))
      (setf (plist-get day :leaveRecords)
            (vector (plist-put (aref (workflow-history-view-test--leave "2026-09-16") 0) (car pair) (cdr pair))))
      (workflow-history-view-test--invalid (workflow-history-view-test--payload day)
                                          (concat "days[0].leaveRecords[0]." (substring (symbol-name (car pair)) 1)))))
  (dolist (pair '((:id . nil) (:slot . "evening") (:task . "")))
    (let ((day (workflow-history-view-test--day "2026-09-16"))
          (leave (aref (workflow-history-view-test--leave "2026-09-16") 0)))
      (setf (plist-get leave :tasks) (vector (plist-put (list :id :null :task "任务" :slot :null) (car pair) (cdr pair)))
            (plist-get day :leaveRecords) (vector leave))
      (workflow-history-view-test--invalid (workflow-history-view-test--payload day)
                                          (concat "days[0].leaveRecords[0].tasks[0]." (substring (symbol-name (car pair)) 1))))))
(ert-deftest workflow-history-view-detail-leave-many-order-and-literal-text ()
  (let* ((day (workflow-history-view-test--day "2026-09-16" "missing"))
         (a (aref (workflow-history-view-test--leave "2026-09-16") 0))
         (b (copy-tree a t)))
    (setf (plist-get b :id) "second" (plist-get b :reason) "原文 #.(error) [[link]] 第二条"
          (plist-get b :slots) ["afternoon" "evening"]
          (plist-get b :tasks) [(:id "id" :task "晚间任务" :slot "evening")]
          (plist-get day :leaveRecords) (vector a b))
    (workflow-history-view-test--panel (workflow-history-view-test--payload day)
      (let ((text (buffer-string)))
        (should (< (string-match "理由：休息原文" text)
                   (string-match (regexp-quote "理由：原文 #.(error) [[link]] 第二条") text)))
        (should (string-match-p "请假 · 下午、晚间" text))
        (should (string-match-p "关联任务：晚间任务（晚间）" text))))))
(ert-deftest workflow-history-view-valid-leap-day-extension-and-unchanged-totals ()
  (let* ((day (workflow-history-view-test--day "2024-02-29"))
         (task (aref (plist-get day :minimumTasks) 0)))
    (setf (plist-get day :focusTotalMinutes) 99 (plist-get task :futureField) "extension")
    (let* ((payload (workflow-history-view-test--payload day)) (before (copy-tree payload t)))
      (should (eq payload (org-workflow-history-view-validate payload)))
      (should (= 99 (plist-get (org-workflow-history-view-summary payload) :total)))
      (should (equal before payload)))))
(ert-deftest workflow-history-view-invalid-object-shapes-and-duplicate-leaves ()
  (dolist (value '(42 "private" (:schema "org-workflow-history" :schemaVersion) (:schema 1 :schema 2)))
    (workflow-history-view-test--invalid value "历史数据不合法"))
  (let ((day (workflow-history-view-test--day "2026-09-16"))
        (leave (aref (workflow-history-view-test--leave "2026-09-16") 0)))
    (setf (plist-get day :leaveRecords) (vector leave (copy-tree leave t)))
    (workflow-history-view-test--invalid (workflow-history-view-test--payload day) "days[0].leaveRecords[1].id"))
  (let ((day (plist-put (workflow-history-view-test--day "2026-09-16" "missing") :habitTasks :null)))
    (workflow-history-view-test--invalid (workflow-history-view-test--payload day) "days[0].habitTasks")))
(ert-deftest workflow-history-view-detail-task-categories-zero-one-many ()
  (dolist (field '(:minimumTasks :optionalTasks :habitTasks))
    (dolist (count '(0 1 3))
      (let ((day (workflow-history-view-test--day "2026-09-16")))
        (setf (plist-get day field)
              (vconcat (cl-loop for index below count collect
                                (list :task (format "独立列表行%d" index) :outcome "ready" :focusMinutes index))))
        (workflow-history-view-test--panel (workflow-history-view-test--payload day)
          (let ((text (buffer-string)))
            (cl-loop for index below count do
                     (should (string-match-p (format "独立列表行%d" index) text)))
            (when (= count 0)
              (should (string-match-p (pcase field (:minimumTasks "无承诺任务")
                                            (:optionalTasks "无可选任务") (:habitTasks "无习惯任务")) text)))))))))
(ert-deftest workflow-history-panel-select-one-complete-root-update ()
  (let ((payload (workflow-history-view-test--payload (workflow-history-view-test--day "2026-09-15" "missing")
                                                    (workflow-history-view-test--day "2026-09-16"))))
    (workflow-history-view-test--panel payload
      (let ((updates 0) (original (symbol-function 'vui-update)))
        (cl-letf (((symbol-function 'vui-update)
                   (lambda (instance props)
                     (cl-incf updates)
                     (let ((model (plist-get props :model)))
                       (should (equal "2026-09-15" (plist-get model :selected-date)))
                       (should (equal "2026-09-15" (plist-get (plist-get model :detail) :date))))
                     (funcall original instance props))))
          (workflow-history-test--no-writes (org-workflow-history-panel-select-date "2026-09-15")))
        (should (= 1 updates))))))
(provide 'org-workflow-history-view-test)
