;;; org-workflow-agenda-workbench-test.el --- Sprint workbench regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'org-workflow-agenda)
(require 'org-workflow-core)

(defmacro org-workflow-workbench-test-with-files (contents &rest body)
  (declare (indent 1))
  `(let ((files nil)
         (before-buffers (buffer-list))
         (org-agenda-buffer-name (generate-new-buffer-name "*Sprint test*"))
         (org-agenda-window-setup 'current-window)
         (org-workflow-agenda-plan-tomorrow nil)
         (org-workflow-agenda-selected-group nil)
         (org-workflow-agenda-planning-all nil)
         (org-workflow-agenda-future-expanded t)
         (org-workflow-agenda-columns-enabled nil))
     (unwind-protect
         (save-window-excursion
           (dolist (content ,contents)
             (push (make-temp-file "workbench-" nil ".org" content) files))
           (setq files (nreverse files))
           (let ((org-agenda-files files))
             (cl-letf (((symbol-function 'org-workflow-target--today-string)
                        (lambda () "2026-08-17"))
                       ((symbol-function 'current-time)
                        (lambda () (encode-time 0 0 20 17 8 2026)))
                       ((symbol-function 'org-workflow-collection-inbox--review-files)
                        (lambda (&rest _) nil))
                       ((symbol-function 'org-workflow-habits--map) #'ignore))
               ,@body)))
       (dolist (buffer (seq-difference (buffer-list) before-buffers))
         (when (buffer-live-p buffer)
           (with-current-buffer buffer (set-buffer-modified-p nil))
           (kill-buffer buffer)))
       (mapc #'delete-file files))))

(defconst org-workflow-workbench-test-source
  "#+filetags: :project:\n#+CATEGORY: Work\n#+TODO: TODO READY | DONE HOLD\n* Stage\n** DIVE Group\n*** TODO First :@deep:\n*** TODO Second :@flow:\n*** TODO Overdue\nSCHEDULED: <2026-08-15 Sat>\n*** TODO Today\nSCHEDULED: <2026-08-17 Mon>\n*** TODO Tomorrow\nSCHEDULED: <2026-08-18 Tue>\n*** TODO Later\nSCHEDULED: <2026-08-19 Wed>\n** DIVE Other\n*** TODO Third\n")

(defun org-workflow-workbench-test-open ()
  (org-agenda nil "d")
  (get-buffer org-agenda-buffer-name))

(defun org-workflow-workbench-test-titles (&optional buffer)
  "Read task identities from native row markers, ignoring headings."
  (with-current-buffer (or buffer (current-buffer))
    (save-excursion
      (goto-char (point-min))
      (let (titles)
        (while (< (point) (point-max))
          (when-let* ((marker (org-get-at-bol 'org-hd-marker)))
            (should (marker-buffer marker))
            (push (org-with-point-at marker (org-get-heading t t t t)) titles))
          (forward-line))
        (nreverse titles)))))

(defun org-workflow-workbench-test-panes ()
  "Create the native companion, also in batch where auto layout is disabled."
  (when-let* ((primary (and org-workflow-agenda--workbench
                            (org-workflow-agenda-workbench-primary org-workflow-agenda--workbench)))
              (window (get-buffer-window primary)))
    (select-window window))
  (delete-other-windows)
  (org-workflow-agenda--set-setting 'org-workflow-agenda-columns-enabled t)
  (let ((org-workflow-agenda-column-min-width 20)) (org-workflow-agenda--apply-columns))
  (let ((state org-workflow-agenda--workbench))
    (list (org-workflow-agenda-workbench-primary state)
          (org-workflow-agenda-workbench-candidates state))))

(ert-deftest org-workflow-workbench-candidates-source-order-and-ancestor-identity ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Work\n* DIVE Stage\n** Same\n*** DIVE Branch\n**** TODO Zed\n**** TODO Alpha\n** DIVE Same\n*** TODO Other\n** TODO Direct\n")
    (let* ((rows (org-workflow-agenda--candidate-entries))
           (ids (mapcar #'cadr rows)))
     (should (equal '("Zed" "Alpha" "Other" "Direct")
                    (mapcar (lambda (row) (org-workflow-target-entry-title (car row))) rows)))
     (should (equal (car ids) (cadr ids)))
     (should (equal (car ids) (nth 2 ids)))
     (should (equal "Stage" (nth 2 (car rows))))
     (should (equal "Stage" (nth 2 (nth 3 rows)))))))

(ert-deftest org-workflow-workbench-candidate-scope-excludes-held-done-and-parents ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :area:\n#+TODO: TODO READY | DONE HOLD\n* DIVE Current\n** TODO Live\n** TODO Parent\n*** DONE Child\n** READY Ready\n** HOLD Held\n*** TODO Hidden\n** TODO Scheduled\nSCHEDULED: <2026-08-18 Tue>\n* Inactive\n** TODO Backlog\n"
        "* DIVE Unscoped\n** TODO Outside\n")
    (should (equal '("Live") (mapcar (lambda (r) (org-workflow-target-entry-title (car r)))
                                     (org-workflow-agenda--candidate-entries))))
    (let ((org-workflow-agenda-planning-all t))
      (should (equal '("Live" "Backlog")
                     (mapcar (lambda (r) (org-workflow-target-entry-title (car r)))
                             (org-workflow-agenda--candidate-entries)))))))

(ert-deftest org-workflow-workbench-same-title-tabs-across-files-retain-source-order ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Work\n* Stage\n** DIVE Same\n*** TODO First file\n"
        "#+filetags: :project:\n#+CATEGORY: Work\n* Stage\n** DIVE Same\n*** TODO Second file\n")
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
      (set-buffer candidate))
    (should (equal '("First file" "Second file") (org-workflow-workbench-test-titles)))
   (let ((rows (org-workflow-agenda--candidate-entries)))
     (should-not (equal (cadar rows) (cadr (cadr rows)))))
   (dolist (file files)
     (should (seq-some (lambda (tab)
                         (string-match-p (regexp-quote (file-name-nondirectory file))
                                         (alist-get 'name tab)))
                       (org-workflow-agenda-candidate-tabs))))))

(ert-deftest org-workflow-workbench-tabs-preserve-schedule-and-source ()
  (org-workflow-workbench-test-with-files
   (list org-workflow-workbench-test-source "#+filetags: :project:\n#+CATEGORY: OtherProject\n* DIVE Stage\n** TODO Other project task\n")
   (org-workflow-workbench-test-open)
   (pcase-let* ((`(,primary ,candidate) (org-workflow-workbench-test-panes))
                (schedule (with-current-buffer primary (buffer-string)))
                (source (with-current-buffer (find-file-noselect (car files)) (buffer-string))))
     (with-current-buffer candidate
       (should (eq tab-line-tabs-function #'org-workflow-agenda-candidate-tabs))
       (funcall (alist-get 'select (car (last (org-workflow-agenda-candidate-tabs)))))
       (should (equal '("Other project task") (org-workflow-workbench-test-titles))))
     (should (equal schedule (with-current-buffer primary (buffer-string))))
     (should (equal source (with-current-buffer (find-file-noselect (car files)) (buffer-string)))))))

(ert-deftest org-workflow-workbench-day-view-exact-tomorrow-and-no-future-duplicate ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (let ((source (with-current-buffer (find-file-noselect (car files)) (buffer-string)))
          (execution (mapcar #'org-workflow-target-entry-title (org-workflow-target--ordered-entries)))
          (org-workflow-target-stack (list 'execution-cache-sentinel))
          (org-workflow-target-selected-date "2026-08-17"))
      (should (member "Overdue" (org-workflow-workbench-test-titles)))
      (org-workflow-agenda-set-day t)
      (let ((titles (org-workflow-workbench-test-titles)))
        (should-not (member "Overdue" titles))
        (should-not (member "Today" titles))
        (should (= 1 (seq-count (lambda (title) (equal title "Tomorrow")) titles)))
        (should-not (member "Later" titles)))
      (should (equal execution (mapcar #'org-workflow-target-entry-title (org-workflow-target--ordered-entries))))
      (should (equal '(execution-cache-sentinel) org-workflow-target-stack))
      (should (equal "2026-08-17" org-workflow-target-selected-date))
      (should (equal source (with-current-buffer (find-file-noselect (car files)) (buffer-string)))))))

(ert-deftest org-workflow-workbench-completed-bands-use-valid-scoped-inherited-priority ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :area:\n#+TODO: TODO READY | DONE HOLD\n* [#A] Area\n** Group\n*** DONE Finished\nCLOSED: [2026-08-17 Mon 10:00] SCHEDULED: <2026-08-16 Sun>\n*** DONE [#B] Future\nCLOSED: [2026-08-17 Mon 10:00] SCHEDULED: <2026-08-18 Tue>\n*** DONE [#B] No schedule\nCLOSED: [2026-08-17 Mon 10:00]\n*** DONE [#B] Yesterday\nCLOSED: [2026-08-16 Sun 10:00] SCHEDULED: <2026-08-16 Sun>\n** HOLD [#C] Hold\n*** DONE Hidden\nCLOSED: [2026-08-17 Mon 10:00] SCHEDULED: <2026-08-16 Sun>\n** DONE [#C] Parent\nCLOSED: [2026-08-17 Mon 10:00] SCHEDULED: <2026-08-16 Sun>\n*** TODO Child\n"
        "* Area\n** DONE [#C] Outside\nCLOSED: [2026-08-17 Mon 10:00] SCHEDULED: <2026-08-16 Sun>\n")
    (should (equal '(?A) (org-workflow-agenda--completed-periods "2026-08-17")))
    (with-temp-buffer
      (org-workflow-agenda-task-stack nil)
      (should (= 1 (how-many "已完成" (point-min) (point-max))))
      (should (= 2 (how-many "暂无安排" (point-min) (point-max)))))))

(ert-deftest org-workflow-workbench-day-switch-syncs-command-date-and-empty-context ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate (org-workflow-agenda-set-day t))
      (dolist (buffer (list primary candidate))
        (with-current-buffer buffer
          (should (equal "2026-08-18" (org-workflow-agenda-target-date)))
          (dolist (command '(org-workflow-agenda-plan-morning org-workflow-agenda-plan-afternoon org-workflow-agenda-plan-evening))
            (let (date period)
              (cl-letf (((symbol-function 'org-workflow-agenda--apply-planning) #'funcall)
                        ((symbol-function 'org-agenda-priority) (lambda (p) (setq period p)))
                        ((symbol-function 'org-agenda-schedule) (lambda (_ d) (setq date d))))
                (funcall command))
              (should (equal "2026-08-18" date))
              (should (memq period '(?A ?B ?C)))))))
      (with-current-buffer primary
        (goto-char (point-min))
        (search-forward "暂无安排")
        (beginning-of-line)
        (let (created)
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "New task"))
                    ((symbol-function 'org-workflow-agenda-create-task)
                     (lambda (title date period) (setq created (list title date period)))))
            (org-workflow-agenda-create-at-point))
          (should (equal '("New task" "2026-08-18" ?A) created)))))))

(ert-deftest org-workflow-workbench-native-refresh-keeps-markers-and-bulk-local ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (goto-char (point-min)) (search-forward "First") (beginning-of-line)
        (org-agenda-bulk-mark)
        (should (= 1 (length org-agenda-bulk-marked-entries))))
      (with-current-buffer primary (should-not org-agenda-bulk-marked-entries))
      (with-current-buffer candidate
        (org-agenda-bulk-unmark-all)
        (goto-char (point-min)) (search-forward "First") (beginning-of-line)
        (org-agenda-schedule nil "2026-08-17")
        (org-agenda-redo)
        (should-not (member "First" (org-workflow-workbench-test-titles))))
      (should (member "First" (org-workflow-workbench-test-titles primary)))
      (with-current-buffer primary (org-agenda-redo))
      (should (member "Second" (org-workflow-workbench-test-titles candidate)))
      (should (member "First" (org-workflow-workbench-test-titles primary))))))

(ert-deftest org-workflow-workbench-native-period-planning-keeps-candidate-alive ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (let ((org-workflow-store-enabled nil))
        (with-current-buffer candidate
          (org-workflow-agenda-set-day t)
          (goto-char (point-min)) (search-forward "First") (beginning-of-line)
          (org-workflow-agenda-plan-morning)))
      (should (buffer-live-p candidate))
      (should (buffer-live-p primary))
      (should (eq 'candidates (buffer-local-value 'org-workflow-agenda--pane-role candidate)))
      (should-not (member "First" (org-workflow-workbench-test-titles candidate)))
      (should (member "Second" (org-workflow-workbench-test-titles candidate)))
      (should (member "First" (org-workflow-workbench-test-titles primary)))
      (with-current-buffer (find-file-noselect (car files))
        (goto-char (point-min)) (search-forward "First") (org-back-to-heading)
        (should (= ?A (nth 3 (org-heading-components))))
        (should (equal "2026-08-18"
                       (org-workflow-target--timestamp-date (org-entry-get nil "SCHEDULED"))))))))

(ert-deftest org-workflow-workbench-native-plan-undo-refreshes-both-panes ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let* ((directory (make-temp-file "workbench-undo-" t))
           (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
           (org-workflow-store--connection nil)
           (org-workflow-store--path nil)
           (org-workflow-store-enabled t)
           (org-id-locations-file (expand-file-name "ids" directory))
           (org-id-locations (make-hash-table :test #'equal))
           (org-id-files nil)
           (org-workflow-agenda-last-plan nil)
           (org-workflow-executing-marker nil)
           (org-workflow-target-selected-marker nil)
           (org-workflow-current-changed-hook nil))
      (unwind-protect
          (progn
            (org-workflow-workbench-test-open)
            (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
              (with-current-buffer candidate
                (org-workflow-agenda-set-day t)
                (goto-char (point-min)) (search-forward "First") (beginning-of-line)
                (org-workflow-agenda-plan-morning)
                (should org-workflow-agenda-last-plan)
                (org-workflow-agenda-undo-plan))
              (should (buffer-live-p primary))
              (should (buffer-live-p candidate))
              (should-not org-workflow-agenda-last-plan)
              (should (member "First" (org-workflow-workbench-test-titles candidate)))
              (should-not (member "First" (org-workflow-workbench-test-titles primary)))
              (with-current-buffer (find-file-noselect (car files))
                (goto-char (point-min)) (search-forward "First") (org-back-to-heading)
                (should-not (nth 3 (org-heading-components)))
                (should-not (org-entry-get nil "SCHEDULED")))))
        (when (and org-workflow-store--connection
                   (org-workflow-store--live-p org-workflow-store--connection))
          (sqlite-close org-workflow-store--connection))
        (delete-directory directory t)))))

(ert-deftest org-workflow-workbench-window-geometry-collapse-and-unrelated-pane ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (delete-other-windows)
    (let* ((primary (current-buffer))
                                           (other (split-window-below))
                                           (unrelated (get-buffer-create "*Workbench unrelated*")))
                                      (set-window-buffer other unrelated)
                                      (org-workflow-agenda--set-setting 'org-workflow-agenda-columns-enabled t)
                                      (let ((org-workflow-agenda-column-min-width 20)) (org-workflow-agenda--apply-columns))
                                      (let* ((state org-workflow-agenda--workbench)
                                             (left (org-workflow-agenda-workbench-window state))
                                             (right (get-buffer-window primary)))
                                        (should (window-live-p left))
                                        (should (> (car (window-edges left)) (car (window-edges right))))
                                        (should (eq unrelated (window-buffer other)))
                                        (org-workflow-agenda-toggle-columns)
                                        (should-not (window-live-p left))
        (should (eq 'combined org-workflow-agenda--pane-role))
        (let ((org-workflow-agenda-column-min-width 20)) (org-workflow-agenda-toggle-columns))
        (should (window-live-p (org-workflow-agenda-workbench-window state)))
        (should (eq unrelated (window-buffer other)))))))

(ert-deftest org-workflow-workbench-settings-independent-of-other-agendas ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (let* ((first (org-workflow-workbench-test-open))
           (org-agenda-buffer-name (generate-new-buffer-name "*Second Sprint*"))
           (second (org-workflow-workbench-test-open)))
      (with-current-buffer first (org-workflow-agenda-set-day t))
      (with-current-buffer second
        (should-not (org-workflow-agenda--setting 'org-workflow-agenda-plan-tomorrow))
        (should (equal "2026-08-17" (org-workflow-agenda-target-date))))
      (let ((org-agenda-buffer-name (generate-new-buffer-name "*Ordinary Agenda*")))
        (org-agenda-list nil "2026-08-17" 1)
                                        (should-not org-workflow-agenda--workbench)
                                        (should-not org-workflow-agenda--sprint-buffer-p)))))

(ert-deftest org-workflow-workbench-resize-never-switches-layout ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
                                    (org-workflow-workbench-test-open)
                                    (org-workflow-workbench-test-panes)
                                    (let* ((state org-workflow-agenda--workbench)
                                           (companion (org-workflow-agenda-workbench-candidates state)))
                                      (org-workflow-agenda--columns-resize (selected-frame))
                                      (should (eq 'schedule org-workflow-agenda--pane-role))
                                      (should (eq companion (org-workflow-agenda-workbench-candidates state)))
                                      (org-workflow-agenda-toggle-columns)
                                      (org-workflow-agenda--columns-resize (selected-frame))
                                      (should (eq 'combined org-workflow-agenda--pane-role))
                                      (should-not (org-workflow-agenda-workbench-window state)))))

(ert-deftest org-workflow-workbench-quit-from-companion-restores-original-windows ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (delete-other-windows)
    (let ((original (get-buffer-create "*Workbench original*")))
      (switch-to-buffer original)
      (org-workflow-workbench-test-open)
      (pcase-let* ((`(,primary ,candidate) (org-workflow-workbench-test-panes))
                   (window (get-buffer-window candidate)))
        (select-window window)
        (org-agenda-quit)
        (should (= 1 (length (window-list))))
        (should (eq original (window-buffer (selected-window))))
        (should-not (buffer-live-p primary))
        (should-not (buffer-live-p candidate))))))

(ert-deftest org-workflow-workbench-journal-entry-quit-restores-original-windows ()
  (require 'vulpea-journal)
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (delete-other-windows)
    (let* ((journal (find-file-noselect (car files)))
           (journal-window (selected-window))
           (unrelated (get-buffer-create "*Journal unrelated*"))
           (other-window (split-window-below))
           (org-workflow-store-enabled nil)
           (org-workflow-collection--opening-sprint nil)
           (note (make-vulpea-note :path (car files))))
      (set-window-buffer other-window unrelated)
      (switch-to-buffer journal)
      (let ((noninteractive nil))
        (cl-letf (((symbol-function 'vulpea-journal-find-note) (lambda (&rest _) note))
                  ((symbol-function 'vulpea-journal-active-date)
                   (lambda () (encode-time 0 0 20 17 8 2026))))
          (org-workflow-collection-show-sprint)))
      (should (eq journal-window (selected-window)))
      (should (eq journal (current-buffer)))
      (should (= 3 (length (window-list))))
      (let* ((sprint (get-buffer "*日记 Sprint*"))
             (sprint-window (get-buffer-window sprint)))
        (should (buffer-live-p sprint))
        (with-current-buffer sprint
          (should (eq 'combined org-workflow-agenda--pane-role))
          (should-not (org-workflow-agenda--setting 'org-workflow-agenda-columns-enabled)))
        (select-window sprint-window)
        (org-agenda-quit)
        (should-not (buffer-live-p sprint)))
      (should (= 2 (length (window-list))))
      (should (eq journal-window (selected-window)))
      (should (eq journal (window-buffer journal-window)))
      (should (eq unrelated (window-buffer other-window))))))

(ert-deftest org-workflow-workbench-redo-restores-task-and-group-anchor ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (let ((id (cadr (car (org-workflow-agenda--candidate-entries)))))
          (org-workflow-agenda--set-setting 'org-workflow-agenda-selected-group id)
          (org-agenda-redo)
          (goto-char (point-min)) (search-forward "Second") (beginning-of-line)
          (let* ((window (get-buffer-window candidate))
                 (marker (copy-marker (org-get-at-bol 'org-hd-marker))))
            (set-window-start window (point) t)
            (set-window-point window (point))
            (org-agenda-redo)
            (should (equal id (org-workflow-agenda--setting 'org-workflow-agenda-selected-group)))
            (should (equal marker (org-get-at-bol 'org-hd-marker)))
                                            (should (equal marker (get-text-property (window-start window) 'org-hd-marker)))
                                            (set-marker marker nil)))))))

(ert-deftest org-workflow-workbench-explicit-tab-restores-original-workspace ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
                                    (delete-other-windows)
                                    (let* ((original (get-buffer-create "*Workbench original workspace*"))
                                           (unrelated (get-buffer-create "*Workbench unrelated workspace*"))
                                           (count (length (funcall tab-bar-tabs-function)))
                                           state)
                                      (switch-to-buffer original)
                                      (set-window-buffer (split-window-below) unrelated)
                                      (unwind-protect
                                          (progn
                                            (org-workflow-agenda-open-workbench)
                                            (setq state org-workflow-agenda--workbench)
                                            (should (= (1+ count) (length (funcall tab-bar-tabs-function))))
                                            (let* ((primary (org-workflow-agenda-workbench-primary state))
                                                   (candidate (org-workflow-agenda-workbench-candidates state))
                                                   (left (get-buffer-window primary))
                                                   (right (get-buffer-window candidate)))
                                              (should (< (car (window-edges left)) (car (window-edges right))))
                                              (with-current-buffer candidate
                                                (should tab-line-mode)
                                                (should (eq tab-line-tabs-function #'org-workflow-agenda-candidate-tabs)))
                                              (select-window right)
                                              (org-agenda-quit)
                                              (should-not (buffer-live-p primary))
                                              (should-not (buffer-live-p candidate)))
                                            (should (= count (length (funcall tab-bar-tabs-function))))
                                            (should (= 2 (length (window-list))))
                                            (should (eq original (window-buffer (selected-window))))
                                            (should (get-buffer-window unrelated)))
                                        (when (alist-get 'org-workflow-agenda-workbench (tab-bar--current-tab-find))
                                          (tab-bar-close-tab))))))

(ert-deftest org-workflow-workbench-close-tab-cleans-only-its-own-buffers ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
                                    (let ((original (current-buffer)))
                                      (org-workflow-agenda-open-workbench)
                                      (let ((buffers (org-workflow-agenda--workbench-buffers)))
                                        (tab-bar-close-tab)
                                        (should (buffer-live-p original))
                                        (dolist (buffer buffers) (should-not (buffer-live-p buffer)))))))

(ert-deftest org-workflow-workbench-group-face-keeps-original-size-and-weight ()
  (should (eq (face-attribute 'org-workflow-agenda-group :weight nil t) 'regular))
  (should (= (face-attribute 'org-workflow-agenda-group :height nil t) 0.95)))

(ert-deftest org-workflow-workbench-project-tabs-cycle-with-native-commands ()
  (org-workflow-workbench-test-with-files
      (list org-workflow-workbench-test-source
            "#+filetags: :project:\n#+CATEGORY: Other\n* DIVE Stage\n** TODO Other task\n")
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (let ((schedule (with-current-buffer primary (buffer-string))))
        (select-window (get-buffer-window candidate))
        (tab-line-switch-to-next-tab)
        (should (equal '("First" "Second" "Third") (org-workflow-workbench-test-titles)))
        (tab-line-switch-to-next-tab)
        (should (equal '("Other task") (org-workflow-workbench-test-titles)))
        (tab-line-switch-to-next-tab)
        (should (= 4 (length (org-workflow-workbench-test-titles))))
        (tab-line-switch-to-prev-tab)
        (should (equal '("Other task") (org-workflow-workbench-test-titles)))
        (tab-line-switch-to-next-tab nil 2)
        (should (equal '("First" "Second" "Third") (org-workflow-workbench-test-titles)))
        (let ((tab-line-switch-cycling nil))
          (tab-line-switch-to-prev-tab nil 10)
          (should (= 4 (length (org-workflow-workbench-test-titles)))))
        (should (equal schedule (with-current-buffer primary (buffer-string))))))))

(ert-deftest org-workflow-workbench-tab-cycle-leaves-ordinary-tab-line-alone ()
  (let ((tab-line-tabs-function #'tab-line-tabs-fixed-window-buffers) called)
    (org-workflow-agenda--next-project-tab
     (lambda (event arg) (setq called (list event arg))) nil 3)
    (should (equal '(nil 3) called))))

(ert-deftest org-workflow-workbench-agenda-dispatch-and-left-tab-line ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (unwind-protect
        (progn
          (org-agenda nil "s")
          (should (eq org-workflow-agenda--pane-role 'schedule))
          (should (local-variable-p 'tab-line-format))
          (should-not tab-line-format)
          (org-workflow-agenda-set-day t)
          (should (string-match-p "明日安排" (buffer-string)))
          (should-not tab-line-format)
          (let* ((state org-workflow-agenda--workbench)
                 (candidate (org-workflow-agenda-workbench-candidates state)))
            (select-window (get-buffer-window candidate))
            (goto-char (point-min)) (search-forward "First") (beginning-of-line)
            (let ((org-workflow-store-enabled nil)) (org-workflow-agenda-plan-morning))
            (should (member "First" (org-workflow-workbench-test-titles
                                     (org-workflow-agenda-workbench-primary state)))))
          (org-agenda-quit))
      (when (alist-get 'org-workflow-agenda-workbench (tab-bar--current-tab-find))
        (tab-bar-close-tab)))))

(ert-deftest org-workflow-workbench-cleans-only-abandoned-menu-side-windows ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((original (selected-window))
           (other (split-window-below))
           (edit (get-buffer-create "*Workbench preserved edit*"))
           (menu (get-buffer-create " *Old buffer  *transient**"))
           (side (display-buffer-in-side-window menu '((side . bottom)))))
      (unwind-protect
          (progn
            (set-window-buffer other edit)
            (org-workflow-agenda--clean-menu-windows)
            (should-not (window-live-p side))
            (should (window-live-p original))
            (should (eq edit (window-buffer other))))
        (kill-buffer edit)
        (kill-buffer menu)))))

(ert-deftest org-workflow-workbench-menu-entry-exits-before-switching-tab ()
  (let ((spec (cdr (transient-get-suffix 'org-workflow-agenda-view-menu "c"))))
    (should (plist-member spec :transient))
    (should-not (plist-get spec :transient))))

(ert-deftest org-workflow-workbench-tabs-group-by-level-one-heading ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Course\n* First project\n** DIVE Chapter\n*** TODO One\n* Second project\n** DIVE Chapter\n*** TODO Two\n")
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,_primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate
        (let ((tabs (org-workflow-agenda-candidate-tabs)))
          (should (equal '("全部" "First project" "Second project")
                         (mapcar (lambda (tab) (alist-get 'name tab)) tabs)))
          (funcall (alist-get 'select (nth 2 tabs)))
          (should (equal '("Two") (org-workflow-workbench-test-titles))))))))

(ert-deftest org-workflow-workbench-parent-first-quiet-ancestors-and-modern-progress ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Course\n* Root\n** Topic\n*** DIVE Parent [2/11]\n**** TODO Candidate\n**** TODO [#A] Planned\nSCHEDULED: <2026-08-17 Mon>\n")
    (org-workflow-workbench-test-open)
    (goto-char (point-min))
    (search-forward "Parent [2/11]  Course / Root / Topic")
    (let ((start (- (point) (length "Parent [2/11]  Course / Root / Topic"))))
      (should (eq 'org-workflow-agenda-group (get-text-property start 'face)))
      (should (eq 'org-workflow-agenda-ancestor (get-text-property (+ start 15) 'face)))
      (should (get-text-property (+ start 7) 'display))
      (should (eq 'org-modern-label (get-text-property (+ start 7) 'face))))))

(ert-deftest org-workflow-workbench-filters-both-panes-and-retains-on-redo ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Course\n* Root\n** DIVE Parent\n*** TODO Candidate tiny :@tiny:\n*** TODO Candidate deep :@deep:\n*** TODO [#A] Planned tiny :@tiny:\nSCHEDULED: <2026-08-17 Mon>\n*** TODO [#A] Planned deep :@deep:\nSCHEDULED: <2026-08-17 Mon>\n")
    (org-workflow-workbench-test-open)
    (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
      (with-current-buffer candidate (org-workflow-agenda-filter-tiny))
      (dolist (buffer (list primary candidate))
        (with-current-buffer buffer
          (should (equal '("+@tiny") org-agenda-tag-filter))
          (goto-char (point-min)) (search-forward "deep") (beginning-of-line)
          (should (invisible-p (point)))
          (goto-char (point-min)) (search-forward "tiny") (beginning-of-line)
          (should-not (invisible-p (point)))))
      (with-current-buffer candidate
        (funcall (alist-get 'select (nth 1 (org-workflow-agenda-candidate-tabs)))))
      (dolist (buffer (list primary candidate))
        (with-current-buffer buffer
          (should (equal '("+@tiny") org-agenda-tag-filter))
          (goto-char (point-min)) (search-forward "deep") (beginning-of-line)
          (should (invisible-p (point)))))
      (with-current-buffer primary (org-workflow-agenda-filter-clear))
      (dolist (buffer (list primary candidate))
        (with-current-buffer buffer
          (should-not org-agenda-tag-filter)
          (goto-char (point-min)) (search-forward "deep") (beginning-of-line)
          (should-not (invisible-p (point))))))))

(ert-deftest org-workflow-workbench-view-menu-filter-keys-are-lowercase ()
  (dolist (binding '(("t" . org-workflow-agenda-filter-tiny)
                     ("f" . org-workflow-agenda-filter-flow)
                     ("d" . org-workflow-agenda-filter-deep)
                     ("p" . org-workflow-agenda-filter-promise)))
    (should (eq (plist-get (cdr (transient-get-suffix 'org-workflow-agenda-view-menu (car binding))) :command)
                (cdr binding)))))

(ert-deftest org-workflow-workbench-quiet-display-keeps-native-data ()
  (org-workflow-workbench-test-with-files
      '("#+filetags: :project:\n#+CATEGORY: Course\n* Root :CURR:\n** Parent\n*** TODO [#A] Late :promise:\nSCHEDULED: <2026-08-15 Sat>\n:PROPERTIES:\n:WORKFLOW_DEFER_COUNT: 2\n:END:\n")
    (org-workflow-workbench-test-open)
    (should (equal "" (org-workflow-agenda--period-load nil)))
    (should-not (string-match-p "今日安排 ·\\|项未估\\|未估时" (buffer-string)))
    (goto-char (point-min)) (search-forward "Late")
    (beginning-of-line)
    (should (string-prefix-p "    ◇ Late" (thing-at-point 'line t)))
    (should (org-get-at-bol 'org-hd-marker))
    (should-not (string-match-p "原定\\|已延期" (buffer-string)))
    (org-agenda-redo)
    (should-not (string-match-p "原定\\|已延期" (buffer-string)))))

(ert-deftest org-workflow-workbench-right-details-wrap-without-changing-rows ()
  (org-workflow-workbench-test-with-files (list org-workflow-workbench-test-source)
    (org-workflow-workbench-test-open)
    (let ((before (buffer-string))
          (titles (org-workflow-workbench-test-titles)))
      (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 12)))
        (org-workflow-agenda--align-right-details (selected-window)))
      (should (equal titles (org-workflow-workbench-test-titles)))
      (should (equal (substring-no-properties before)
                     (buffer-substring-no-properties (point-min) (point-max))))
      (goto-char (point-min))
      (let ((spacer (text-property-any (point-min) (point-max) 'org-workflow-agenda-right-spacer t)))
        (should spacer)
        (should (equal "\n" (get-text-property spacer 'display)))
        (should (eq 'space (car (get-text-property (1+ spacer) 'display))))))))

(provide 'org-workflow-agenda-workbench-test)
;;; org-workflow-agenda-workbench-test.el ends here
