;;; org-workflow-agenda-agenda-inbox-test.el --- Unified Sprint collection tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'org-workflow-agenda-mouse-test
         (expand-file-name "org-workflow-agenda-mouse-test.el"
                           (file-name-directory (or load-file-name buffer-file-name))))

(defconst org-workflow-agenda-inbox-test-source
  "#+filetags: :area:\n#+TODO: TODO READY | DONE HOLD\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2020-01-06\n:END:\n** TODO Old note :@tiny:\n:PROPERTIES:\n:CAPTURED_ON: 2020-01-07\n:END:\nKeep the original body.\n** TODO Current idea :@deep:\n:PROPERTIES:\n:CAPTURED_ON: 2026-08-17\n:END:\n** TODO [#A] Already arranged\nSCHEDULED: <2026-08-17 Mon>\n** TODO Future arranged\nSCHEDULED: <2026-08-19 Wed>\n** DONE Finished\n** HOLD Deferred\n** TODO Parent collection\n*** TODO Nested detail\n* Outside\n** TODO Not collected\n")

(defmacro org-workflow-agenda-inbox-test-with-files (contents &rest body)
  (declare (indent 1))
  `(org-workflow-workbench-test-with-files ,contents
				     (let ((org-workflow-store-enabled nil))
				       (cl-letf (((symbol-function 'org-workflow-collection-inbox--review-files)
						  (lambda () (list (car files)))))
						,@body))))

(ert-deftest org-workflow-agenda-inbox-single-and-double-have-distinct-sections ()
  (org-workflow-agenda-inbox-test-with-files (list org-workflow-agenda-inbox-test-source)
				       (org-workflow-workbench-test-open)
				       (should (string-match-p "收集箱" (buffer-string)))
				       (should-not (string-match-p "待安排\\|未来 7 天" (buffer-string)))
				       (should (equal '("Already arranged" "Parent collection" "Old note" "Current idea")
						      (org-workflow-workbench-test-titles)))
				       (let ((marker (my/org-mouse-test-row "Old note")))
					 (should (equal marker (org-workflow-inbox--classification-marker)))
					 (should (eq (get-text-property (point) 'org-agenda-type) 'todo)))
				       (pcase-let ((`(,primary ,candidate) (org-workflow-workbench-test-panes)))
					 (with-current-buffer primary
					   (should-not (string-match-p "^收集箱$\\|未来 7 天" (buffer-string))))
					 (with-current-buffer candidate
					   (should (string-match-p "待安排" (buffer-string)))
					   (should-not (string-match-p "未来 7 天" (buffer-string)))))))

(ert-deftest org-workflow-agenda-inbox-historical-arrangement-enters-queue-and-undo-restores ()
  (org-workflow-agenda-inbox-test-with-files (list org-workflow-agenda-inbox-test-source)
				       (let* ((org-agenda-files nil) (org-workflow-agenda-last-plan nil)
					      (directory (make-temp-file "inbox-undo-" t))
					      (org-workflow-store-enabled t)
					      (org-workflow-store-file (expand-file-name "facts.sqlite" directory))
					      (org-workflow-store--connection nil) (org-workflow-store--path nil)
					      (org-id-locations-file (expand-file-name "ids" directory))
					      (org-id-locations (make-hash-table :test #'equal)) (org-id-files nil)
					      (org-workflow-target-selected-marker nil) (org-workflow-target-stack nil)
					      (org-workflow-current-changed-hook nil) (org-workflow-stack-empty-hook nil))
					 (unwind-protect
					     (progn
					       (org-workflow-workbench-test-open)
					       (let* ((marker (copy-marker (my/org-mouse-test-row "Old note")))
						      (source (with-current-buffer (marker-buffer marker) (buffer-string))))
						 (org-workflow-agenda-plan-morning)
						 (should (member "Old note" (mapcar #'org-workflow-target-entry-title
										    (org-workflow-target--ordered-entries))))
						 (my/org-mouse-test-row "Old note")
						 (should-not (get-text-property (point) 'org-workflow-agenda-inbox-entry))
						 (should-not org-agenda-files)
						 (org-workflow-agenda-undo-plan)
						 (my/org-mouse-test-row "Old note")
						 (should (get-text-property (point) 'org-workflow-agenda-inbox-entry))
						 (org-workflow-agenda-plan-at "2026-08-18" ?A)
						 (should-not (member "Old note" (org-workflow-workbench-test-titles)))
						 (let* ((images (org-workflow-store--decode
								 (caar (sqlite-select (org-workflow-store--db)
										      "SELECT after_text FROM operations ORDER BY rowid DESC LIMIT 1")))))
						   (should (assoc (buffer-file-name (marker-buffer marker)) images)))
						 (org-workflow-agenda-undo-plan)
						 (my/org-mouse-test-row "Old note")
						 (should (get-text-property (point) 'org-workflow-agenda-inbox-entry))
						 (let ((before-failure (org-with-point-at marker (buffer-string)))
						       (execute (symbol-function 'sqlite-execute)))
						   (cl-letf (((symbol-function 'sqlite-execute)
							      (lambda (db sql &rest args)
								(if (equal sql "COMMIT") (error "Injected database commit failure")
								  (apply execute db sql args)))))
						     (should-error (org-workflow-agenda-plan-at "2026-08-18" ?A)))
						   (should (equal before-failure (org-with-point-at marker (buffer-string))))
						   (should (member "Old note" (org-workflow-workbench-test-titles))))
						 (org-with-point-at marker
								    (should-not (org-entry-get nil "SCHEDULED"))
								    (should-not (nth 3 (org-heading-components)))
								    (should (string-match-p "Keep the original body" (buffer-string))))))
					   (when (and org-workflow-store--connection
						      (org-workflow-store--live-p org-workflow-store--connection))
					     (sqlite-close org-workflow-store--connection))
					   (delete-directory directory t)))))

(ert-deftest org-workflow-agenda-inbox-complete-refreshes-review-without-copying-content ()
  (org-workflow-agenda-inbox-test-with-files (list org-workflow-agenda-inbox-test-source)
				       (org-workflow-workbench-test-open)
				       (let ((marker (copy-marker (my/org-mouse-test-row "Old note"))))
					 (org-workflow-agenda-mouse--select marker nil)
					 (org-workflow-inbox-state-done)
					 (org-with-point-at marker
							    (should (equal "DONE" (org-get-todo-state)))
							    (should (string-match-p "Keep the original body" (buffer-string))))
					 (should-not org-agenda-bulk-marked-entries)
					 (should-not org-workflow-agenda-mouse--anchor)
					 (my/org-mouse-test-row "Old note")
					 (should-not (get-text-property (point) 'org-workflow-agenda-inbox-entry))
					 (should (eq 'completed (org-workflow-agenda-mouse--row-kind))))))

(ert-deftest org-workflow-agenda-inbox-refile-refreshes-and-rejects-batch-classification ()
  (org-workflow-agenda-inbox-test-with-files
   (list org-workflow-agenda-inbox-test-source "#+filetags: :project:\n* Someday\n")
   (let ((org-workflow-projects-file (cadr files)))
     (org-workflow-workbench-test-open)
     (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Old note") nil)
     (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Current idea") 'control)
     (should-error (org-workflow-inbox--classification-marker) :type 'user-error)
     (org-workflow-agenda--clear-selection)
     (my/org-mouse-test-row "Old note")
     (org-workflow-inbox-classify-someday)
     (should-not (member "Old note" (org-workflow-workbench-test-titles)))
     (with-current-buffer (find-file-noselect org-workflow-projects-file)
       (should (string-match-p "Old note" (buffer-string)))
       (should (string-match-p "Keep the original body" (buffer-string)))))))

(ert-deftest org-workflow-agenda-inbox-mouse-menu-and-native-filter ()
  (org-workflow-agenda-inbox-test-with-files (list org-workflow-agenda-inbox-test-source)
				       (org-workflow-workbench-test-open)
				       (my/org-mouse-test-row "Old note")
				       (let ((menu (org-workflow-agenda-mouse--menu)))
					 (should (assq 'classify (cdr menu)))
					 (should (assq 'complete (cdr menu))))
				       (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Old note") nil)
				       (org-workflow-agenda-mouse--select (my/org-mouse-test-row "Current idea") 'control)
				       (let ((menu (org-workflow-agenda-mouse--menu)))
					 (should-not (plist-get (nthcdr 3 (cdr (assq 'classify (cdr menu)))) :enable)))
				       (org-workflow-agenda-filter-deep)
				       (should-not org-agenda-bulk-marked-entries)
				       (my/org-mouse-test-row "Old note")
				       (should (invisible-p (point)))
				       (my/org-mouse-test-row "Current idea")
				       (should-not (invisible-p (point)))))

(ert-deftest org-workflow-agenda-inbox-removes-note-route-and-future-menu-only ()
  (should-not (fboundp 'org-workflow-inbox-classify-note))
  (should-error (transient-get-suffix 'org-workflow-inbox-classify "n"))
  (should-error (transient-get-suffix 'org-workflow-agenda-view-menu "v"))
  (should (transient-get-suffix 'org-workflow-inbox-classify "p"))
  (should (assoc "n" org-capture-templates)))

(ert-deftest org-workflow-agenda-inbox-link-label-keeps-original-classification-identity ()
  (org-workflow-agenda-inbox-test-with-files
      '("#+filetags: :area:\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2020-01-01\n:END:\n** TODO [[https://example.org/a?q=1][Collected link]]\nOriginal body\n")
    (org-workflow-workbench-test-open)
    (should (string-match-p "Collected link" (buffer-string)))
    (should-not (string-match-p "example.org" (buffer-string)))
    (goto-char (point-min)) (search-forward "Collected link") (beginning-of-line)
    (let ((marker (org-workflow-inbox--classification-marker)))
      (org-with-point-at marker
        (should (string-match-p (regexp-quote "https://example.org/a?q=1") (buffer-string)))
        (should-not (buffer-modified-p))))))

(ert-deftest org-workflow-agenda-inbox-does-not-inherit-source-heading-faces ()
  (org-workflow-agenda-inbox-test-with-files
      '("#+filetags: :area:\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2020-01-01\n:END:\n** TODO Collected task :@tiny:\n")
    (with-current-buffer (find-file-noselect (car files))
      (goto-char (point-min)) (search-forward "Collected task")
      (add-text-properties (- (point) (length "Collected task")) (point)
                           '(face org-level-2 font-lock-face org-level-2 display (height 1.5))))
    (org-workflow-workbench-test-open)
    (goto-char (point-min)) (search-forward "Collected task")
    (let ((start (- (point) (length "Collected task"))))
      (should-not (get-text-property start 'face))
      (should-not (get-text-property start 'font-lock-face))
      (should-not (get-text-property start 'display))
      (should (markerp (get-text-property start 'org-hd-marker)))
      (should (equal "TODO" (get-text-property start 'todo-state))))))

(ert-deftest org-workflow-agenda-commitment-marks-title-without-synthetic-tags ()
  (org-workflow-agenda-inbox-test-with-files
      '("* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2020-01-01\n:END:\n** TODO Committed task :@tiny:\n** TODO Ordinary task :@deep:\n")
    (cl-letf (((symbol-function 'org-workflow--promise-p)
               (lambda (&rest _) (equal (org-get-heading t t t t) "Committed task")))
              ((symbol-function 'org-workflow-display-tags)
               (lambda (&rest _) (cons "promise" (org-get-tags)))))
      (org-workflow-workbench-test-open)
      (should-not (string-match-p "promise" (buffer-string)))
      (goto-char (point-min)) (search-forward "Committed task")
      (let ((start (- (point) (length "Committed task"))))
        (should-not (get-text-property start 'face))
        (should (equal "◇ " (buffer-substring-no-properties (- start 2) start)))
        (should (eq 'org-workflow-agenda-commitment (get-text-property (- start 2) 'face)))
        (should (eq 'org-priority (face-attribute 'org-workflow-agenda-commitment :inherit)))
        (should (= 1.0 (face-attribute 'org-workflow-agenda-commitment :height)))
        (should-not (face-attribute 'org-workflow-agenda-commitment :inverse-video))
        (should (eq 'unspecified (face-attribute 'org-workflow-agenda-commitment :background)))
        (should (equal '("@tiny") (get-text-property start 'tags)))
        (should (markerp (get-text-property start 'org-hd-marker))))
      (search-forward "Ordinary task")
      (should-not (get-text-property (- (point) (length "Ordinary task")) 'face))
      (should (string-match-p "@tiny\\|@deep" (buffer-string))))))

(ert-deftest org-workflow-agenda-inbox-history-queue-excludes-uncollected-and-duplicate-files ()
  (org-workflow-agenda-inbox-test-with-files
   '("#+filetags: :area:\n* 收集箱\n:PROPERTIES:\n:JOURNAL_INBOX: 2020-01-01\n:END:\n** TODO Collected\nSCHEDULED: <2026-08-17 Mon>\n* Other\n** TODO Outside collection\nSCHEDULED: <2026-08-17 Mon>\n")
   (let ((org-agenda-files nil))
     (should (equal '("Collected") (mapcar #'org-workflow-target-entry-title
                                           (org-workflow-target--collect)))))
   (let ((org-agenda-files (list (concat (file-name-directory (car files))
                                         "./" (file-name-nondirectory (car files))))))
     (should (= 2 (length (org-workflow-target--collect)))))))

(provide 'org-workflow-agenda-agenda-inbox-test)
;;; org-workflow-agenda-agenda-inbox-test.el ends here
